import { execFile } from "node:child_process";
import { existsSync, promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { type Page, type TestInfo } from "@playwright/test";
import { type ExpandedTechCandidate } from "./types";

export const CORE_TECH_IDS = [
  "acga_graph_cell_governance",
  "kernelone_agent_os",
  "turn_transaction_kernel_ledger",
  "context_plane_isolation",
  "descriptor_context_verify_packs",
  "strategy_profile_overlay_fingerprint",
  "cognitive_runtime_receipt_handoff",
  "session_continuity_engine",
  "context_catalog_graph_semantic_retrieval",
  "repo_intelligence_localizer",
  "akashic_knowledge_pipeline",
  "tool_normalization_edit_blocks",
  "change_set_validation_rollback",
  "task_market_runtime_projection",
  "cognitive_knowledge_distiller",
  "contextos_attention_phase_budgeting",
];

export const EXPANDED_TECH_CANDIDATES: ExpandedTechCandidate[] = [
  {
    id: "desktop_web_dual_runtime_entrypoint",
    title: "Dual desktop/browser runtime entrypoint",
    category: "entrypoint",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["infrastructure/scripts/run-web.js", "package.json", "src/frontend/src/api.ts"],
    gates: ["node --check infrastructure/scripts/run-web.js", "npm run dev:web -- --dry-run"],
    e2eFields: ["baseUrl", "token_source", "cors_origin", "renderer_url"],
  },
  {
    id: "browser_backend_info_fallback",
    title: "Browser backend info fallback without Electron preload",
    category: "entrypoint",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["src/frontend/src/api.ts"],
    gates: ["npm run typecheck"],
    e2eFields: ["window.__DEV_BACKEND__", "localStorage.polaris.baseUrl", "VITE_BACKEND_TOKEN"],
  },
  {
    id: "websocket_stale_token_recovery",
    title: "WebSocket stale token refresh",
    category: "entrypoint",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["src/frontend/src/api.ts"],
    gates: ["npm run typecheck"],
    e2eFields: ["ws_url_token", "cache_clear_before_connect", "403_reconnect_without_stale_token"],
  },
  {
    id: "electron_backend_supervisor_chain",
    title: "Electron backend supervisor chain",
    category: "entrypoint",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["infrastructure/scripts/run-electron.js", "src/electron/main.cjs"],
    gates: ["npm run test:e2e -- --list"],
    e2eFields: ["backend_pid", "python_path", "nats_status", "process_cleanup"],
  },
  {
    id: "electron_preload_ipc_contract",
    title: "Electron preload IPC contract",
    category: "entrypoint",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["src/electron/preload.cjs", "src/electron/main.cjs"],
    gates: ["npm run test:e2e -- --list"],
    e2eFields: ["window.polaris.getBackendInfo", "pickWorkspace", "openPath"],
  },
  {
    id: "browser_workspace_settings_fallback",
    title: "Browser workspace update via settings API",
    category: "entrypoint",
    status: "partial",
    source: "ui-api-e2e-audit",
    paths: ["src/frontend/src/api.ts", "src/backend/polaris/delivery/http/routers/settings.py"],
    gates: ["npm run test:e2e:settings"],
    e2eFields: ["settings.workspace", "ui_exception_degraded_to_http_settings"],
  },
  {
    id: "electron_secret_safe_storage",
    title: "Electron safeStorage secret bridge",
    category: "security",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["src/electron/main.cjs"],
    gates: ["npm run test:e2e:settings"],
    e2eFields: ["safeStorage.available", "encrypted_secret_present", "plaintext_absent"],
  },
  {
    id: "electron_pty_bridge",
    title: "Electron PTY bridge",
    category: "tooling",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["src/electron/main.cjs", "src/frontend/src"],
    gates: ["npm run test:e2e:panel"],
    e2eFields: ["pty_session_id", "pty_write", "pty_output", "pty_close"],
  },
  {
    id: "e2e_fixture_isolated_home_runtime_workspace",
    title: "E2E isolated HOME/runtime/workspace",
    category: "e2e",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["src/backend/polaris/tests/electron/fixtures.ts"],
    gates: ["npm run test:e2e -- --list"],
    e2eFields: ["KERNELONE_HOME", "KERNELONE_RUNTIME_ROOT", "KERNELONE_WORKSPACE", "outside_repo"],
  },
  {
    id: "e2e_automatic_evidence_attachments",
    title: "Automatic renderer/main evidence attachments",
    category: "e2e",
    status: "implemented",
    source: "ui-api-e2e-audit",
    paths: ["src/backend/polaris/tests/electron/fixtures.ts"],
    gates: ["npm run test:e2e -- --list"],
    e2eFields: ["electron-main-stdout", "electron-main-stderr", "renderer-console", "dialog-screenshot"],
  },
  {
    id: "subgraph_truth_vs_draft_reconciliation",
    title: "Subgraph truth/draft reconciliation",
    category: "governance",
    status: "gate",
    source: "graph-governance-audit",
    paths: ["src/backend/docs/graph/subgraphs", "src/backend/docs/graph/catalog/cells.yaml"],
    gates: [
      "python docs/governance/ci/scripts/run_catalog_governance_gate.py --workspace . --mode fail-on-new",
      "python -m pytest -q polaris/tests/architecture/test_graph_reality.py",
    ],
    e2eFields: ["catalog_subgraph_refs", "subgraph_yaml_files", "yaml_not_referenced_by_catalog"],
  },
  {
    id: "cell_manifest_catalog_reconciliation",
    title: "Cell manifest/catalog reconciliation",
    category: "governance",
    status: "gate",
    source: "graph-governance-audit",
    paths: ["src/backend/polaris/cells", "src/backend/polaris/tests/architecture/test_manifest_schema_canonical.py"],
    gates: ["python docs/governance/ci/scripts/run_catalog_governance_gate.py --workspace . --mode fail-on-new"],
    e2eFields: ["manifest_catalog.mismatch_count", "manifest_only", "catalog_only", "duplicate_cell_ids"],
  },
  {
    id: "single_state_owner_effects_gate",
    title: "Single state owner and declared effects gate",
    category: "governance",
    status: "gate",
    source: "graph-governance-audit",
    paths: ["src/backend/docs/graph/catalog/cells.yaml", "src/backend/docs/governance/ci/scripts/run_catalog_governance_gate.py"],
    gates: ["python docs/governance/ci/scripts/run_catalog_governance_gate.py --workspace . --mode hard-fail"],
    e2eFields: ["state_owner_duplicates", "undeclared_effects", "effects_prefix_counts"],
  },
  {
    id: "semantic_boundary_governance_gate",
    title: "Semantic boundary governance gate",
    category: "governance",
    status: "gate",
    source: "graph-governance-audit",
    paths: [
      "src/backend/polaris/cells/context/catalog",
      "src/backend/polaris/cells/context/engine",
      "src/backend/docs/governance/ci/scripts/check_semantic_boundary.py",
    ],
    gates: [
      "python docs/governance/ci/scripts/check_semantic_boundary.py",
      "python -m pytest -q polaris/tests/architecture/governance/test_semantic_boundary.py",
    ],
    e2eFields: ["compliant_sites", "non_compliant_sites", "graph_fingerprint", "descriptor_hash"],
  },
  {
    id: "canonical_code_exploration_budget_gate",
    title: "Canonical code exploration and budget gate",
    category: "governance",
    status: "gate",
    source: "graph-governance-audit",
    paths: ["src/backend/docs/governance/ci/fitness-rules.yaml", "src/backend/polaris/kernelone/context"],
    gates: [
      "python -m pytest -q polaris/cells/roles/kernel/tests/test_canonical_exploration_e2e.py",
      "python -m pytest -q polaris/kernelone/context/tests/test_context_subsystem.py",
    ],
    e2eFields: ["first_tool", "phase_order", "budget_used", "compaction_trigger_ratio"],
  },
  {
    id: "event_fact_stream_singleton_writer",
    title: "Event fact stream singleton writer",
    category: "events",
    status: "partial",
    source: "graph-governance-audit",
    paths: ["src/backend/polaris/cells/events/fact_stream", "src/backend/docs/graph/subgraphs/event_pipeline.yaml"],
    gates: [
      "python -m pytest -q polaris/tests/test_realtime_single_rail_static_guard.py polaris/delivery/tests/test_ws_stream_delivery.py",
    ],
    e2eFields: ["runtime_events_owner", "direct_event_writer_count", "runtime_v2_delivery_count"],
  },
  {
    id: "kernelone_traceability_matrix",
    title: "KernelOne traceability matrix",
    category: "governance",
    status: "partial",
    source: "graph-governance-audit",
    paths: ["src/backend/polaris/kernelone/traceability", "src/backend/docs/governance/ci/scripts/run_traceability_gate.py"],
    gates: [
      "python docs/governance/ci/scripts/run_traceability_gate.py --workspace .",
      "python -m pytest -q polaris/kernelone/traceability/tests",
    ],
    e2eFields: ["matrix_id", "nodes", "links", "missing_doc_ancestor", "gate.passed"],
  },
  {
    id: "structural_bug_governance_chain",
    title: "Structural bug governance chain",
    category: "governance",
    status: "gate",
    source: "graph-governance-audit",
    paths: [
      "src/backend/docs/governance/debt.register.yaml",
      "src/backend/polaris/cells/roles/kernel/generated/verify.pack.json",
      "src/backend/docs/governance/templates/verification-cards",
    ],
    gates: ["python -m pytest -q polaris/tests/architecture/test_structural_bug_governance_assets.py"],
    e2eFields: ["debt_ids", "verification_cards", "adrs", "residual_risks"],
  },
  {
    id: "contextos_runtime_eval_promotion_gate",
    title: "ContextOS runtime eval promotion gate",
    category: "evaluation",
    status: "gate",
    source: "graph-governance-audit",
    paths: [
      "src/backend/docs/governance/CONTEXT_OS_COGNITIVE_RUNTIME_EVAL_SUITE.md",
      "src/backend/docs/governance/ci/context-os-runtime-eval-gate.yaml",
    ],
    gates: ["python docs/governance/ci/scripts/run_context_os_runtime_eval_gate.py --report <report.json>"],
    e2eFields: ["passed", "recommended_mode", "failures", "suite_runs"],
  },
  {
    id: "tool_calling_canonical_identity_gate",
    title: "Tool-calling canonical identity gate",
    category: "tooling",
    status: "gate",
    source: "graph-governance-audit",
    paths: [
      "src/backend/docs/governance/TOOL_CALLING_CANONICAL_GATE_STANDARD.md",
      "src/backend/docs/governance/AGENTIC_TOOL_CALLING_MATRIX_V2_STANDARD.md",
      "src/backend/docs/governance/ci/scripts/run_tool_calling_canonical_gate.py",
    ],
    gates: ["python docs/governance/ci/scripts/run_tool_calling_canonical_gate.py --workspace . --role director --mode hard-fail"],
    e2eFields: ["raw_events", "stream_observed.tool_calls", "canonical_tools", "issue_count"],
  },
  {
    id: "governance_ci_staged_rollout",
    title: "Governance CI staged rollout",
    category: "governance",
    status: "gate",
    source: "graph-governance-audit",
    paths: [".github/workflows/governance-gates.yml", "src/backend/docs/governance/ci/STAGED_ROLLOUT_PLAN.md"],
    gates: [
      "python docs/governance/ci/scripts/run_catalog_governance_gate.py --workspace . --mode fail-on-new --baseline polaris/tests/architecture/allowlists/catalog_governance_gate.baseline.json --mismatch-baseline polaris/tests/architecture/allowlists/manifest_catalog_mismatches.baseline.jsonl",
    ],
    e2eFields: ["workflow_stage", "continue_on_error", "artifact_name", "stage_summary"],
  },
  {
    id: "task_market_outbox_atomic_relay",
    title: "TaskMarket outbox atomic commit and relay",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/service.py",
      "src/backend/polaris/cells/runtime/task_market/internal/store_sqlite.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_service.py",
    ],
    gates: ["fitness rule outbox_atomic", "python -m pytest -q polaris/cells/runtime/task_market/tests/test_service.py"],
    e2eFields: ["outbox_id", "status", "event_type", "sent_outbox_ids", "failed_outbox_ids"],
  },
  {
    id: "task_market_durable_pull_consumer_loop",
    title: "TaskMarket durable pull consumer loop",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/consumer_loop.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_consumer_loop.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_e2e_pipeline.py",
    ],
    gates: ["KERNELONE_TASK_MARKET_MODE=mainline-durable", "start_consumer_loops()"],
    e2eFields: ["consumer_status", "outbox_relay_running", "role_running_map", "task.status"],
  },
  {
    id: "task_market_multi_workspace_consumer_isolation",
    title: "TaskMarket multi-workspace consumer isolation",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/service.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_multi_workspace_isolation.py",
    ],
    gates: ["per-workspace ConsumerLoopManager tests"],
    e2eFields: ["workspace", "claimed_by", "task_id", "stopped_workspace_stays_stopped"],
  },
  {
    id: "task_market_lease_fsm_claim_guard",
    title: "TaskMarket lease and FSM claim guard",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/lease_manager.py",
      "src/backend/polaris/cells/runtime/task_market/internal/fsm.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_claiming_integration.py",
    ],
    gates: ["claim_work_item()", "renew_task_lease()", "StaleLeaseTokenError tests"],
    e2eFields: ["lease_token", "lease_expires_at", "claimed_by", "attempts", "version"],
  },
  {
    id: "task_market_lifecycle_cognitive_receipts",
    title: "TaskMarket lifecycle Cognitive Runtime receipts",
    category: "task_market",
    status: "sidecar",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/service.py",
      "src/backend/polaris/cells/runtime/task_market/README.agent.md",
    ],
    gates: ["mutating lifecycle transition records RecordRuntimeReceiptCommandV1"],
    e2eFields: ["metadata.last_cognitive_runtime_lifecycle", "cognitive_runtime_receipt_ids", "receipt_type"],
  },
  {
    id: "task_market_hitl_tri_council",
    title: "TaskMarket HITL authority and Tri-Council escalation",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/human_review.py",
      "src/backend/polaris/cells/runtime/task_market/public/hitl_api.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_hitl_authority.py",
    ],
    gates: ["request_human_review()", "resolve_human_review()", "sweep_escalation_timeouts()"],
    e2eFields: ["current_role", "next_role", "escalation_deadline", "resolved_by", "unauthorized_role"],
  },
  {
    id: "task_market_webhook_callback_outbox",
    title: "TaskMarket HITL webhook callback via outbox",
    category: "task_market",
    status: "sidecar",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/service.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_webhook_callback.py",
    ],
    gates: ["callback_url creates task_market.human_review_callback outbox record"],
    e2eFields: ["event_type", "payload.callback_url", "payload.action", "outbox.status"],
  },
  {
    id: "task_market_dlq_replay_error_breakdown",
    title: "TaskMarket DLQ replay and error breakdown",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/dlq.py",
      "src/backend/polaris/cells/runtime/task_market/public/dlq_api.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_dlq_replay.py",
    ],
    gates: ["fail_task_stage(to_dead_letter=True)", "replay_dlq_item()"],
    e2eFields: ["status=dead_letter", "reason", "error_code", "_replayed_at", "by_error_code"],
  },
  {
    id: "task_market_saga_compensation",
    title: "TaskMarket saga compensation",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/saga.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_saga.py",
    ],
    gates: ["register_compensation_action()", "commit_compensation_actions()", "compensate_task()"],
    e2eFields: ["metadata.saga_compensation", "manual_intervention_required", "task_market.saga_*"],
  },
  {
    id: "task_market_reconciliation_control_loop",
    title: "TaskMarket reconciliation control loop",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/reconciler.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_reconciler.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_drift_requeue.py",
    ],
    gates: ["TaskReconciliationLoop.run_once()"],
    e2eFields: ["changed_parent_count", "escalated_count", "requeued_count"],
  },
  {
    id: "task_market_revision_first_change_order",
    title: "TaskMarket revision-first change order and drift requeue",
    category: "task_market",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/public/contracts.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_revision_drift.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_impact_analyzer.py",
    ],
    gates: ["register_plan_revision()", "submit_change_order()", "detect_revision_drift()"],
    e2eFields: ["plan_revision_id", "drifted_count", "impacted_total", "affected_task_ids"],
  },
  {
    id: "task_market_dependency_dag_validator",
    title: "TaskMarket dependency DAG validator",
    category: "task_market",
    status: "sidecar",
    source: "task-market-audit",
    paths: ["src/backend/polaris/cells/runtime/task_market/tests/test_dag_validator.py"],
    gates: ["validate_dependency_dag()"],
    e2eFields: ["is_valid", "cycle_count", "cycles", "orphan_depends_on"],
  },
  {
    id: "task_market_prometheus_business_metrics",
    title: "TaskMarket Prometheus business metrics",
    category: "observability",
    status: "implemented",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/metrics.py",
      "src/backend/polaris/delivery/http/middleware/metrics.py",
    ],
    gates: ["HTTP /metrics includes task-market metrics"],
    e2eFields: ["task_market_operations_total", "task_market_queue_depth", "task_market_consumer_poll_total"],
  },
  {
    id: "task_market_otel_tracing_wrapper",
    title: "TaskMarket OTel tracing wrapper",
    category: "observability",
    status: "sidecar",
    source: "task-market-audit",
    paths: [
      "src/backend/polaris/cells/runtime/task_market/internal/tracing.py",
      "src/backend/polaris/cells/runtime/task_market/tests/test_tracing.py",
    ],
    gates: ["KERNELONE_TASK_MARKET_TRACING_ENABLED=true"],
    e2eFields: ["span_name", "operation", "task_id", "stage", "trace_id"],
  },
  {
    id: "llm_config_save_control_plane_transaction",
    title: "LLM config save as control-plane sync transaction",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/backend/polaris/delivery/http/routers/llm.py",
      "src/backend/polaris/cells/llm/provider_config/internal/settings_sync.py",
    ],
    gates: ["POST /v2/llm/config", "GET /v2/llm/status"],
    e2eFields: ["last_updated", "roles.*.provider_id", "roles.*.model", "settings.pm_model"],
  },
  {
    id: "workspace_scoped_llm_readiness_projection",
    title: "Workspace-scoped LLM readiness projection",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: ["src/backend/polaris/cells/runtime/projection/internal/llm_status.py"],
    gates: ["GET /v2/llm/status"],
    e2eFields: ["state", "blocked_roles", "factory_blocked_roles", "roles.*.readiness_issue"],
  },
  {
    id: "llm_model_identity_freshness_gate",
    title: "Model identity normalization and readiness freshness gate",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/backend/polaris/kernelone/llm/model_identity.py",
      "src/backend/polaris/cells/llm/evaluation/internal/readiness_freshness.py",
    ],
    gates: ["model_mismatch/provider_mismatch/readiness_stale diagnostics"],
    e2eFields: ["model_mismatch", "provider_mismatch", "tested_model_missing", "readiness_stale"],
  },
  {
    id: "llm_scheme_b_direct_test_context",
    title: "Scheme B direct provider test context",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/backend/polaris/cells/llm/provider_config/internal/test_context.py",
      "src/frontend/src/app/components/llm/test/streamingTest.ts",
    ],
    gates: ["POST /v2/llm/test", "POST /v2/llm/test/jetstream", "WS /v2/ws/runtime"],
    e2eFields: ["target.provider_id=direct_<type>", "target.role=connectivity", "final.ready", "final.grade"],
  },
  {
    id: "provider_request_context_redaction_boundary",
    title: "Provider request context merge and redacted error boundary",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/backend/polaris/cells/llm/provider_config/internal/provider_context.py",
      "src/backend/polaris/delivery/http/routers/providers.py",
    ],
    gates: ["GET /v2/llm/providers/{id}/health", "GET /v2/llm/providers/{id}/models"],
    e2eFields: ["ok", "status", "provider_kind", "error_code", "error_message"],
  },
  {
    id: "director_provider_runtime_support_classifier",
    title: "Director provider runtime support classifier",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/backend/polaris/cells/llm/provider_runtime/internal/runtime_support.py",
      "src/frontend/src/app/components/llm/readinessDiagnostics.ts",
    ],
    gates: ["Director runtime support readiness diagnostics"],
    e2eFields: ["roles.director.runtime_supported", "roles.director.runtime_issue", "unsupported_roles"],
  },
  {
    id: "llm_evaluation_index_dual_mirror_lock",
    title: "LLM evaluation index dual mirror with per-path lock",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: ["src/backend/polaris/cells/llm/evaluation/internal/index.py"],
    gates: ["LLM test report index reconcile"],
    e2eFields: ["reports/<run_id>.json", "last_run_id", "timestamp", "last_reconcile"],
  },
  {
    id: "evaluation_suite_failure_evidence_synthesis",
    title: "Evaluation suite failure evidence synthesis",
    category: "evaluation",
    status: "implemented",
    source: "llm-control-audit",
    paths: ["src/backend/polaris/cells/llm/evaluation/internal/runner.py"],
    gates: ["deep test", "agentic benchmark", "tool/session matrix"],
    e2eFields: ["suites[].cases[].case_id", "summary.pass_rate", "final.ready", "final.next_action"],
  },
  {
    id: "llm_interview_readiness_history",
    title: "LLM interview writes readiness history",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/frontend/src/app/components/settings/LLMSettingsBridge.tsx",
      "src/backend/polaris/cells/runtime/projection/internal/llm_status.py",
    ],
    gates: ["POST /v2/llm/interview/ask", "POST /v2/llm/interview/save"],
    e2eFields: ["saved", "report_path", "readiness_updated", "interviews.latest_by_provider"],
  },
  {
    id: "native_tool_round_orchestrator",
    title: "Native tool round orchestrator with policy results",
    category: "tooling",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/backend/polaris/cells/llm/tool_runtime/internal/orchestrator.py",
      "src/backend/polaris/cells/llm/dialogue/internal/role_dialogue.py",
    ],
    gates: ["role chat stream native tool calls"],
    e2eFields: ["tool_calls", "tool_results", "tool_feedback", "should_continue"],
  },
  {
    id: "legacy_text_tool_protocol_fail_closed",
    title: "Legacy text tool protocol fail-closed",
    category: "tooling",
    status: "implemented",
    source: "llm-control-audit",
    paths: ["src/backend/polaris/cells/llm/tool_runtime/internal/role_integrations.py"],
    gates: ["debug event tool_execution/text_tool_protocol_rejected"],
    e2eFields: ["reason=native_tool_calling_only", "protocol_violation=legacy_text_tool_protocol_disabled"],
  },
  {
    id: "permission_pdp_rbac_tool_gateway_audit",
    title: "Permission PDP with RBAC, role graph, conditions, and tool gateway audit",
    category: "security",
    status: "implemented",
    source: "llm-control-audit",
    paths: ["src/backend/polaris/cells/policy/permission/internal/permission_service.py"],
    gates: ["Director tool/file/command policy checks"],
    e2eFields: ["PermissionDecisionResult.allowed", "audit.subject", "audit.action", "unauthorized_blocked"],
  },
  {
    id: "role_profile_llm_binding_from_config",
    title: "Role profile LLM binding completed from llm_config",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/backend/polaris/cells/roles/profile/internal/registry.py",
      "src/backend/polaris/cells/roles/profile/internal/schema.py",
    ],
    gates: ["role runtime profile load after LLM settings changes"],
    e2eFields: ["provider", "model", "profile_version", "tool_policy_id"],
  },
  {
    id: "frontend_llm_save_queue_orphan_cleanup_keychain",
    title: "Frontend LLM save queue, orphan binding cleanup, and keychain env override",
    category: "llm_control",
    status: "implemented",
    source: "llm-control-audit",
    paths: [
      "src/frontend/src/app/components/settings/LLMSettingsBridge.tsx",
      "src/frontend/src/app/components/llm/utils/configSanitizer.ts",
    ],
    gates: ["Settings LLM save/delete provider UI flow"],
    e2eFields: ["llmSaving", "llmError", "orphan role cleared", "env_overrides"],
  },
  {
    id: "factory_run_audit_bundle_realtime",
    title: "Factory run audit bundle and Nats-JetStream realtime channel",
    category: "factory",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/delivery/http/routers/factory.py",
      "src/backend/polaris/cells/factory/pipeline/internal/factory_run_service.py",
      "src/backend/polaris/tests/integration/delivery/routers/test_factory_router.py",
    ],
    gates: ["GET /v2/factory/runs/{run_id}/audit-bundle", "WS /v2/ws/runtime"],
    e2eFields: ["evidence_counts.events_total", "events_tail", "summary_json", "Nats-JetStream status/event/complete"],
  },
  {
    id: "factory_pm_contract_quality_leakage_cleaning",
    title: "Factory PM contract quality gate and prompt leakage cleaning",
    category: "factory",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: ["src/backend/polaris/cells/factory/pipeline/internal/factory_run_service.py"],
    gates: ["factory pm_planning stage"],
    e2eFields: ["pm_planning.signals.json", "pm.contract_issue_detected", "deterministic_pm_contracts"],
  },
  {
    id: "factory_projection_lab_cell_ir",
    title: "Projection Lab Cell IR to traditional project projection",
    category: "factory",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/factory/pipeline/internal/projection_lab.py",
      "src/backend/polaris/cells/factory/pipeline/tests/test_projection_lab.py",
    ],
    gates: ["RunProjectionExperimentCommandV1"],
    e2eFields: ["artifact_paths", "cell_ir.wave_particle_model.wave_form", "target_cells", "verification_ok"],
  },
  {
    id: "factory_back_mapping_selective_reprojection",
    title: "Back Mapping and selective reprojection",
    category: "factory",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/factory/pipeline/internal/back_mapping.py",
      "src/backend/polaris/cells/factory/pipeline/internal/projection_change_analysis.py",
    ],
    gates: ["RefreshProjectionBackMappingCommandV1", "ReprojectProjectionExperimentCommandV1"],
    e2eFields: ["mapping_strategy", "qualified_name", "syntax_source", "impacted_cell_ids", "rewritten_files"],
  },
  {
    id: "factory_verification_guard_engine",
    title: "Verification Guard safe validation engine",
    category: "factory",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/factory/verification_guard/internal/safe_executor.py",
      "src/backend/polaris/cells/factory/verification_guard/internal/verification_engine.py",
    ],
    gates: ["VerifyCompletionCommandV1", "VerificationEngine.verify"],
    e2eFields: ["VerificationReport.status", "command_results[].return_code", "evidence_collected", "mismatch_details"],
  },
  {
    id: "immutable_archive_manifest_jsonl_index",
    title: "Immutable archive manifest and canonical JSONL index",
    category: "archive",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/archive/run_archive/internal/history_archive_service.py",
      "src/backend/polaris/kernelone/storage/history_manifest_repository.py",
      "src/backend/polaris/cells/archive/task_snapshot_archive",
      "src/backend/polaris/cells/archive/factory_archive",
    ],
    gates: ["archive_run", "archive_task_snapshot", "archive_factory_run"],
    e2eFields: ["manifest.content_hash", "source_paths", "target_path", "runs.index.jsonl.archive_timestamp"],
  },
  {
    id: "uep_runtime_stream_archive",
    title: "UEP runtime stream archive",
    category: "archive",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/archive/run_archive/internal/archive_sink.py",
      "src/backend/polaris/cells/archive/run_archive/internal/stream_archiver.py",
    ],
    gates: ["create_archive_sink(bus)", "create_stream_archiver(workspace).archive_turn"],
    e2eFields: ["stream_meta.json.archive_id", "session_id", "turn_id", "event_count", "format=jsonl.gz"],
  },
  {
    id: "control_plane_ledger_history_projection",
    title: "Control Plane Run Ledger history projection",
    category: "history",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/delivery/http/routers/history.py",
      "src/backend/polaris/delivery/http/routers/control_plane.py",
      "src/backend/polaris/tests/unit/delivery/http/routers/test_history_v2.py",
    ],
    gates: ["GET /v2/control-plane/ledger/projection", "GET /v2/history/runs?source=runtime|archived"],
    e2eFields: ["source=run_ledger_projection", "projected", "missing", "failed", "runs[].source"],
  },
  {
    id: "runtime_storage_layout_migration_reset_control",
    title: "Runtime storage layout, migration, and reset control plane",
    category: "runtime_storage",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: ["src/backend/polaris/delivery/http/routers/runtime.py"],
    gates: ["GET /v2/runtime/storage/layout", "GET /v2/runtime/migration/status", "POST /v2/runtime/reset/tasks"],
    e2eFields: ["storage_layout_mode", "classification", "policies", "archived_counts", "state_reset"],
  },
  {
    id: "runtime_artifact_store_hot_paths_orphan_recovery",
    title: "Runtime artifact store hot paths and orphan state recovery",
    category: "runtime_storage",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/runtime/artifact_store/internal/artifact_paths.py",
      "src/backend/polaris/cells/runtime/artifact_store/internal/artifacts.py",
      "src/backend/polaris/cells/runtime/artifact_store/internal/arrow_service.py",
    ],
    gates: ["ReadRuntimeArtifactQueryV1", "WriteRuntimeArtifactCommandV1", "resolve_safe_path"],
    e2eFields: ["source=runtime.artifact_store", "stale", "orphaned", "recovery_code=ENGINE_ORPHANED"],
  },
  {
    id: "memos_runtime_projection_side_list",
    title: "Memos runtime projection side list",
    category: "runtime_storage",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/delivery/http/routers/memos.py",
      "src/backend/polaris/cells/runtime/projection/internal/memos_query_service.py",
    ],
    gates: ["GET /v2/memos/list"],
    e2eFields: ["items[].name", "mtime", "summary", "task_id", "run_id"],
  },
  {
    id: "audit_evidence_bundle_task_evidence",
    title: "EvidenceBundle and TaskEvidence truncated evidence",
    category: "audit",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/audit/evidence/internal/bundle_service.py",
      "src/backend/polaris/cells/audit/evidence/internal/task_service.py",
    ],
    gates: ["create_from_working_tree", "create_from_director_run"],
    e2eFields: ["bundle_id", "base_sha", "head_sha", "working_tree_dirty", "runtime/evidence_index.jsonl"],
  },
  {
    id: "kernel_audit_hash_chain_role_session_export",
    title: "Kernel audit hash chain and role session audit export",
    category: "audit",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/kernelone/audit/runtime.py",
      "src/backend/polaris/kernelone/audit/gateway.py",
      "src/backend/polaris/cells/audit/evidence/internal/role_session_audit_service.py",
    ],
    gates: ["KernelAuditRuntime.emit_event", "AuditGateway.verify_chain", "RoleSessionAuditService.export_audit_log"],
    e2eFields: ["prev_hash", "signature", "event_id", "chain_valid", "gap_count"],
  },
  {
    id: "resident_self_learning_tick",
    title: "Resident self-learning tick from decision trace to goals/skills/experiments",
    category: "resident",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/resident/autonomy/internal/resident_runtime_service.py",
      "src/backend/polaris/cells/resident/autonomy/internal/resident_storage.py",
      "src/backend/polaris/cells/resident/autonomy/internal/meta_cognition.py",
      "src/backend/polaris/cells/resident/autonomy/internal/skill_foundry.py",
    ],
    gates: ["POST /v2/resident/tick", "GET /v2/resident/status", "GET /v2/resident/decisions"],
    e2eFields: ["runtime.tick_count", "counts.decisions", "counts.goals", "agenda.risk_register"],
  },
  {
    id: "resident_governed_goal_pm_bridge",
    title: "Resident governed goal PM bridge and execution projection",
    category: "resident",
    status: "implemented",
    source: "factory-archive-resident-audit",
    paths: [
      "src/backend/polaris/cells/resident/autonomy/internal/goal_governor.py",
      "src/backend/polaris/cells/resident/autonomy/internal/pm_bridge.py",
      "src/backend/polaris/cells/resident/autonomy/internal/execution_projection.py",
    ],
    gates: ["POST /v2/resident/goals/{id}/materialize", "POST /v2/resident/goals/{id}/run"],
    e2eFields: ["resident_goal_id", "pm_contract_path", "backup_manifest_path", "execution.stage", "execution.percent"],
  },
];

export const CANDIDATE_SOURCE_PROBE_IDS: Record<string, string[]> = {
  dual_mode_source_assets: [
    "desktop_web_dual_runtime_entrypoint",
    "browser_backend_info_fallback",
    "electron_backend_supervisor_chain",
    "electron_preload_ipc_contract",
  ],
  e2e_evidence_source_assets: [
    "e2e_fixture_isolated_home_runtime_workspace",
    "e2e_automatic_evidence_attachments",
  ],
  graph_governance_source_assets: [
    "subgraph_truth_vs_draft_reconciliation",
    "cell_manifest_catalog_reconciliation",
    "single_state_owner_effects_gate",
    "semantic_boundary_governance_gate",
    "tool_calling_canonical_identity_gate",
  ],
  task_market_source_assets: [
    "task_market_outbox_atomic_relay",
    "task_market_durable_pull_consumer_loop",
    "task_market_lease_fsm_claim_guard",
    "task_market_hitl_tri_council",
    "task_market_dlq_replay_error_breakdown",
    "task_market_saga_compensation",
    "task_market_revision_first_change_order",
  ],
  llm_control_source_assets: [
    "llm_config_save_control_plane_transaction",
    "workspace_scoped_llm_readiness_projection",
    "llm_model_identity_freshness_gate",
    "llm_scheme_b_direct_test_context",
    "native_tool_round_orchestrator",
    "permission_pdp_rbac_tool_gateway_audit",
  ],
  factory_archive_resident_source_assets: [
    "factory_run_audit_bundle_sse",
    "factory_projection_lab_cell_ir",
    "factory_verification_guard_engine",
    "immutable_archive_manifest_jsonl_index",
    "kernel_audit_hash_chain_role_session_export",
    "resident_self_learning_tick",
  ],
};

export const CANDIDATE_RUNTIME_PROBE_IDS: Record<string, string[]> = {
  backend_connection: [
    "desktop_web_dual_runtime_entrypoint",
    "browser_backend_info_fallback",
  ],
  settings_runtime_layout_api: [
    "browser_workspace_settings_fallback",
    "runtime_storage_layout_migration_reset_control",
  ],
  cognitive_runtime_receipt_handoff_roundtrip: [
    "task_market_lifecycle_cognitive_receipts",
  ],
  runtime_artifact_pm_quality_contract: [
    "factory_pm_contract_quality_leakage_cleaning",
  ],
  runtime_artifact_qa_result_receipt: [
    "factory_verification_guard_engine",
    "audit_evidence_bundle_task_evidence",
  ],
  runtime_events_tool_policy_audit: [
    "permission_pdp_rbac_tool_gateway_audit",
  ],
  llm_control_status_runtime_probe: [
    "workspace_scoped_llm_readiness_projection",
    "llm_model_identity_freshness_gate",
    "director_provider_runtime_support_classifier",
    "role_profile_llm_binding_from_config",
  ],
  llm_provider_catalog_runtime_probe: [
    "provider_request_context_redaction_boundary",
    "llm_scheme_b_direct_test_context",
  ],
  runtime_storage_readonly_control_plane_probe: [
    "runtime_storage_layout_migration_reset_control",
    "memos_runtime_projection_side_list",
  ],
  prometheus_metrics_runtime_probe: [
    "task_market_prometheus_business_metrics",
  ],
  e2e_runtime_isolation_probe: [
    "e2e_fixture_isolated_home_runtime_workspace",
  ],
  e2e_attachment_runtime_probe: [
    "e2e_automatic_evidence_attachments",
  ],
  history_archive_readonly_runtime_probe: [
    "control_plane_ledger_history_projection",
    "immutable_archive_manifest_jsonl_index",
  ],
  resident_self_learning_runtime_probe: [
    "resident_self_learning_tick",
  ],
  resident_goal_pm_bridge_runtime_probe: [
    "resident_governed_goal_pm_bridge",
  ],
  llm_interview_save_runtime_probe: [
    "llm_interview_readiness_history",
    "llm_evaluation_index_dual_mirror_lock",
  ],
  role_session_audit_export_runtime_probe: [
    "kernel_audit_hash_chain_role_session_export",
  ],
  websocket_stale_token_runtime_probe: [
    "websocket_stale_token_recovery",
  ],
  electron_preload_supervisor_runtime_probe: [
    "electron_backend_supervisor_chain",
    "electron_preload_ipc_contract",
  ],
  electron_secret_safe_storage_runtime_probe: [
    "electron_secret_safe_storage",
  ],
  electron_pty_runtime_probe: [
    "electron_pty_bridge",
  ],
  graph_subgraph_reconciliation_runtime_probe: [
    "subgraph_truth_vs_draft_reconciliation",
  ],
  cell_manifest_catalog_runtime_probe: [
    "cell_manifest_catalog_reconciliation",
  ],
  single_state_owner_effects_runtime_probe: [
    "single_state_owner_effects_gate",
  ],
  structural_bug_governance_runtime_probe: [
    "structural_bug_governance_chain",
  ],
  semantic_boundary_governance_runtime_probe: [
    "semantic_boundary_governance_gate",
  ],
  tool_calling_canonical_gate_runtime_probe: [
    "tool_calling_canonical_identity_gate",
  ],
  governance_ci_staged_rollout_runtime_probe: [
    "governance_ci_staged_rollout",
  ],
  contextos_runtime_eval_gate_runtime_probe: [
    "contextos_runtime_eval_promotion_gate",
  ],
  canonical_code_exploration_budget_runtime_probe: [
    "canonical_code_exploration_budget_gate",
  ],
  task_market_regression_runtime_probe: [
    "task_market_outbox_atomic_relay",
    "task_market_durable_pull_consumer_loop",
    "task_market_multi_workspace_consumer_isolation",
    "task_market_lease_fsm_claim_guard",
    "task_market_hitl_tri_council",
    "task_market_webhook_callback_outbox",
    "task_market_dlq_replay_error_breakdown",
    "task_market_saga_compensation",
    "task_market_reconciliation_control_loop",
    "task_market_revision_first_change_order",
    "task_market_dependency_dag_validator",
    "task_market_otel_tracing_wrapper",
  ],
  llm_config_control_plane_runtime_probe: [
    "llm_config_save_control_plane_transaction",
  ],
  permission_pdp_runtime_probe: [
    "permission_pdp_rbac_tool_gateway_audit",
  ],
  frontend_llm_settings_runtime_probe: [
    "frontend_llm_save_queue_orphan_cleanup_keychain",
  ],
  llm_evaluation_runtime_probe: [
    "evaluation_suite_failure_evidence_synthesis",
  ],
  native_tool_runtime_probe: [
    "native_tool_round_orchestrator",
    "legacy_text_tool_protocol_fail_closed",
  ],
  factory_pipeline_runtime_probe: [
    "factory_run_audit_bundle_sse",
    "factory_projection_lab_cell_ir",
    "factory_back_mapping_selective_reprojection",
    "factory_verification_guard_engine",
  ],
  archive_stream_runtime_probe: [
    "uep_runtime_stream_archive",
  ],
  runtime_artifact_store_runtime_probe: [
    "runtime_artifact_store_hot_paths_orphan_recovery",
  ],
  audit_evidence_bundle_runtime_probe: [
    "audit_evidence_bundle_task_evidence",
  ],
  event_fact_stream_runtime_probe: [
    "event_fact_stream_singleton_writer",
  ],
  kernelone_traceability_runtime_probe: [
    "kernelone_traceability_matrix",
  ],
};
