"""AGENTS.md workflow helpers for loop-pm."""

import logging
import os
from datetime import datetime

from polaris.delivery.cli.pm.config import AGENTS_DRAFT_REL, AGENTS_FEEDBACK_REL
from polaris.delivery.cli.pm.utils import truncate_text_block
from polaris.kernelone.fs.text_ops import read_file_safe
from polaris.kernelone.storage.io_paths import resolve_artifact_path

logger = logging.getLogger(__name__)


def is_usable_agents_content(text: str, *, min_bytes: int = 320) -> bool:
    """Check whether AGENTS content is structurally usable."""
    payload = str(text or "").strip()
    if not payload:
        return False
    if len(payload.encode("utf-8")) < max(int(min_bytes or 0), 120):
        return False
    lowered = payload.lower()
    if "<instructions>" not in lowered or "</instructions>" not in lowered:
        return False
    return "utf-8" in lowered


def _is_failed_draft(text: str) -> bool:
    """Check if draft text indicates a failed generation."""
    if not text:
        return True
    cleaned = text.strip()
    lowered = cleaned.lower()
    if "generation failed" in lowered:
        return True
    if "failed to write last message file" in lowered:
        return True
    if lowered.startswith("error:"):
        return True
    if "incorrect function" in lowered and "os error" in lowered:
        return True
    if "traceback (most recent call last)" in lowered:
        return True
    if "exception:" in lowered and len(cleaned) < 256:
        return True
    return bool(not is_usable_agents_content(cleaned, min_bytes=220))


def _build_fallback(docs_text: str, root_text: str, feedback_text: str, error_hint: str = "") -> str:
    """Build fallback AGENTS.md content."""
    sections: list[str] = []
    if docs_text:
        sections.append("## Project Docs (excerpt)\n" + truncate_text_block(docs_text))
    if root_text:
        sections.append("## README (excerpt)\n" + truncate_text_block(root_text))
    if feedback_text:
        sections.append("## User Feedback (apply first)\n" + truncate_text_block(feedback_text))
    if error_hint:
        sections.append(f"## Generation Note\n- fallback_reason: {error_hint}")

    body = "\n\n".join([s for s in sections if s.strip()]).strip()
    content = (
        "# AGENTS.md\n\n"
        f"> Generated by Polaris PM at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        "<INSTRUCTIONS>\n"
        "- Objective: deliver reviewable, maintainable, testable, deployable code.\n"
        "- Primary references: docs/product/requirements.md, docs/product/plan.md, docs/agent/tui_runtime.md.\n"
        "- Follow role pipeline: PM -> (ChiefEngineer optional) -> Director -> (QA optional).\n"
        "- Keep runtime evidence under logical `runtime/*` paths; project persistent data must stay in `<workspace>/.polaris`.\n"
        "- Use UTF-8 explicitly for all text file reads/writes.\n"
        "- Prefer small, verifiable increments and include concrete verification commands.\n"
        "</INSTRUCTIONS>\n\n" + (body + "\n" if body else "")
    )
    return content


def get_agents_draft_path(workspace_full: str, cache_root_full: str) -> str:
    """Get the path for the AGENTS draft file."""
    return resolve_artifact_path(workspace_full, cache_root_full, AGENTS_DRAFT_REL)


def get_agents_feedback_path(workspace_full: str, cache_root_full: str) -> str:
    """Get the path for the AGENTS feedback file."""
    try:
        return resolve_artifact_path(workspace_full, cache_root_full, AGENTS_FEEDBACK_REL)
    except (RuntimeError, ValueError):
        return os.path.join(workspace_full, AGENTS_FEEDBACK_REL.replace("/", os.sep))


def check_existing_draft(draft_full: str, feedback_full: str, feedback_text: str) -> str | None:
    """Check if an existing draft should be used."""
    if not os.path.exists(draft_full):
        return None

    existing = read_file_safe(draft_full) or ""
    if _is_failed_draft(existing):
        try:
            os.remove(draft_full)
        except (RuntimeError, ValueError) as e:
            logger.debug(f"Failed to remove failed draft: {e}")
        return None

    # Check if feedback has been updated since draft
    if feedback_text and os.path.exists(feedback_full):
        try:
            if os.path.getmtime(feedback_full) <= os.path.getmtime(draft_full):
                return draft_full
        except (RuntimeError, ValueError):
            return draft_full
    else:
        return draft_full

    return None


def gather_docs_context(workspace_full: str, cache_root_full: str) -> tuple:
    """Gather documentation context for AGENTS generation."""
    docs_sections: list[str] = []
    docs_context_parts: list[str] = []

    def _append_section(label: str, path: str) -> None:
        text = (read_file_safe(path) or "").strip()
        if not text:
            return
        docs_sections.append(text)
        docs_context_parts.append(f"## {label}\n{truncate_text_block(text)}\n")

    _append_section(
        "docs/agent/tui_runtime.md",
        os.path.join(workspace_full, "docs", "agent", "tui_runtime.md"),
    )
    _append_section("docs/tui_runtime.md", os.path.join(workspace_full, "docs", "tui_runtime.md"))
    _append_section(
        "docs/product/requirements.md",
        os.path.join(workspace_full, "docs", "product", "requirements.md"),
    )
    _append_section(
        "docs/product/plan.md",
        os.path.join(workspace_full, "docs", "product", "plan.md"),
    )
    _append_section("tui_runtime.md", os.path.join(workspace_full, "tui_runtime.md"))

    runtime_plan = resolve_artifact_path(workspace_full, cache_root_full, "runtime/contracts/plan.md")
    runtime_requirements = resolve_artifact_path(workspace_full, cache_root_full, "runtime/contracts/requirements.md")
    _append_section("runtime/contracts/plan.md", runtime_plan)
    _append_section("runtime/contracts/requirements.md", runtime_requirements)

    docs_text = "\n\n".join(docs_sections).strip()
    root_text = (read_file_safe(os.path.join(workspace_full, "tui_runtime.md")) or "").strip()
    docs_context = "\n".join(docs_context_parts).strip()
    return docs_text, root_text, docs_context


__all__ = [
    "_build_fallback",
    "_is_failed_draft",
    "check_existing_draft",
    "gather_docs_context",
    "get_agents_draft_path",
    "get_agents_feedback_path",
    "is_usable_agents_content",
]
