"""Non-Director task execution for loop-pm."""

import os
import time
from typing import Any

from polaris.cells.policy.permission.public import (
    evaluate_finops_gate,
    evaluate_policy_gate,
)
from polaris.delivery.cli.pm.chief_engineer import run_chief_engineer_task
from polaris.delivery.cli.pm.config import DEFAULT_ASSIGNEE_EXECUTION, DEFAULT_DEFECT_TICKET_FIELDS
from polaris.delivery.cli.pm.task_special import (
    build_defect_followup_task,
    extract_defect_ticket,
    validate_ticket_fields,
)
from polaris.delivery.cli.pm.tasks import normalize_assigned_to
from polaris.delivery.cli.pm.utils import (
    _normalize_audit_result,
    _slug_token,
)
from polaris.kernelone.events import emit_dialogue, emit_event
from polaris.kernelone.fs.text_ops import ensure_parent_dir, write_json_atomic
from polaris.kernelone.storage.io_paths import resolve_artifact_path


def _execute_non_director_task(
    task: dict[str, Any],
    *,
    run_id: str,
    pm_iteration: int,
    workspace_full: str = "",
    cache_root_full: str = "",
) -> dict[str, Any]:
    """Execute a single non-director task."""
    assignee = normalize_assigned_to(task.get("assigned_to"))
    task_id = str(task.get("id") or "").strip() or f"TASK-{pm_iteration:05d}"
    title = str(task.get("title") or task.get("goal") or "").strip()
    required_raw = task.get("required_evidence")
    required: dict[str, Any] = required_raw if isinstance(required_raw, dict) else {}
    result: dict[str, Any] = {
        "task_id": task_id,
        "title": title,
        "assigned_to": assignee,
        "status": "success",
        "ok": True,
        "blocking": False,
        "summary": "",
        "output": {},
        "error_code": "",
        "generated_director_task": None,
    }

    if assignee == "Architect":
        # Generate a spec.md for the architecture task
        import re

        task_goal = str(task.get("goal") or task.get("title") or "").strip()
        task_constraints = task.get("constraints") or []
        task_scope = str(task.get("spec") or "").strip()
        task_acceptance = task.get("acceptance_criteria") or []
        if isinstance(task_constraints, str):
            task_constraints = [task_constraints]
        if isinstance(task_acceptance, str):
            task_acceptance = [task_acceptance]

        spec_lines = [
            f"# Architecture Spec: {title or task_id}",
            "",
            "## Goal",
            "",
            task_goal or "TBD",
            "",
            "## Scope",
            "",
            task_scope or "TBD",
            "",
            "## Constraints",
            "",
        ]
        for c in task_constraints or ["TBD"]:
            spec_lines.append(f"- {c}")
        spec_lines.extend(
            [
                "",
                "## Acceptance Criteria",
                "",
            ]
        )
        for ac in task_acceptance or ["TBD"]:
            spec_lines.append(f"- {ac}")
        spec_lines.extend(
            [
                "",
                "## Dependencies",
                "",
            ]
        )
        deps = task.get("dependencies") or []
        if isinstance(deps, str):
            deps = [deps]
        for dep in deps or ["None"]:
            spec_lines.append(f"- {dep}")
        spec_lines.extend(
            [
                "",
                "---",
                f"_Generated by Architect (中书令) for task {task_id}_",
            ]
        )

        spec_content = "\n".join(spec_lines) + "\n"
        safe_id = re.sub(r"[^a-zA-Z0-9_-]", "_", task_id)
        spec_rel_path = f"docs/product/spec_{safe_id}.md"
        spec_full_path = os.path.join(workspace_full, spec_rel_path)
        try:
            os.makedirs(os.path.dirname(spec_full_path), exist_ok=True)
            with open(spec_full_path, "w", encoding="utf-8") as handle:
                handle.write(spec_content)
            result["summary"] = f"Architect generated spec: {spec_rel_path}"
            result["output"] = {
                "spec_path": spec_rel_path,
                "spec_summary": task_goal,
                "generated": True,
            }
        except (RuntimeError, ValueError) as exc:
            result["summary"] = f"Architect spec generation failed: {exc}"
            result["output"] = {
                "spec_summary": task_goal,
                "generated": False,
                "error": str(exc),
            }
        return result

    if assignee == "ChiefEngineer":
        try:
            ce_result = run_chief_engineer_task(
                task=task,
                workspace_full=workspace_full,
                cache_root_full=cache_root_full,
                run_id=run_id,
                pm_iteration=pm_iteration,
            )
            ok = bool(ce_result.get("ok", False))
            result["status"] = "success" if ok else "failed"
            result["ok"] = ok
            result["blocking"] = False  # Graceful: don't block on CE failure
            result["error_code"] = "" if ok else "CHIEF_ENGINEER_FAILED"
            result["summary"] = str(ce_result.get("summary") or "ChiefEngineer blueprint stage completed.").strip()
            result["output"] = {
                "analysis": ce_result.get("analysis", {}),
                "task_update": ce_result.get("task_update", {}),
            }
            return result
        except (RuntimeError, ValueError) as exc:
            result["status"] = "failed"
            result["ok"] = False
            result["blocking"] = False  # Graceful: don't block on CE error
            result["error_code"] = "CHIEF_ENGINEER_ERROR"
            result["summary"] = f"ChiefEngineer stage failed: {exc}"
            result["output"] = {"error": str(exc)}
            return result

    if assignee == "PolicyGate":
        status, output, error_code, summary = evaluate_policy_gate(task, required)
        result["status"] = status
        result["ok"] = status == "success"
        result["blocking"] = status != "success"
        result["error_code"] = error_code
        result["summary"] = summary
        result["output"] = output
        return result

    if assignee == "FinOps":
        status, output, error_code, summary = evaluate_finops_gate(task, required)
        result["status"] = status
        result["ok"] = status == "success"
        result["blocking"] = status != "success"
        result["error_code"] = error_code
        result["summary"] = summary
        result["output"] = output
        return result

    if assignee == "Auditor":
        audit_result = _normalize_audit_result(required.get("audit_result") or task.get("audit_result") or "pass")
        if audit_result == "pass":
            result["summary"] = "Auditor accepted task outcome"
            result["output"] = {"audit_result": "PASS"}
            return result
        if audit_result != "fail":
            # Graceful degradation: invalid audit_result defaults to PASS with warning
            result["summary"] = "Auditor task had invalid audit_result; defaulted to PASS"
            result["output"] = {"audit_result": "PASS", "warning": "invalid_result_defaulted"}
            return result

        defect_ticket = extract_defect_ticket(task)
        missing = validate_ticket_fields(defect_ticket, DEFAULT_DEFECT_TICKET_FIELDS)
        result["output"] = {
            "audit_result": "FAIL",
            "defect_ticket": defect_ticket if isinstance(defect_ticket, dict) else {},
            "missing_fields": missing,
        }

        # Phase A: Auditor fail-closed semantic - hard block when defect ticket is missing
        if missing:
            # Fail-closed: hard block when required defect ticket fields are missing
            result["status"] = "blocked"
            result["ok"] = False
            result["blocking"] = True  # hard_block = True
            result["error_code"] = "DEFECT_TICKET_MISSING"
            result["summary"] = "Auditor FAIL with incomplete defect ticket; BLOCKED. Missing: " + ", ".join(missing)
            return result

        # Auditor FAIL but ticket is complete - create followup task (non-blocking)
        followup_task = build_defect_followup_task(task, defect_ticket, run_id, pm_iteration)
        result["status"] = "failed"
        result["ok"] = False
        result["blocking"] = False
        result["error_code"] = "AUDITOR_FAILS_WITH_DEFECT"
        result["summary"] = "Auditor FAIL recorded; generated Director defect-loop follow-up task."
        result["generated_director_task"] = followup_task
        return result

    if assignee == "PM":
        result["summary"] = "PM-owned task retained in PM queue."
        result["output"] = {"note": "docs_or_coordination_task"}
        return result

    # Graceful degradation: route unsupported assignees to Director instead of blocking
    result["status"] = "delegated"
    result["ok"] = True
    result["blocking"] = False
    result["error_code"] = ""
    result["summary"] = f"Unsupported assignee '{assignee}' delegated to Director"
    result["output"] = {"delegated_to": "Director", "original_assignee": assignee}
    return result


def execute_non_director_tasks(
    *,
    tasks: list[dict[str, Any]],
    workspace_full: str,
    cache_root_full: str,
    run_id: str,
    pm_iteration: int,
    events_path: str = "",
    dialogue_path: str = "",
    schema_warnings: list[str] | None = None,
    verification_log_path: str = "",
) -> dict[str, Any]:
    """Execute all non-director tasks."""
    results: list[dict[str, Any]] = []
    generated_director_tasks: list[dict[str, Any]] = []
    gate_receipts: list[dict[str, Any]] = []
    hard_block = False
    blocked_reasons: list[str] = []

    from polaris.delivery.cli.pm.director_mgmt import build_run_dir

    run_dir = build_run_dir(workspace_full, cache_root_full, pm_iteration)
    queue_dir = os.path.join(run_dir, "role_queue")
    ensure_parent_dir(os.path.join(queue_dir, "placeholder"))

    for index, task in enumerate(tasks or [], start=1):
        if not isinstance(task, dict):
            continue
        task_id = str(task.get("id") or "").strip() or f"T{index:03d}"
        assignee = normalize_assigned_to(task.get("assigned_to"))
        started = time.time()
        record: dict[str, Any]
        try:
            record = _execute_non_director_task(
                task,
                run_id=run_id,
                pm_iteration=pm_iteration,
                workspace_full=workspace_full,
                cache_root_full=cache_root_full,
            )
        except (RuntimeError, ValueError) as exc:
            record = {
                "task_id": task_id,
                "title": str(task.get("title") or task.get("goal") or "").strip(),
                "assigned_to": assignee,
                "status": "blocked",
                "ok": False,
                "blocking": True,
                "summary": "Role handler execution raised exception.",
                "output": {},
                "error_code": "ROLE_HANDLER_EXCEPTION",
                "error": str(exc),
                "generated_director_task": None,
            }
        duration_ms = max(0, int((time.time() - started) * 1000))
        task_slug = _slug_token(task_id, fallback=f"task-{index:03d}")
        role_artifact_path = os.path.join(queue_dir, f"{task_slug}-{assignee.lower()}.json")
        artifact_payload = {
            "schema_version": 1,
            "run_id": run_id,
            "pm_iteration": pm_iteration,
            "task": task,
            "result": {
                "status": record.get("status"),
                "ok": bool(record.get("ok", False)),
                "blocking": bool(record.get("blocking", False)),
                "summary": str(record.get("summary") or ""),
                "error_code": str(record.get("error_code") or ""),
                "output": record.get("output") if isinstance(record.get("output"), dict) else {},
                "duration_ms": duration_ms,
            },
        }
        if record.get("generated_director_task"):
            artifact_payload["generated_director_task"] = record.get("generated_director_task")
        write_json_atomic(role_artifact_path, artifact_payload)

        if record.get("generated_director_task") and isinstance(record.get("generated_director_task"), dict):
            generated_director_tasks.append(dict(record["generated_director_task"]))

        status = str(record.get("status") or "").strip().lower()
        blocking = bool(record.get("blocking", False))
        if blocking:
            hard_block = True
            blocked_reasons.append(f"{task_id}:{record.get('error_code') or status or 'blocked'}")

        role_record = {
            "task_id": task_id,
            "assigned_to": assignee,
            "status": status or "unknown",
            "ok": bool(record.get("ok", False)),
            "blocking": blocking,
            "summary": str(record.get("summary") or ""),
            "error_code": str(record.get("error_code") or ""),
            "duration_ms": duration_ms,
            "artifact_path": role_artifact_path,
        }
        if isinstance(record.get("output"), dict):
            role_record["output"] = record.get("output")
        results.append(role_record)
        if assignee in ("PolicyGate", "FinOps"):
            gate_receipts.append(
                {
                    "task_id": task_id,
                    "assigned_to": assignee,
                    "status": role_record["status"],
                    "ok": role_record["ok"],
                    "error_code": role_record["error_code"],
                    "output": role_record.get("output", {}),
                }
            )

        emit_event(
            events_path,
            kind="status",
            actor=assignee,
            name="assignee_task_executed",
            refs={
                "task_id": task_id,
                "phase": "assignee_queue",
                "files": [role_artifact_path],
            },
            summary=str(role_record["summary"]),  # type: ignore[arg-type]
            ok=bool(role_record["ok"]),
            output={
                "status": role_record["status"],
                "blocking": role_record["blocking"],
                "error_code": role_record["error_code"],
                "artifact_path": role_artifact_path,
            },
            duration_ms=duration_ms,
            error=str(record.get("error") or ""),
        )
        emit_dialogue(
            dialogue_path,
            speaker=assignee,
            type="result",
            text=f"{assignee} handled {task_id}: {str(role_record['status']).upper()} - {role_record['summary']}",
            summary=f"{assignee} {str(role_record['status']).upper()}: {task_id}",
            run_id=run_id,
            pm_iteration=pm_iteration,
            refs={
                "task_id": task_id,
                "phase": "assignee_queue",
                "files": [role_artifact_path],
            },
            meta={
                "error_code": role_record["error_code"],
                "blocking": role_record["blocking"],
            },
        )

    payload = {
        "schema_version": 1,
        "run_id": run_id,
        "pm_iteration": pm_iteration,
        "generated_at": __import__("datetime").datetime.now().isoformat(),
        "results": results,
        "hard_block": hard_block,
        "blocked_reasons": blocked_reasons,
        "generated_director_tasks": generated_director_tasks,
        "schema_warnings": [str(item).strip() for item in (schema_warnings or []) if str(item).strip()],
        "schema_warning_count": len([str(item).strip() for item in (schema_warnings or []) if str(item).strip()]),
        "gate_receipts": gate_receipts,
        "verification_log_path": str(verification_log_path or "").strip(),
    }
    summary_path = resolve_artifact_path(
        workspace_full,
        cache_root_full,
        DEFAULT_ASSIGNEE_EXECUTION,
    )
    write_json_atomic(summary_path, payload)
    run_summary_path = os.path.join(run_dir, "state", "assignee_execution.state.json")
    write_json_atomic(run_summary_path, payload)
    emit_event(
        events_path,
        kind="status",
        actor="PM",
        name="assignee_queue_summary",
        refs={"phase": "assignee_queue", "files": [summary_path, run_summary_path]},
        summary=f"Executed {len(results)} non-Director queued tasks",
        ok=not hard_block,
        output={
            "hard_block": hard_block,
            "blocked_reasons": blocked_reasons,
            "schema_warning_count": payload.get("schema_warning_count", 0),
            "gate_receipts_count": len(gate_receipts),
            "generated_director_task_ids": [
                str(item.get("id") or "") for item in generated_director_tasks if isinstance(item, dict)
            ],
        },
        error="; ".join(blocked_reasons) if hard_block else "",
    )
    return payload


__all__ = [
    "execute_non_director_tasks",
]
