"""Defect and interrupt task helpers for loop-pm."""

import hashlib
import os
from typing import Any

from polaris.delivery.cli.pm.task_helpers import extract_defect_ticket, validate_ticket_fields
from polaris.delivery.cli.pm.utils import _normalize_scope_list


def build_defect_followup_task(
    source_task: dict[str, Any],
    defect_ticket: dict[str, Any],
    run_id: str,
    iteration: int,
) -> dict[str, Any]:
    """Build a followup task for a defect."""
    source_id = str(source_task.get("id") or "").strip() or f"AUD-{iteration:05d}"
    defect_id = str(defect_ticket.get("defect_id") or "").strip() or f"{source_id}-DEFECT"
    hash_seed = f"{run_id}|{source_id}|{defect_id}"
    followup_id = f"PM-DEFECT-{hashlib.sha1(hash_seed.encode('utf-8')).hexdigest()[:10]}"
    suspected_scope = _normalize_scope_list(defect_ticket.get("suspected_scope"))
    if not suspected_scope:
        suspected_scope = _normalize_scope_list(source_task.get("target_files"))

    expected = str(defect_ticket.get("expected") or "").strip()
    actual = str(defect_ticket.get("actual") or "").strip()
    artifact_path = str(defect_ticket.get("artifact_path") or "").strip()
    repro_steps = defect_ticket.get("repro_steps")
    repro_text = (
        ", ".join(str(item).strip() for item in repro_steps if str(item).strip())
        if isinstance(repro_steps, list)
        else str(repro_steps or "").strip()
    )

    acceptance = [
        f"Fix defect {defect_id} so actual behavior matches expected behavior.",
        "Keep the patch scope minimal and focused on suspected_scope.",
        f"Attach updated validation evidence. Prior evidence: {artifact_path or 'N/A'}.",
    ]
    if expected:
        acceptance.append(f"Expected behavior: {expected}")
    if actual:
        acceptance.append(f"Prior actual behavior: {actual}")
    if repro_text:
        acceptance.append(f"Repro steps are stable after fix: {repro_text}")

    constraints = [
        "Generated by PM defect-loop from Auditor FAIL result.",
        "Do not perform broad refactors outside suspected scope.",
    ]

    return {
        "id": followup_id,
        "priority": 1,
        "title": f"Defect fix: {defect_id}",
        "goal": f"Resolve Auditor defect {defect_id} from task {source_id}.",
        "context_files": [],
        "target_files": suspected_scope,
        "constraints": constraints,
        "acceptance": acceptance,
        "assigned_to": "Director",
        "required_evidence": {
            "source": "auditor_defect_loop",
            "source_task_id": source_id,
            "defect_ticket": defect_ticket,
        },
        "stop_conditions": ["status=success", "qa=PASS"],
    }


def build_interrupt_task(
    interrupt_text: str,
    iteration: int,
    run_id: str,
) -> dict[str, Any]:
    """Build an interrupt task."""
    cleaned = (interrupt_text or "").strip()
    lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
    title = lines[0] if lines else "Interrupt task"
    title = title.lstrip("# ").strip() or "Interrupt task"
    if len(title) > 120:
        title = title[:120].rstrip() + "..."
    task_id = f"P0-{iteration:05d}"
    acceptance = ["Interrupt request has been evaluated and executed or explicitly blocked with evidence."]
    return {
        "id": task_id,
        "priority": 0,
        "title": f"P0 Interrupt: {title}",
        "goal": cleaned or "Handle urgent interrupt request from INTERRUPT.md.",
        "context_files": ["INTERRUPT.md"],
        "target_files": [],
        "constraints": ["Treat as P0 preemption. Fail-closed on ambiguity."],
        "acceptance": acceptance,
        "acceptance_criteria": acceptance,
        "assigned_to": "Director",
        "dependencies": [],
        "status": "todo",
        "spec": f"interrupt:{run_id}",
        "required_evidence": None,
        "stop_conditions": ["status=success", "qa=PASS"],
        "source": "interrupt",
    }


def consume_interrupt_task(workspace_full: str, run_dir: str, iteration: int, run_id: str) -> dict[str, Any] | None:
    """Consume interrupt task from INTERRUPT.md if present."""
    from polaris.kernelone.fs.control_flags import interrupt_notice_path
    from polaris.kernelone.fs.text_ops import read_file_safe, write_text_atomic

    interrupt_file = interrupt_notice_path(workspace_full)
    if not os.path.isfile(interrupt_file):
        return None
    text = read_file_safe(interrupt_file) or ""
    if not text.strip():
        return None
    consumed_path = os.path.join(run_dir, "INTERRUPT.consumed.md")
    try:
        write_text_atomic(consumed_path, text)
        os.remove(interrupt_file)
    except (RuntimeError, ValueError):
        return None
    return build_interrupt_task(interrupt_text=text, iteration=iteration, run_id=run_id)


def build_resume_payload_from_last_tasks(
    last_tasks: Any,
    iteration: int,
    timestamp: str,
) -> dict[str, Any] | None:
    """Build resume payload from last tasks."""
    from polaris.delivery.cli.pm.config import MANUAL_INTERVENTION_RESUME_NOTE
    from polaris.delivery.cli.pm.tasks import normalize_pm_payload

    if not isinstance(last_tasks, dict):
        return None
    tasks = last_tasks.get("tasks")
    if not isinstance(tasks, list) or not any(isinstance(item, dict) for item in tasks):
        return None
    normalized = normalize_pm_payload(last_tasks, iteration, timestamp)
    normalized_tasks = normalized.get("tasks")
    if not isinstance(normalized_tasks, list) or not normalized_tasks:
        return None
    notes = str(normalized.get("notes") or "").strip()
    normalized["notes"] = (
        f"{notes} {MANUAL_INTERVENTION_RESUME_NOTE}".strip() if notes else MANUAL_INTERVENTION_RESUME_NOTE
    )
    return normalized


__all__ = [
    "build_defect_followup_task",
    "build_interrupt_task",
    "build_resume_payload_from_last_tasks",
    "consume_interrupt_task",
    "extract_defect_ticket",
    "validate_ticket_fields",
]
