"""PM Task Quality Gate Module.

This module provides PM task quality evaluation, validation, and autofix capabilities.
It is designed to be testable as pure functions without side effects.

This file is a thin, lossless re-export shim. The implementation was
decomposed (behavior-preserving) into a same-cell package under
``internal/quality_gate/``:

* :mod:`polaris.cells.orchestration.pm_planning.internal.quality_gate.primitives`
  - domain-agnostic, dependency-free primitives.
* :mod:`polaris.cells.orchestration.pm_planning.internal.quality_gate.domain_contracts`
  - ALL CLAUDE.md §8 game/card3d project-specific domain-contract behavior,
    isolated behind the ``_domain_contracts_enabled`` gate (env
    ``KERNELONE_PM_DOMAIN_CONTRACTS``, default-enabled).
* :mod:`polaris.cells.orchestration.pm_planning.internal.quality_gate.gate`
  - the generic, platform-clean quality gate (``evaluate_pm_task_quality`` etc.).

Importing this module resolves the identical public and privately-imported
surface as before, and re-fires the same import-time side effects.
"""

from __future__ import annotations

# Re-export the stdlib / external names the historical module bound at module
# scope so the importable surface stays byte-identical to the pre-split file.
import os as os
import re as re
from pathlib import Path as Path
from typing import Any as Any

from polaris.cells.orchestration.pm_planning.internal.dependency_validator import (
    DependencyCycleError as DependencyCycleError,
    validate_dependency_dag as validate_dependency_dag,
)
from polaris.cells.orchestration.pm_planning.internal.quality_gate.domain_contracts import (
    _CARD3D_PM_CORE_HINT_RE,
    _CARD3D_PM_DETECTION_CORE_DOMAINS,
    _CARD3D_PM_DIRECTORY_SCOPE_DOMAINS,
    _CARD3D_PM_DOMAIN_SCOPE_ALIASES,
    _CARD3D_PM_DOMAIN_SCOPE_PATHS,
    _CARD3D_PM_DOMAIN_TARGET_FILES,
    _CARD3D_PM_DOMAIN_TITLES,
    _CARD3D_PM_REQUIRED_DOMAINS,
    _CARD3D_PM_STACK_HINT_RE,
    _CARD3D_PM_TEST_TARGET_FILES,
    _CARD3D_PM_WORKSPACE_SIGNAL_PATTERNS,
    _DOMAIN_CONTRACTS_DISABLE_TOKENS,
    _GAME_PM_DOMAIN_SCOPE_PATHS,
    _GAME_PM_DOMAIN_TITLES,
    _GAME_PM_FORBIDDEN_DEPENDENCY_POLICY_RE,
    _GAME_PM_FRAGILE_ACCEPTANCE_RE,
    _GAME_PM_HINT_RE,
    _GAME_PM_MIN_TASKS,
    _GAME_PM_OFF_DOMAIN_CORE_RE,
    _GAME_PM_REQUIRED_DOMAINS,
    _GAME_PM_WORKSPACE_SIGNAL_PATTERNS,
    _append_missing_card3d_domain_tasks,
    _append_missing_game_domain_tasks,
    _attach_workspace_game_context_if_needed,
    _build_card3d_domain_repair_task,
    _build_game_domain_repair_task,
    _card3d_domain_path_roots,
    _card3d_domain_target_files,
    _card3d_domains_for_task,
    _card3d_task_is_unanchored_fallback,
    _card3d_tests_task_has_placeholder_cleanup_contract,
    _covered_card3d_domains,
    _covered_game_domains,
    _domain_contracts_enabled,
    _domain_text_hints_enabled,
    _game_domain_path_roots,
    _game_domains_for_task,
    _game_task_has_non_seed_stack_path,
    _game_task_has_policy_risk,
    _has_card3d_text_hints,
    _has_forbidden_game_dependency_policy,
    _has_fragile_game_acceptance,
    _is_card3d_pm_contract,
    _is_game_pm_contract,
    _is_game_stack_mutating_path,
    _missing_card3d_required_test_targets,
    _normalize_game_policy_path,
    _path_matches_card3d_detection_domain,
    _path_matches_card3d_domain,
    _path_matches_game_domain,
    _primary_task_evidence_path,
    _read_workspace_planning_hint_text,
    _remove_card3d_policy_incompatible_tasks_in_place,
    _remove_game_policy_incompatible_tasks_in_place,
    _repair_card3d_tests_task_contract,
    _sanitize_fragile_game_acceptance_in_place,
    _sanitize_game_dependency_policy_in_place,
    _sanitize_game_dependency_policy_value,
    _sanitize_game_policy_paths_in_place,
    _task_has_exact_seed_stack_targets,
    _workspace_has_card3d_planning_hints,
    _workspace_has_game_planning_hints,
    build_card3d_pm_required_domain_contract,
    should_apply_card3d_pm_domain_contract,
)
from polaris.cells.orchestration.pm_planning.internal.quality_gate.gate import (
    autofix_pm_contract_for_quality,
    check_quality_promote_candidate,
    evaluate_pm_task_quality,
    get_quality_gate_config,
)
from polaris.cells.orchestration.pm_planning.internal.quality_gate.primitives import (
    _CJK_CHAR_RE,
    _DETERMINISTIC_SCAFFOLD_MARKER_ERROR_RE,
    _INTERACTIVE_APP_HINT_RE,
    _PM_ACTION_TOKENS,
    _PM_CHINESE_PROMPT_LEAK_TOKENS,
    _PM_EXECUTABLE_BACKTICK_RE,
    _PM_FILE_EVIDENCE_PATH_RE,
    _PM_MEASURABLE_ASSERT_RE,
    _PM_MEASURABLE_BACKTICK_RE,
    _PM_MEASURABLE_COMMAND_RE,
    _PM_MEASURABLE_PATH_RE,
    _PM_MEASURABLE_RESULT_RE,
    _PM_NON_PATH_TEXT_RE,
    _PM_PROMPT_LEAK_TOKENS,
    _PM_SCOPE_FILENAMES,
    _PM_SCOPE_ROOTS,
    _PM_SCOPE_SUFFIXES,
    _VENDORED_MINIFIED_ASSET_RE,
    _append_deterministic_scaffold_residue_cleanup_task,
    _append_unique_text_item,
    _canonical_pm_contract_output_path,
    _coerce_pm_path_to_workspace_relative,
    _collect_task_delivery_paths,
    _collect_task_scope_paths,
    _contains_prompt_leakage,
    _dedupe_paths,
    _dedupe_text_items,
    _derive_scope_from_pm_targets,
    _deterministic_scaffold_residue_paths,
    _domain_path_roots,
    _drop_unknown_dependency_refs_in_place,
    _fallback_file_evidence_path_for_scope,
    _has_executable_or_file_acceptance_anchor,
    _has_measurable_acceptance_anchor,
    _is_concrete_pm_scope_path,
    _is_directory_scope_evidenced,
    _is_file_like_pm_scope_path,
    _is_workspace_bound_concrete_path,
    _last_task_id,
    _normalize_artifact_quality_relative_path,
    _normalize_dep_list,
    _normalize_dependency_refs_in_place,
    _normalize_path,
    _normalize_path_list,
    _normalize_text,
    _path_parts_contain_parent,
    _replace_external_roots_in_text,
    _representative_workspace_file_for_scope,
    _resolve_dependency_ref,
    _sanitize_pm_task_paths_in_place,
    _scope_paths_for_target_files,
    _steer_single_file_ui_tasks_in_place,
    _strip_unfulfillable_vendored_targets_in_place,
    _strip_wrapping_quotes,
    _task_id_at_position,
    _title_is_too_short,
    _unique_task_id,
    _unknown_dependency_refs,
    _workspace_prefix,
    _workspace_relative_path,
)
from polaris.kernelone.quality import (
    scan_workspace_artifact_quality as scan_workspace_artifact_quality,
)

__all__ = [
    "_CARD3D_PM_CORE_HINT_RE",
    "_CARD3D_PM_DETECTION_CORE_DOMAINS",
    "_CARD3D_PM_DIRECTORY_SCOPE_DOMAINS",
    "_CARD3D_PM_DOMAIN_SCOPE_ALIASES",
    "_CARD3D_PM_DOMAIN_SCOPE_PATHS",
    "_CARD3D_PM_DOMAIN_TARGET_FILES",
    "_CARD3D_PM_DOMAIN_TITLES",
    "_CARD3D_PM_REQUIRED_DOMAINS",
    "_CARD3D_PM_STACK_HINT_RE",
    "_CARD3D_PM_TEST_TARGET_FILES",
    "_CARD3D_PM_WORKSPACE_SIGNAL_PATTERNS",
    "_CJK_CHAR_RE",
    "_DETERMINISTIC_SCAFFOLD_MARKER_ERROR_RE",
    "_DOMAIN_CONTRACTS_DISABLE_TOKENS",
    "_GAME_PM_DOMAIN_SCOPE_PATHS",
    "_GAME_PM_DOMAIN_TITLES",
    "_GAME_PM_FORBIDDEN_DEPENDENCY_POLICY_RE",
    "_GAME_PM_FRAGILE_ACCEPTANCE_RE",
    "_GAME_PM_HINT_RE",
    "_GAME_PM_MIN_TASKS",
    "_GAME_PM_OFF_DOMAIN_CORE_RE",
    "_GAME_PM_REQUIRED_DOMAINS",
    "_GAME_PM_WORKSPACE_SIGNAL_PATTERNS",
    "_INTERACTIVE_APP_HINT_RE",
    "_PM_ACTION_TOKENS",
    "_PM_CHINESE_PROMPT_LEAK_TOKENS",
    "_PM_EXECUTABLE_BACKTICK_RE",
    "_PM_FILE_EVIDENCE_PATH_RE",
    "_PM_MEASURABLE_ASSERT_RE",
    "_PM_MEASURABLE_BACKTICK_RE",
    "_PM_MEASURABLE_COMMAND_RE",
    "_PM_MEASURABLE_PATH_RE",
    "_PM_MEASURABLE_RESULT_RE",
    "_PM_NON_PATH_TEXT_RE",
    "_PM_PROMPT_LEAK_TOKENS",
    "_PM_SCOPE_FILENAMES",
    "_PM_SCOPE_ROOTS",
    "_PM_SCOPE_SUFFIXES",
    "_VENDORED_MINIFIED_ASSET_RE",
    "_append_deterministic_scaffold_residue_cleanup_task",
    "_append_missing_card3d_domain_tasks",
    "_append_missing_game_domain_tasks",
    "_append_unique_text_item",
    "_attach_workspace_game_context_if_needed",
    "_build_card3d_domain_repair_task",
    "_build_game_domain_repair_task",
    "_canonical_pm_contract_output_path",
    "_card3d_domain_path_roots",
    "_card3d_domain_target_files",
    "_card3d_domains_for_task",
    "_card3d_task_is_unanchored_fallback",
    "_card3d_tests_task_has_placeholder_cleanup_contract",
    "_coerce_pm_path_to_workspace_relative",
    "_collect_task_delivery_paths",
    "_collect_task_scope_paths",
    "_contains_prompt_leakage",
    "_covered_card3d_domains",
    "_covered_game_domains",
    "_dedupe_paths",
    "_dedupe_text_items",
    "_derive_scope_from_pm_targets",
    "_deterministic_scaffold_residue_paths",
    "_domain_contracts_enabled",
    "_domain_path_roots",
    "_domain_text_hints_enabled",
    "_drop_unknown_dependency_refs_in_place",
    "_fallback_file_evidence_path_for_scope",
    "_game_domain_path_roots",
    "_game_domains_for_task",
    "_game_task_has_non_seed_stack_path",
    "_game_task_has_policy_risk",
    "_has_card3d_text_hints",
    "_has_executable_or_file_acceptance_anchor",
    "_has_forbidden_game_dependency_policy",
    "_has_fragile_game_acceptance",
    "_has_measurable_acceptance_anchor",
    "_is_card3d_pm_contract",
    "_is_concrete_pm_scope_path",
    "_is_directory_scope_evidenced",
    "_is_file_like_pm_scope_path",
    "_is_game_pm_contract",
    "_is_game_stack_mutating_path",
    "_is_workspace_bound_concrete_path",
    "_last_task_id",
    "_missing_card3d_required_test_targets",
    "_normalize_artifact_quality_relative_path",
    "_normalize_dep_list",
    "_normalize_dependency_refs_in_place",
    "_normalize_game_policy_path",
    "_normalize_path",
    "_normalize_path_list",
    "_normalize_text",
    "_path_matches_card3d_detection_domain",
    "_path_matches_card3d_domain",
    "_path_matches_game_domain",
    "_path_parts_contain_parent",
    "_primary_task_evidence_path",
    "_read_workspace_planning_hint_text",
    "_remove_card3d_policy_incompatible_tasks_in_place",
    "_remove_game_policy_incompatible_tasks_in_place",
    "_repair_card3d_tests_task_contract",
    "_replace_external_roots_in_text",
    "_representative_workspace_file_for_scope",
    "_resolve_dependency_ref",
    "_sanitize_fragile_game_acceptance_in_place",
    "_sanitize_game_dependency_policy_in_place",
    "_sanitize_game_dependency_policy_value",
    "_sanitize_game_policy_paths_in_place",
    "_sanitize_pm_task_paths_in_place",
    "_scope_paths_for_target_files",
    "_steer_single_file_ui_tasks_in_place",
    "_strip_unfulfillable_vendored_targets_in_place",
    "_strip_wrapping_quotes",
    "_task_has_exact_seed_stack_targets",
    "_task_id_at_position",
    "_title_is_too_short",
    "_unique_task_id",
    "_unknown_dependency_refs",
    "_workspace_has_card3d_planning_hints",
    "_workspace_has_game_planning_hints",
    "_workspace_prefix",
    "_workspace_relative_path",
    "autofix_pm_contract_for_quality",
    "build_card3d_pm_required_domain_contract",
    "check_quality_promote_candidate",
    "evaluate_pm_task_quality",
    "get_quality_gate_config",
    "should_apply_card3d_pm_domain_contract",
]
