import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BaseProviderSettings } from './BaseProviderSettings';
import { cyberInputClasses } from '@/app/components/ui/cyber-input-classes';
export function GeminiAPIProviderSettings({ provider, onUpdate, onValidate }) {
    const handleFieldChange = (field, value) => {
        onUpdate({ [field]: value });
    };
    return (_jsxs(BaseProviderSettings, { provider: provider, onUpdate: onUpdate, onValidate: onValidate, children: [_jsxs("div", { className: "space-y-3", children: [_jsx("h5", { className: "text-xs font-semibold text-text-main", children: "Gemini API \u914D\u7F6E" }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs text-text-muted mb-1", children: "API \u8DEF\u5F84" }), _jsx("input", { type: "text", value: provider.api_path || '/v1beta/models/{model}:generateContent', onChange: (e) => handleFieldChange('api_path', e.target.value), placeholder: "/v1beta/models/{model}:generateContent", className: cyberInputClasses }), _jsxs("p", { className: "text-[9px] text-text-dim mt-1", children: ["\u4F7F\u7528 ", '{model}', " \u5360\u4F4D\u7B26\u53EF\u6309\u6A21\u578B\u52A8\u6001\u8DEF\u7531"] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs text-text-muted mb-1", children: "\u6A21\u578B\u5217\u8868\u8DEF\u5F84" }), _jsx("input", { type: "text", value: provider.models_path || '/v1beta/models', onChange: (e) => handleFieldChange('models_path', e.target.value), placeholder: "/v1beta/models", className: cyberInputClasses })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h5", { className: "text-xs font-semibold text-text-main", children: "Gemini \u6A21\u578B" }), _jsx("div", { className: "bg-[rgba(35,25,14,0.45)] rounded-lg p-3 border border-white/10", children: _jsxs("div", { className: "space-y-2 text-xs", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-text-muted", children: "gemini-1.5-pro" }), _jsx("span", { className: "text-text-main", children: "\u2022 2M \u4E0A\u4E0B\u6587" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-text-muted", children: "gemini-1.5-flash" }), _jsx("span", { className: "text-text-main", children: "\u2022 1M \u4E0A\u4E0B\u6587" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-text-muted", children: "gemini-1.0-pro" }), _jsx("span", { className: "text-text-main", children: "\u2022 32K \u4E0A\u4E0B\u6587" })] })] }) }), _jsxs("p", { className: "text-[9px] text-text-dim", children: ["API Key \u53EF\u5728 ", _jsx("a", { href: "https://aistudio.google.com/app/apikey", target: "_blank", className: "text-accent hover:underline", children: "Google AI Studio" }), " \u83B7\u53D6"] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h5", { className: "text-xs font-semibold text-text-main", children: "\u9AD8\u7EA7\u53C2\u6570" }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs text-text-muted mb-1", children: "\u6E29\u5EA6\uFF08Temperature\uFF09" }), _jsx("input", { type: "number", value: provider.temperature ?? 0.7, onChange: (e) => {
                                    // ?? + NaN-guard (NOT `|| default`): 0 is falsy, so `0 || 0.7`
                                    // silently forced 0.7 and blocked setting temperature to 0.
                                    const parsed = parseFloat(e.target.value);
                                    handleFieldChange('temperature', Number.isNaN(parsed) ? undefined : parsed);
                                }, min: "0", max: "2", step: "any", className: cyberInputClasses })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs text-text-muted mb-1", children: "\u91CD\u8BD5\u6B21\u6570" }), _jsx("input", { type: "number", value: provider.retries || 3, onChange: (e) => handleFieldChange('retries', parseInt(e.target.value) || 3), min: "0", max: "10", className: cyberInputClasses })] })] })] }));
}
