"""Terminal console subpackage for Polaris CLI.

Re-exports all public and internal names previously available from
terminal_console.py for backward compatibility.
"""

from __future__ import annotations

# Base utilities and constants
from polaris.delivery.cli.terminal._base import (
    _ALLOWED_BACKENDS as _ALLOWED_BACKENDS,
    _EMPTY_TOOL_BLOCK_RE as _EMPTY_TOOL_BLOCK_RE,
    _EXIT_COMMANDS as _EXIT_COMMANDS,
    _HELP_COMMANDS as _HELP_COMMANDS,
    _HELP_TEXT as _HELP_TEXT,
    _JSON_RENDER_MODES as _JSON_RENDER_MODES,
    _KEYMODE_FILE as _KEYMODE_FILE,
    _KEYMODE_VALUES as _KEYMODE_VALUES,
    _KNOWN_MODELS as _KNOWN_MODELS,
    _MODEL_PRICING_PER_M as _MODEL_PRICING_PER_M,
    _ONBOARD_MARKER_PATH as _ONBOARD_MARKER_PATH,
    _ONBOARD_WELCOME_PANEL_PLAIN as _ONBOARD_WELCOME_PANEL_PLAIN,
    _ONBOARD_WELCOME_PANEL_RICH as _ONBOARD_WELCOME_PANEL_RICH,
    _OUTPUT_FORMAT_MODES as _OUTPUT_FORMAT_MODES,
    _PROMPT_STYLES as _PROMPT_STYLES,
    _SPINNER_FRAMES as _SPINNER_FRAMES,
    _UNSET as _UNSET,
    ROLE_PROMPT_SYMBOLS as ROLE_PROMPT_SYMBOLS,
    TOOL_NAME_STYLES as TOOL_NAME_STYLES,
    _apply_keymode as _apply_keymode,
    _as_mapping as _as_mapping,
    _coerce_bool as _coerce_bool,
    _detect_keymode_from_shell as _detect_keymode_from_shell,
    _format_time as _format_time,
    _get_current_model as _get_current_model,
    _get_default_keymode as _get_default_keymode,
    _get_polaris_version as _get_polaris_version,
    _get_role_symbol as _get_role_symbol,
    _get_tool_style as _get_tool_style,
    _json_event_packet as _json_event_packet,
    _json_event_text as _json_event_text,
    _normalize_json_render as _normalize_json_render,
    _normalize_output_format as _normalize_output_format,
    _normalize_prompt_style as _normalize_prompt_style,
    _normalize_role as _normalize_role,
    _print_status_bar as _print_status_bar,
    _resolve_keymode as _resolve_keymode,
    _resolve_output_format as _resolve_output_format,
    _restore_infrastructure_logs as _restore_infrastructure_logs,
    _safe_text as _safe_text,
    _save_keymode as _save_keymode,
    _set_current_model as _set_current_model,
    _show_onboarding as _show_onboarding,
    _stdout_is_tty as _stdout_is_tty,
    _suppress_infrastructure_logs as _suppress_infrastructure_logs,
    _tool_error as _tool_error,
    _tool_name as _tool_name,
    _tool_path as _tool_path,
    _tool_status as _tool_status,
    _truncate_workspace as _truncate_workspace,
)

# Commands
from polaris.delivery.cli.terminal.commands import (
    _build_role_capability_profile as _build_role_capability_profile,
    _console_display_role as _console_display_role,
    _handle_command as _handle_command,
    _resolve_role_session as _resolve_role_session,
)

# Console / entry points / SUPER mode
from polaris.delivery.cli.terminal.console import (
    SUPER_ROLE as SUPER_ROLE,
    PolarisLazyClaude as PolarisLazyClaude,
    PolarisRoleConsole as PolarisRoleConsole,
    _acknowledge_super_claims as _acknowledge_super_claims,
    _claim_super_tasks_from_market as _claim_super_tasks_from_market,
    _director_output_suggests_more_work as _director_output_suggests_more_work,
    _orch_build_handoff_kwargs as _orch_build_handoff_kwargs,
    _orch_execute_with_retry as _orch_execute_with_retry,
    _orch_inject_constraint as _orch_inject_constraint,
    _orch_update_context as _orch_update_context,
    _persist_super_tasks_to_board as _persist_super_tasks_to_board,
    _run_batch_mode as _run_batch_mode,
    _run_director_execution_loop as _run_director_execution_loop,
    _run_super_turn as _run_super_turn,
    _run_super_turn_orchestrator as _run_super_turn_orchestrator,
    _trigger_slm_warmup as _trigger_slm_warmup,
    run_director_console as run_director_console,
    run_role_console as run_role_console,
)

# Events / streaming
from polaris.delivery.cli.terminal.events import (
    _run_streaming_turn as _run_streaming_turn,
    _stream_turn as _stream_turn,
)

# Layout and formatting
from polaris.delivery.cli.terminal.layout import (
    _build_render_state as _build_render_state,
    _ConsoleRenderState as _ConsoleRenderState,
    _create_turn_spinner as _create_turn_spinner,
    _print_banner as _print_banner,
    _PromptRenderer as _PromptRenderer,
    _spinner_enabled_for_stream as _spinner_enabled_for_stream,
    _spinner_output_stream as _spinner_output_stream,
    _TurnExecutionResult as _TurnExecutionResult,
    _TurnSpinner as _TurnSpinner,
)

# Renderers
from polaris.delivery.cli.terminal.renderers import (
    _ANSI_BOLD as _ANSI_BOLD,
    _ANSI_CYAN as _ANSI_CYAN,
    _ANSI_DIM as _ANSI_DIM,
    _ANSI_GREEN as _ANSI_GREEN,
    _ANSI_RED as _ANSI_RED,
    _ANSI_RESET as _ANSI_RESET,
    _ANSI_YELLOW as _ANSI_YELLOW,
    _build_structured_json_event as _build_structured_json_event,
    _debug_body_text as _debug_body_text,
    _estimate_cost as _estimate_cost,
    _extract_diff_text as _extract_diff_text,
    _extract_token_usage as _extract_token_usage,
    _has_diff_content as _has_diff_content,
    _print_debug_event as _print_debug_event,
    _print_error_event as _print_error_event,
    _print_json_with_rich as _print_json_with_rich,
    _print_stream_json_event as _print_stream_json_event,
    _print_structured_json_event as _print_structured_json_event,
    _print_token_stats as _print_token_stats,
    _print_tool_call_rich as _print_tool_call_rich,
    _print_tool_result_rich as _print_tool_result_rich,
    _render_diff_ansi as _render_diff_ansi,
    _style_debug_line as _style_debug_line,
    _supports_dim_debug as _supports_dim_debug,
)

__all__ = [
    "ROLE_PROMPT_SYMBOLS",
    "SUPER_ROLE",
    "TOOL_NAME_STYLES",
    "_ALLOWED_BACKENDS",
    "_ANSI_BOLD",
    "_ANSI_CYAN",
    "_ANSI_DIM",
    "_ANSI_GREEN",
    "_ANSI_RED",
    "_ANSI_RESET",
    "_ANSI_YELLOW",
    "_EMPTY_TOOL_BLOCK_RE",
    "_EXIT_COMMANDS",
    "_HELP_COMMANDS",
    "_HELP_TEXT",
    "_JSON_RENDER_MODES",
    "_KEYMODE_FILE",
    "_KEYMODE_VALUES",
    "_KNOWN_MODELS",
    "_MODEL_PRICING_PER_M",
    "_ONBOARD_MARKER_PATH",
    "_ONBOARD_WELCOME_PANEL_PLAIN",
    "_ONBOARD_WELCOME_PANEL_RICH",
    "_OUTPUT_FORMAT_MODES",
    "_PROMPT_STYLES",
    "_SPINNER_FRAMES",
    "PolarisLazyClaude",
    "PolarisRoleConsole",
    "_ConsoleRenderState",
    "_PromptRenderer",
    "_TurnExecutionResult",
    "_TurnSpinner",
    "_acknowledge_super_claims",
    "_apply_keymode",
    "_as_mapping",
    "_build_render_state",
    "_build_role_capability_profile",
    "_build_structured_json_event",
    "_claim_super_tasks_from_market",
    "_coerce_bool",
    "_console_display_role",
    "_create_turn_spinner",
    "_debug_body_text",
    "_detect_keymode_from_shell",
    "_director_output_suggests_more_work",
    "_estimate_cost",
    "_extract_diff_text",
    "_extract_token_usage",
    "_format_time",
    "_get_current_model",
    "_get_default_keymode",
    "_get_polaris_version",
    "_get_role_symbol",
    "_get_tool_style",
    "_handle_command",
    "_has_diff_content",
    "_normalize_json_render",
    "_normalize_output_format",
    "_normalize_prompt_style",
    "_normalize_role",
    "_orch_build_handoff_kwargs",
    "_orch_execute_with_retry",
    "_orch_inject_constraint",
    "_orch_update_context",
    "_persist_super_tasks_to_board",
    "_print_banner",
    "_print_debug_event",
    "_print_error_event",
    "_print_json_with_rich",
    "_print_status_bar",
    "_print_stream_json_event",
    "_print_structured_json_event",
    "_print_token_stats",
    "_print_tool_call_rich",
    "_print_tool_result_rich",
    "_render_diff_ansi",
    "_resolve_keymode",
    "_resolve_output_format",
    "_resolve_role_session",
    "_restore_infrastructure_logs",
    "_run_batch_mode",
    "_run_director_execution_loop",
    "_run_streaming_turn",
    "_run_super_turn",
    "_run_super_turn_orchestrator",
    "_safe_text",
    "_save_keymode",
    "_set_current_model",
    "_show_onboarding",
    "_spinner_enabled_for_stream",
    "_spinner_output_stream",
    "_stdout_is_tty",
    "_stream_turn",
    "_style_debug_line",
    "_supports_dim_debug",
    "_suppress_infrastructure_logs",
    "_tool_error",
    "_tool_name",
    "_tool_path",
    "_tool_status",
    "_trigger_slm_warmup",
    "_truncate_workspace",
    "run_director_console",
    "run_role_console",
]
