"""Summarize the catalog governance gate report.

This script accepts either:
1. ``--input <report.json>`` to read a report file generated by
   ``run_catalog_governance_gate.py --report ...``
2. raw JSON from stdin

It prints a stable text summary suitable for terminal usage in both
PowerShell and Bash workflows.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Summarize catalog governance gate output.")
    parser.add_argument(
        "--input",
        help="Path to a JSON report generated by run_catalog_governance_gate.py. If omitted, read JSON from stdin.",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=10,
        help="Number of top cells to print for each summary section.",
    )
    return parser.parse_args()


def _load_payload(input_path: str | None) -> dict[str, Any]:
    if input_path:
        return json.loads(Path(input_path).read_text(encoding="utf-8"))
    return json.load(sys.stdin)


def _extract_depends_on_source_cell(message: str) -> str | None:
    marker = " imports "
    suffix = " but does not declare it in depends_on"
    if marker not in message or suffix not in message:
        return None
    source, remainder = message.split(marker, 1)
    if suffix not in remainder:
        return None
    return source.strip() or None


def _render_top_counter(title: str, counter: Counter[str], *, top: int) -> list[str]:
    lines = [f"=== {title} ==="]
    if not counter:
        lines.append("(none)")
        return lines
    for key, value in counter.most_common(max(1, top)):
        lines.append(f"{key}: {value}")
    return lines


def build_summary(payload: dict[str, Any], *, top: int) -> str:
    issues = payload.get("issues") if isinstance(payload.get("issues"), list) else []
    manifest_catalog = payload.get("manifest_catalog") if isinstance(payload.get("manifest_catalog"), dict) else {}
    mismatches = manifest_catalog.get("mismatches") if isinstance(manifest_catalog.get("mismatches"), list) else []

    depends_on_counter: Counter[str] = Counter()
    for issue in issues:
        if not isinstance(issue, dict):
            continue
        source_cell = _extract_depends_on_source_cell(str(issue.get("message") or ""))
        if source_cell:
            depends_on_counter[source_cell] += 1

    mismatch_cell_counter: Counter[str] = Counter()
    mismatch_field_counter: Counter[str] = Counter()
    for mismatch in mismatches:
        if not isinstance(mismatch, dict):
            continue
        cell_id = str(mismatch.get("cell_id") or "").strip()
        field = str(mismatch.get("field") or "").strip()
        if cell_id:
            mismatch_cell_counter[cell_id] += 1
        if field:
            mismatch_field_counter[field] += 1

    lines = [
        "=== SUMMARY ===",
        f"workspace: {payload.get('workspace', '')}",
        f"mode: {payload.get('mode', '')}",
        f"issue_count: {payload.get('issue_count', 0)}",
        f"blocker_count: {payload.get('blocker_count', 0)}",
        f"high_count: {payload.get('high_count', 0)}",
        f"new_issue_count: {payload.get('new_issue_count', 0)}",
        f"mismatch_count: {manifest_catalog.get('mismatch_count', 0)}",
        f"new_mismatch_count: {manifest_catalog.get('new_mismatch_count', 0)}",
        "",
    ]
    lines.extend(_render_top_counter("depends_on_drift top cells", depends_on_counter, top=top))
    lines.append("")
    lines.extend(_render_top_counter("manifest_mismatch top cells", mismatch_cell_counter, top=top))
    lines.append("")
    lines.extend(_render_top_counter("manifest_mismatch fields", mismatch_field_counter, top=top))
    return "\n".join(lines)


def main() -> int:
    args = _parse_args()
    payload = _load_payload(args.input)
    print(build_summary(payload, top=max(1, int(args.top))))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
