"""Backward-compatibility shim for polaris.delivery.cli.terminal_console.

All implementation has been moved to the terminal/ subpackage.
Import from polaris.delivery.cli.terminal for new code.
"""

from __future__ import annotations

# Backward-compatibility: these must be mutable module-level bindings so that
# tests which monkeypatch terminal_console._ONBOARD_MARKER_PATH affect the
# value seen by _show_onboarding.
import polaris.delivery.cli.terminal._base as _base_mod

# Re-export everything from the new terminal subpackage to maintain
# backward compatibility with existing imports.
from polaris.delivery.cli.terminal import (
    _ALLOWED_BACKENDS,
    _ANSI_BOLD,
    _ANSI_CYAN,
    _ANSI_DIM,
    _ANSI_GREEN,
    _ANSI_RED,
    _ANSI_RESET,
    _ANSI_YELLOW,
    _EMPTY_TOOL_BLOCK_RE,
    _EXIT_COMMANDS,
    _HELP_COMMANDS,
    _HELP_TEXT,
    _JSON_RENDER_MODES,
    _KEYMODE_FILE,
    _KEYMODE_VALUES,
    _KNOWN_MODELS,
    _MODEL_PRICING_PER_M,
    _OUTPUT_FORMAT_MODES,
    _PROMPT_STYLES,
    _SPINNER_FRAMES,
    _UNSET,
    ROLE_PROMPT_SYMBOLS,
    SUPER_ROLE,
    TOOL_NAME_STYLES,
    PolarisLazyClaude,
    PolarisRoleConsole,
    _acknowledge_super_claims,
    _apply_keymode,
    _as_mapping,
    _build_render_state,
    _build_role_capability_profile,
    _build_structured_json_event,
    _claim_super_tasks_from_market,
    _coerce_bool,
    _console_display_role,
    _ConsoleRenderState,
    _create_turn_spinner,
    _debug_body_text,
    _detect_keymode_from_shell,
    _director_output_suggests_more_work,
    _estimate_cost,
    _extract_diff_text,
    _extract_token_usage,
    _format_time,
    _get_current_model,
    _get_default_keymode,
    _get_polaris_version,
    _get_role_symbol,
    _get_tool_style,
    _handle_command,
    _has_diff_content,
    _json_event_packet,
    _json_event_text,
    _normalize_json_render,
    _normalize_output_format,
    _normalize_prompt_style,
    _normalize_role,
    _orch_build_handoff_kwargs,
    _orch_execute_with_retry,
    _orch_inject_constraint,
    _orch_update_context,
    _persist_super_tasks_to_board,
    _print_banner,
    _print_debug_event,
    _print_error_event,
    _print_json_with_rich,
    _print_status_bar,
    _print_stream_json_event,
    _print_structured_json_event,
    _print_token_stats,
    _print_tool_call_rich,
    _print_tool_result_rich,
    _PromptRenderer,
    _render_diff_ansi,
    _resolve_keymode,
    _resolve_output_format,
    _resolve_role_session,
    _restore_infrastructure_logs,
    _run_batch_mode,
    _run_director_execution_loop,
    _run_streaming_turn,
    _run_super_turn,
    _run_super_turn_orchestrator,
    _safe_text,
    _save_keymode,
    _set_current_model,
    _spinner_enabled_for_stream,
    _spinner_output_stream,
    _stdout_is_tty,
    _stream_turn,
    _style_debug_line,
    _supports_dim_debug,
    _suppress_infrastructure_logs,
    _tool_error,
    _tool_name,
    _tool_path,
    _tool_status,
    _trigger_slm_warmup,
    _truncate_workspace,
    _TurnExecutionResult,
    _TurnSpinner,
    run_director_console,
    run_role_console,
)

_ONBOARD_MARKER_PATH = _base_mod._ONBOARD_MARKER_PATH
_ONBOARD_WELCOME_PANEL_RICH = _base_mod._ONBOARD_WELCOME_PANEL_RICH
_ONBOARD_WELCOME_PANEL_PLAIN = _base_mod._ONBOARD_WELCOME_PANEL_PLAIN


def _show_onboarding() -> None:
    """Wrapper that respects monkeypatches of terminal_console._ONBOARD_MARKER_PATH."""
    old_path = _base_mod._ONBOARD_MARKER_PATH
    _base_mod._ONBOARD_MARKER_PATH = _ONBOARD_MARKER_PATH
    try:
        from polaris.delivery.cli.terminal._base import _show_onboarding as _base_show_onboarding

        _base_show_onboarding()
    finally:
        _base_mod._ONBOARD_MARKER_PATH = old_path


__all__ = [
    "ROLE_PROMPT_SYMBOLS",
    "SUPER_ROLE",
    "TOOL_NAME_STYLES",
    "_ALLOWED_BACKENDS",
    "_ANSI_BOLD",
    "_ANSI_CYAN",
    "_ANSI_DIM",
    "_ANSI_GREEN",
    "_ANSI_RED",
    "_ANSI_RESET",
    "_ANSI_YELLOW",
    "_EMPTY_TOOL_BLOCK_RE",
    "_EXIT_COMMANDS",
    "_HELP_COMMANDS",
    "_HELP_TEXT",
    "_JSON_RENDER_MODES",
    "_KEYMODE_FILE",
    "_KEYMODE_VALUES",
    "_KNOWN_MODELS",
    "_MODEL_PRICING_PER_M",
    "_ONBOARD_MARKER_PATH",
    "_ONBOARD_WELCOME_PANEL_PLAIN",
    "_ONBOARD_WELCOME_PANEL_RICH",
    "_OUTPUT_FORMAT_MODES",
    "_PROMPT_STYLES",
    "_SPINNER_FRAMES",
    "_UNSET",
    "PolarisLazyClaude",
    "PolarisRoleConsole",
    "_ConsoleRenderState",
    "_PromptRenderer",
    "_TurnExecutionResult",
    "_TurnSpinner",
    "_acknowledge_super_claims",
    "_apply_keymode",
    "_as_mapping",
    "_build_render_state",
    "_build_role_capability_profile",
    "_build_structured_json_event",
    "_claim_super_tasks_from_market",
    "_coerce_bool",
    "_console_display_role",
    "_create_turn_spinner",
    "_debug_body_text",
    "_detect_keymode_from_shell",
    "_director_output_suggests_more_work",
    "_estimate_cost",
    "_extract_diff_text",
    "_extract_token_usage",
    "_format_time",
    "_get_current_model",
    "_get_default_keymode",
    "_get_polaris_version",
    "_get_role_symbol",
    "_get_tool_style",
    "_handle_command",
    "_has_diff_content",
    "_json_event_packet",
    "_json_event_text",
    "_normalize_json_render",
    "_normalize_output_format",
    "_normalize_prompt_style",
    "_normalize_role",
    "_orch_build_handoff_kwargs",
    "_orch_execute_with_retry",
    "_orch_inject_constraint",
    "_orch_update_context",
    "_persist_super_tasks_to_board",
    "_print_banner",
    "_print_debug_event",
    "_print_error_event",
    "_print_json_with_rich",
    "_print_status_bar",
    "_print_stream_json_event",
    "_print_structured_json_event",
    "_print_token_stats",
    "_print_tool_call_rich",
    "_print_tool_result_rich",
    "_render_diff_ansi",
    "_resolve_keymode",
    "_resolve_output_format",
    "_resolve_role_session",
    "_restore_infrastructure_logs",
    "_run_batch_mode",
    "_run_director_execution_loop",
    "_run_streaming_turn",
    "_run_super_turn",
    "_run_super_turn_orchestrator",
    "_safe_text",
    "_save_keymode",
    "_set_current_model",
    "_show_onboarding",
    "_spinner_enabled_for_stream",
    "_spinner_output_stream",
    "_stdout_is_tty",
    "_stream_turn",
    "_style_debug_line",
    "_supports_dim_debug",
    "_suppress_infrastructure_logs",
    "_tool_error",
    "_tool_name",
    "_tool_path",
    "_tool_status",
    "_trigger_slm_warmup",
    "_truncate_workspace",
    "run_director_console",
    "run_role_console",
]
