"""Public boundary for `chief_engineer.blueprint` cell."""

from polaris.cells.chief_engineer.blueprint.internal.blueprint_persistence import (
    BlueprintPersistence,
)

# Contract types (dataclasses, enums, errors) are owned by contracts.py.
# Import them from there directly so the public boundary does not depend
# on service.py re-exporting them (which a linter may strip as "unused").
from .contracts import (
    ADREventV1,
    ADRRecordV1,
    ADRStatus,
    ArchitectureDecisionV1,
    ArtifactObligationV1,
    ArtifactSemanticRoleV1,
    BuildChiefEngineerBlueprintPortfolioCommandV1,
    ChiefEngineerBehaviorExampleV1,
    ChiefEngineerBehaviorInvariantV1,
    ChiefEngineerBlueprintError,
    ChiefEngineerBlueprintErrorV1,
    ChiefEngineerBlueprintPortfolioV1,
    ChiefEngineerPortfolioStructuralRecoveryV1,
    ChiefEngineerPortfolioTaskV1,
    ChiefEngineerProjectInterfaceContractV1,
    ChiefEngineerSemanticRepairCandidateV1,
    ChiefEngineerSemanticRepairDiagnosisV1,
    ChiefEngineerSemanticRepairOperationV1,
    ChiefEngineerSemanticRepairPatchV1,
    ChiefEngineerSemanticRepairReceiptV1,
    ChiefEngineerSharedBehaviorContractV1,
    EntrypointKindV1,
    EntrypointObligationV1,
    GenerateTaskBlueprintCommandV1,
    GetBlueprintStatusQueryV1,
    GovernanceSummaryV1,
    HandoffDecisionV1,
    IncidentSeverity,
    ListADRsQueryV1,
    ListPostMortemsQueryV1,
    ListRisksQueryV1,
    ListTechDebtQueryV1,
    ListTechRadarQueryV1,
    ObligationApplicabilityV1,
    PostMortemEventV1,
    PostMortemRecordV1,
    PostMortemStatus,
    ProjectCompletionContractV1,
    ProjectCompletionObligationsV1,
    ProjectKindAuthorityV1,
    ProjectKindV1,
    QualityGateResultV1,
    QueryBlueprintProvenanceV1,
    QueryProjectCompletionContractV1,
    RegisterADRCommandV1,
    RegisterPostMortemCommandV1,
    RegisterRiskCommandV1,
    RegisterTechDebtCommandV1,
    RegisterTechRadarCommandV1,
    ReleaseDecision,
    ReleaseReadinessV1,
    RiskEventV1,
    RiskRecordV1,
    RiskSeverity,
    RiskStatus,
    RollbackLinkV1,
    RollbackStrategy,
    StackPolicyViolationV1,
    TaskBlueprintGeneratedEventV1,
    TaskBlueprintProvenanceSnapshotV1,
    TaskBlueprintResultV1,
    TechDebtEventV1,
    TechDebtRecordV1,
    TechDebtSeverity,
    TechDebtStatus,
    TechRadarEntryV1,
    TechRadarEventV1,
    TechRadarRing,
    UpdateADRStatusCommandV1,
    UpdatePostMortemStatusCommandV1,
    UpdateRiskStatusCommandV1,
    UpdateTechDebtStatusCommandV1,
    UpdateTechRadarRingCommandV1,
    VerificationCommandAuthorityV1,
    VerificationModalityV1,
    VerificationObligationV1,
    chief_engineer_semantic_repair_task_set_hash,
    project_completion_catalog_snapshot_hash,
    project_completion_verifier_policy_snapshot_hash,
)

# Service functions and re-exported agent/consumer classes.
from .service import (
    CEConsumer,
    ChiefEngineerAgent,
    assert_handoff_ready,
    assess_release_readiness,
    attach_governance_to_blueprint,
    bind_chief_engineer_semantic_repair_provider_patch,
    build_blueprint_governance,
    build_ce_handoff_decision,
    build_chief_engineer_blueprint_portfolio,
    build_chief_engineer_semantic_repair_patch_schema,
    check_stack_policy,
    chief_engineer_source_suffixes_for_language,
    classify_chief_engineer_pm_entrypoint_kind,
    compose_chief_engineer_semantic_repair,
    derive_project_kind_authority_from_catalog_snapshot,
    evaluate_ce_handoff_decision_for_blueprint,
    evaluate_handoff_decision,
    evaluate_handoff_decision_for_blueprint,
    generate_task_blueprint,
    get_blueprint_governance,
    get_blueprint_status,
    list_adrs,
    list_post_mortems,
    list_risks,
    list_tech_debt,
    list_tech_radar,
    load_chief_engineer_semantic_repair_candidate,
    normalize_chief_engineer_portfolio_tool_arguments,
    persist_chief_engineer_review_document,
    persist_chief_engineer_semantic_repair_candidate,
    project_chief_engineer_completion_contract_semantic_errors,
    project_chief_engineer_delivery_depth_feasibility_from_pm_tasks,
    project_chief_engineer_portfolio_delivery_depth_feasibility,
    project_chief_engineer_semantic_repair_provider_context,
    project_chief_engineer_task_blueprint,
    query_blueprint_provenance,
    query_project_completion_contract,
    register_adr,
    register_post_mortem,
    register_risk,
    register_tech_debt,
    register_tech_radar,
    run_pre_dispatch_chief_engineer,
    summarize_adrs,
    summarize_post_mortems,
    summarize_risks,
    summarize_tech_debt,
    summarize_tech_radar,
    update_adr_status,
    update_post_mortem_status,
    update_risk_status,
    update_tech_debt_status,
    update_tech_radar_ring,
    validate_director_handoff_from_payload,
)


def build_project_completion_contract(
    *,
    project_id: str,
    run_id: str,
    project_kind: ProjectKindV1,
    project_kind_authority: ProjectKindAuthorityV1,
    pm_contract_hash: str,
    covered_task_ids: tuple[str, ...],
    obligations: ProjectCompletionObligationsV1,
    completion_predicate_version: str,
    verifier_policy_hash: str,
    verifier_policy_snapshot_hash: str,
    verification_command_authority: tuple[VerificationCommandAuthorityV1, ...],
) -> ProjectCompletionContractV1:
    """Build a completion contract after the public types are initialized."""

    from polaris.cells.chief_engineer.blueprint.internal.project_completion_contract import (
        build_project_completion_contract as _build_project_completion_contract,
    )

    return _build_project_completion_contract(
        project_id=project_id,
        run_id=run_id,
        project_kind=project_kind,
        project_kind_authority=project_kind_authority,
        pm_contract_hash=pm_contract_hash,
        covered_task_ids=covered_task_ids,
        obligations=obligations,
        completion_predicate_version=completion_predicate_version,
        verifier_policy_hash=verifier_policy_hash,
        verifier_policy_snapshot_hash=verifier_policy_snapshot_hash,
        verification_command_authority=verification_command_authority,
    )


__all__ = [
    "ADREventV1",
    "ADRRecordV1",
    "ADRStatus",
    "ArchitectureDecisionV1",
    "ArtifactObligationV1",
    "ArtifactSemanticRoleV1",
    "BlueprintPersistence",
    "BuildChiefEngineerBlueprintPortfolioCommandV1",
    "CEConsumer",
    "ChiefEngineerAgent",
    "ChiefEngineerBehaviorExampleV1",
    "ChiefEngineerBehaviorInvariantV1",
    "ChiefEngineerBlueprintError",
    "ChiefEngineerBlueprintErrorV1",
    "ChiefEngineerBlueprintPortfolioV1",
    "ChiefEngineerPortfolioStructuralRecoveryV1",
    "ChiefEngineerPortfolioTaskV1",
    "ChiefEngineerProjectInterfaceContractV1",
    "ChiefEngineerSemanticRepairCandidateV1",
    "ChiefEngineerSemanticRepairDiagnosisV1",
    "ChiefEngineerSemanticRepairOperationV1",
    "ChiefEngineerSemanticRepairPatchV1",
    "ChiefEngineerSemanticRepairReceiptV1",
    "ChiefEngineerSharedBehaviorContractV1",
    "EntrypointKindV1",
    "EntrypointObligationV1",
    "GenerateTaskBlueprintCommandV1",
    "GetBlueprintStatusQueryV1",
    "GovernanceSummaryV1",
    "HandoffDecisionV1",
    "IncidentSeverity",
    "ListADRsQueryV1",
    "ListPostMortemsQueryV1",
    "ListRisksQueryV1",
    "ListTechDebtQueryV1",
    "ListTechRadarQueryV1",
    "ObligationApplicabilityV1",
    "PostMortemEventV1",
    "PostMortemRecordV1",
    "PostMortemStatus",
    "ProjectCompletionContractV1",
    "ProjectCompletionObligationsV1",
    "ProjectKindAuthorityV1",
    "ProjectKindV1",
    "QualityGateResultV1",
    "QueryBlueprintProvenanceV1",
    "QueryProjectCompletionContractV1",
    "RegisterADRCommandV1",
    "RegisterPostMortemCommandV1",
    "RegisterRiskCommandV1",
    "RegisterTechDebtCommandV1",
    "RegisterTechRadarCommandV1",
    "ReleaseDecision",
    "ReleaseReadinessV1",
    "RiskEventV1",
    "RiskRecordV1",
    "RiskSeverity",
    "RiskStatus",
    "RollbackLinkV1",
    "RollbackStrategy",
    "StackPolicyViolationV1",
    "TaskBlueprintGeneratedEventV1",
    "TaskBlueprintProvenanceSnapshotV1",
    "TaskBlueprintResultV1",
    "TechDebtEventV1",
    "TechDebtRecordV1",
    "TechDebtSeverity",
    "TechDebtStatus",
    "TechRadarEntryV1",
    "TechRadarEventV1",
    "TechRadarRing",
    "UpdateADRStatusCommandV1",
    "UpdatePostMortemStatusCommandV1",
    "UpdateRiskStatusCommandV1",
    "UpdateTechDebtStatusCommandV1",
    "UpdateTechRadarRingCommandV1",
    "VerificationCommandAuthorityV1",
    "VerificationModalityV1",
    "VerificationObligationV1",
    "assert_handoff_ready",
    "assess_release_readiness",
    "attach_governance_to_blueprint",
    "bind_chief_engineer_semantic_repair_provider_patch",
    "build_blueprint_governance",
    "build_ce_handoff_decision",
    "build_chief_engineer_blueprint_portfolio",
    "build_chief_engineer_semantic_repair_patch_schema",
    "build_project_completion_contract",
    "check_stack_policy",
    "chief_engineer_semantic_repair_task_set_hash",
    "chief_engineer_source_suffixes_for_language",
    "classify_chief_engineer_pm_entrypoint_kind",
    "compose_chief_engineer_semantic_repair",
    "derive_project_kind_authority_from_catalog_snapshot",
    "evaluate_ce_handoff_decision_for_blueprint",
    "evaluate_handoff_decision",
    "evaluate_handoff_decision_for_blueprint",
    "generate_task_blueprint",
    "get_blueprint_governance",
    "get_blueprint_status",
    "list_adrs",
    "list_post_mortems",
    "list_risks",
    "list_tech_debt",
    "list_tech_radar",
    "load_chief_engineer_semantic_repair_candidate",
    "normalize_chief_engineer_portfolio_tool_arguments",
    "persist_chief_engineer_review_document",
    "persist_chief_engineer_semantic_repair_candidate",
    "project_chief_engineer_completion_contract_semantic_errors",
    "project_chief_engineer_delivery_depth_feasibility_from_pm_tasks",
    "project_chief_engineer_portfolio_delivery_depth_feasibility",
    "project_chief_engineer_semantic_repair_provider_context",
    "project_chief_engineer_task_blueprint",
    "project_completion_catalog_snapshot_hash",
    "project_completion_verifier_policy_snapshot_hash",
    "query_blueprint_provenance",
    "query_project_completion_contract",
    "register_adr",
    "register_post_mortem",
    "register_risk",
    "register_tech_debt",
    "register_tech_radar",
    "run_pre_dispatch_chief_engineer",
    "summarize_adrs",
    "summarize_post_mortems",
    "summarize_risks",
    "summarize_tech_debt",
    "summarize_tech_radar",
    "update_adr_status",
    "update_post_mortem_status",
    "update_risk_status",
    "update_tech_debt_status",
    "update_tech_radar_ring",
    "validate_director_handoff_from_payload",
]
