"""Public boundary for `chief_engineer.blueprint` cell."""

from polaris.cells.chief_engineer.blueprint.internal.blueprint_persistence import (
    BlueprintPersistence,
)

# Contract types (dataclasses, enums, errors) are owned by contracts.py.
# Import them from there directly so the public boundary does not depend
# on service.py re-exporting them (which a linter may strip as "unused").
from .contracts import (
    ADREventV1,
    ADRRecordV1,
    ADRStatus,
    ChiefEngineerBlueprintError,
    ChiefEngineerBlueprintErrorV1,
    GenerateTaskBlueprintCommandV1,
    GetBlueprintStatusQueryV1,
    GovernanceSummaryV1,
    HandoffDecisionV1,
    ListADRsQueryV1,
    ListRisksQueryV1,
    ListTechDebtQueryV1,
    QualityGateResultV1,
    RegisterADRCommandV1,
    RegisterRiskCommandV1,
    RegisterTechDebtCommandV1,
    RiskEventV1,
    RiskRecordV1,
    RiskSeverity,
    RiskStatus,
    RollbackLinkV1,
    RollbackStrategy,
    TaskBlueprintGeneratedEventV1,
    TaskBlueprintResultV1,
    TechDebtEventV1,
    TechDebtRecordV1,
    TechDebtSeverity,
    TechDebtStatus,
    UpdateADRStatusCommandV1,
    UpdateRiskStatusCommandV1,
    UpdateTechDebtStatusCommandV1,
)

# Service functions and re-exported agent/consumer classes.
from .service import (
    CEConsumer,
    ChiefEngineerAgent,
    assert_handoff_ready,
    attach_governance_to_blueprint,
    build_blueprint_governance,
    evaluate_handoff_decision,
    evaluate_handoff_decision_for_blueprint,
    generate_task_blueprint,
    get_blueprint_governance,
    get_blueprint_status,
    list_adrs,
    list_risks,
    list_tech_debt,
    register_adr,
    register_risk,
    register_tech_debt,
    run_pre_dispatch_chief_engineer,
    summarize_adrs,
    summarize_risks,
    summarize_tech_debt,
    update_adr_status,
    update_risk_status,
    update_tech_debt_status,
)

__all__ = [
    "ADREventV1",
    "ADRRecordV1",
    "ADRStatus",
    "BlueprintPersistence",
    "CEConsumer",
    "ChiefEngineerAgent",
    "ChiefEngineerBlueprintError",
    "ChiefEngineerBlueprintErrorV1",
    "GenerateTaskBlueprintCommandV1",
    "GetBlueprintStatusQueryV1",
    "GovernanceSummaryV1",
    "HandoffDecisionV1",
    "ListADRsQueryV1",
    "ListRisksQueryV1",
    "ListTechDebtQueryV1",
    "QualityGateResultV1",
    "RegisterADRCommandV1",
    "RegisterRiskCommandV1",
    "RegisterTechDebtCommandV1",
    "RiskEventV1",
    "RiskRecordV1",
    "RiskSeverity",
    "RiskStatus",
    "RollbackLinkV1",
    "RollbackStrategy",
    "TaskBlueprintGeneratedEventV1",
    "TaskBlueprintResultV1",
    "TechDebtEventV1",
    "TechDebtRecordV1",
    "TechDebtSeverity",
    "TechDebtStatus",
    "UpdateADRStatusCommandV1",
    "UpdateRiskStatusCommandV1",
    "UpdateTechDebtStatusCommandV1",
    "assert_handoff_ready",
    "attach_governance_to_blueprint",
    "build_blueprint_governance",
    "evaluate_handoff_decision",
    "evaluate_handoff_decision_for_blueprint",
    "generate_task_blueprint",
    "get_blueprint_governance",
    "get_blueprint_status",
    "list_adrs",
    "list_risks",
    "list_tech_debt",
    "register_adr",
    "register_risk",
    "register_tech_debt",
    "run_pre_dispatch_chief_engineer",
    "summarize_adrs",
    "summarize_risks",
    "summarize_tech_debt",
    "update_adr_status",
    "update_risk_status",
    "update_tech_debt_status",
]
