"""KernelOne event subsystem exports."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "EVENT_TYPE_COMPLETE",
    "EVENT_TYPE_CONTENT_CHUNK",
    "EVENT_TYPE_ERROR",
    "EVENT_TYPE_FINGERPRINT",
    "EVENT_TYPE_LLM_CALL_END",
    "EVENT_TYPE_LLM_CALL_START",
    "EVENT_TYPE_LLM_COMPLETED",
    "EVENT_TYPE_LLM_END",
    "EVENT_TYPE_LLM_ERROR",
    "EVENT_TYPE_LLM_FAILED",
    "EVENT_TYPE_LLM_RETRY",
    "EVENT_TYPE_LLM_START",
    "EVENT_TYPE_LLM_WAITING",
    "EVENT_TYPE_SESSION_END",
    "EVENT_TYPE_SESSION_START",
    "EVENT_TYPE_STATE_SNAPSHOT",
    "EVENT_TYPE_TASK_COMPLETED",
    "EVENT_TYPE_TASK_CREATED",
    "EVENT_TYPE_TASK_FAILED",
    "EVENT_TYPE_TASK_UPDATED",
    "EVENT_TYPE_THINKING_CHUNK",
    "EVENT_TYPE_TOOL_CALL",
    "EVENT_TYPE_TOOL_END",
    "EVENT_TYPE_TOOL_ERROR",
    "EVENT_TYPE_TOOL_RESULT",
    "EVENT_TYPE_TOOL_START",
    "TOPIC_RUNTIME_AUDIT",
    "TOPIC_RUNTIME_FINGERPRINT",
    "TOPIC_RUNTIME_LLM",
    "TOPIC_RUNTIME_STREAM",
    "UEP_PERSISTENCE_TOPICS",
    "UEP_RUNTIME_TOPICS",
    "UEP_SECURE_TOPICS",
    "UEP_TOPIC_TO_CATEGORY",
    "Actor",
    "ContextEvent",
    "EmitResult",
    "EventEnvelope",
    "EventQueryResult",
    "EventSourcingError",
    "EventType",
    "EventWriter",
    "JsonlEventStore",
    "LLMRealtimeEvent",
    "LLMRealtimeEventBridge",
    "LegacySyncHandlerAdapter",
    "Message",
    "MessageBus",
    "MessageType",
    "emit_dialogue",
    "emit_event",
    "emit_fact_event",
    "emit_llm_event",
    "emit_session_event",
    "get_event_seq",
    "get_event_writer",
    "get_global_bus",
    "get_llm_realtime_bridge",
    "publish_llm_realtime_event",
    "query_stream_events",
    "set_dialogue_seq",
    "set_event_seq",
    "set_global_bus",
    "set_llm_realtime_bridge",
    "utc_iso_now",
]

_ATTR_TO_MODULE = {
    "EVENT_TYPE_COMPLETE": "polaris.kernelone.events.constants",
    "EVENT_TYPE_CONTENT_CHUNK": "polaris.kernelone.events.constants",
    "EVENT_TYPE_ERROR": "polaris.kernelone.events.constants",
    "EVENT_TYPE_FINGERPRINT": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_CALL_END": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_CALL_START": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_COMPLETED": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_END": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_ERROR": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_FAILED": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_RETRY": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_START": "polaris.kernelone.events.constants",
    "EVENT_TYPE_LLM_WAITING": "polaris.kernelone.events.constants",
    "EVENT_TYPE_SESSION_END": "polaris.kernelone.events.constants",
    "EVENT_TYPE_SESSION_START": "polaris.kernelone.events.constants",
    "EVENT_TYPE_STATE_SNAPSHOT": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TASK_COMPLETED": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TASK_CREATED": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TASK_FAILED": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TASK_UPDATED": "polaris.kernelone.events.constants",
    "EVENT_TYPE_THINKING_CHUNK": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TOOL_CALL": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TOOL_END": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TOOL_ERROR": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TOOL_RESULT": "polaris.kernelone.events.constants",
    "EVENT_TYPE_TOOL_START": "polaris.kernelone.events.constants",
    "ContextEvent": "polaris.kernelone.events.context_events",
    "EventType": "polaris.kernelone.events.context_events",
    "EventWriter": "polaris.kernelone.events.context_events",
    "get_event_writer": "polaris.kernelone.events.context_events",
    "EmitResult": "polaris.kernelone.events.emit_result",
    "emit_fact_event": "polaris.kernelone.events.fact_events",
    "emit_dialogue": "polaris.kernelone.events.io_events",
    "emit_event": "polaris.kernelone.events.io_events",
    "emit_llm_event": "polaris.kernelone.events.io_events",
    "get_event_seq": "polaris.kernelone.events.io_events",
    "set_dialogue_seq": "polaris.kernelone.events.io_events",
    "set_event_seq": "polaris.kernelone.events.io_events",
    "utc_iso_now": "polaris.kernelone.events.io_events",
    "Actor": "polaris.kernelone.events.message_bus",
    "LegacySyncHandlerAdapter": "polaris.kernelone.events.message_bus",
    "Message": "polaris.kernelone.events.message_bus",
    "MessageBus": "polaris.kernelone.events.message_bus",
    "MessageType": "polaris.kernelone.events.message_bus",
    "LLMRealtimeEvent": "polaris.kernelone.events.realtime_bridge",
    "LLMRealtimeEventBridge": "polaris.kernelone.events.realtime_bridge",
    "get_llm_realtime_bridge": "polaris.kernelone.events.realtime_bridge",
    "publish_llm_realtime_event": "polaris.kernelone.events.realtime_bridge",
    "set_llm_realtime_bridge": "polaris.kernelone.events.realtime_bridge",
    "get_global_bus": "polaris.kernelone.events.registry",
    "set_global_bus": "polaris.kernelone.events.registry",
    "emit_session_event": "polaris.kernelone.events.session_events",
    "EventEnvelope": "polaris.kernelone.events.sourcing",
    "EventQueryResult": "polaris.kernelone.events.sourcing",
    "EventSourcingError": "polaris.kernelone.events.sourcing",
    "JsonlEventStore": "polaris.kernelone.events.sourcing",
    "query_stream_events": "polaris.kernelone.events.sourcing",
    "TOPIC_RUNTIME_AUDIT": "polaris.kernelone.events.topics",
    "TOPIC_RUNTIME_FINGERPRINT": "polaris.kernelone.events.topics",
    "TOPIC_RUNTIME_LLM": "polaris.kernelone.events.topics",
    "TOPIC_RUNTIME_STREAM": "polaris.kernelone.events.topics",
    "UEP_PERSISTENCE_TOPICS": "polaris.kernelone.events.topics",
    "UEP_RUNTIME_TOPICS": "polaris.kernelone.events.topics",
    "UEP_SECURE_TOPICS": "polaris.kernelone.events.topics",
    "UEP_TOPIC_TO_CATEGORY": "polaris.kernelone.events.topics",
}


def __getattr__(name: str) -> Any:
    module_path = _ATTR_TO_MODULE.get(name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_path)
    return getattr(module, name)
