"""Public boundary for `runtime.projection` cell.

Keep package import side effects light. Neighboring cells import small public
facades from this package during bootstrap, and eager service imports can create
cycles before their modules finish initializing.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

_CONTRACT_EXPORTS = {
    "ChainAxisV1",
    "DeliveryAxisV1",
    "DirectorStatusObservationPortV1",
    "DirectorStatusObservationV1",
    "DirectorStatusObservationV1Error",
    "FactoryChainOwnerObservationPortV1",
    "FactoryChainOwnerObservationV1",
    "ProjectOutcomeEvidenceRefsV1",
    "ProjectOutcomeFactoryOwnerBindingV1",
    "ProjectOutcomeFactoryOwnerQueryV1",
    "ProjectOutcomeNonFactoryClaimsV1",
    "ProjectOutcomeNonFactoryEvidenceRefsV1",
    "ProjectOutcomeOwnerObservationV1Error",
    "ProjectOutcomeQueryV1",
    "ProjectOutcomeV1",
    "ProjectOutcomeValidationV1Error",
    "QaAxisV1",
    "RecommendedDispositionV1",
    "RunLedgerAxisV1",
    "RuntimeObserverEventTypeV1",
    "RuntimeObserverEventV1",
    "RuntimeProjectedEventV1",
    "RuntimeProjectionError",
    "RuntimeProjectionQueryV1",
    "RuntimeProjectionResultV1",
    "TaskBoundaryAxisV1",
    "TaskRuntimeAxisV1",
}

_ROLE_CONTRACT_EXPORTS = {
    "ChiefEngineerBlueprintDetailV1",
    "ChiefEngineerBlueprintListV1",
    "ChiefEngineerBlueprintSummaryV1",
    "RoleTaskContractV1",
}

_SERVICE_EXPORTS = {
    "CodeChangeState",
    "CodeChangeStatus",
    "DiffHunk",
    "EventSeverity",
    "PMTaskNode",
    "PMTaskState",
    "QATaskNode",
    "QATaskState",
    "ReviewComment",
    "ReviewState",
    "ReviewVerdict",
    "RoleState",
    "RoleType",
    "RuntimeEventV2",
    "RuntimeProjection",
    "RuntimeProjectionService",
    "RuntimeRoleState",
    "RuntimeSnapshotV2",
    "RuntimeSummary",
    "RuntimeTaskNode",
    "RuntimeWorkerState",
    "TaskSource",
    "TaskState",
    "WorkerState",
    "WorkspaceRuntimeContext",
    "build_anthro_state",
    "build_cache_root",
    "build_director_runtime_status",
    "build_director_status",
    "build_engine_status",
    "build_llm_status",
    "build_pm_status",
    "build_pm_status_async",
    "build_resident_state",
    "build_runtime_projection",
    "build_runtime_projection_sync",
    "build_snapshot_payload_from_projection",
    "build_status_payload_sync",
    "build_workflow_status_payload",
    "canonicalize_workflow_task_state",
    "decode_bytes",
    "format_mtime",
    "get_runtime_event_v2_schema",
    "get_runtime_snapshot_v2_schema",
    "get_workflow_director_status_sync",
    "get_workflow_runtime_status",
    "get_workflow_stage",
    "invalidate_projection_cache",
    "list_memos",
    "load_runtime_task_rows",
    "merge_director_status",
    "query_project_outcome",
    "query_project_outcome_with_factory_owner",
    "read_file_head",
    "read_file_tail",
    "read_incremental",
    "read_json",
    "read_readme_title",
    "resolve_artifact_path",
    "resolve_workspace_runtime_context",
    "select_latest_artifact",
    "summarize_workflow_tasks",
    "write_text_atomic",
    "write_workflow_state",
}

if TYPE_CHECKING:
    from polaris.cells.runtime.projection.public.contracts import (
        ChainAxisV1,
        DeliveryAxisV1,
        DirectorStatusObservationPortV1,
        DirectorStatusObservationV1,
        DirectorStatusObservationV1Error,
        FactoryChainOwnerObservationPortV1,
        FactoryChainOwnerObservationV1,
        ProjectOutcomeEvidenceRefsV1,
        ProjectOutcomeFactoryOwnerBindingV1,
        ProjectOutcomeFactoryOwnerQueryV1,
        ProjectOutcomeNonFactoryClaimsV1,
        ProjectOutcomeNonFactoryEvidenceRefsV1,
        ProjectOutcomeOwnerObservationV1Error,
        ProjectOutcomeQueryV1,
        ProjectOutcomeV1,
        ProjectOutcomeValidationV1Error,
        QaAxisV1,
        RecommendedDispositionV1,
        RunLedgerAxisV1,
        RuntimeObserverEventTypeV1,
        RuntimeObserverEventV1,
        RuntimeProjectedEventV1,
        RuntimeProjectionError,
        RuntimeProjectionQueryV1,
        RuntimeProjectionResultV1,
        TaskBoundaryAxisV1,
        TaskRuntimeAxisV1,
    )
    from polaris.cells.runtime.projection.public.role_contracts import (
        ChiefEngineerBlueprintDetailV1,
        ChiefEngineerBlueprintListV1,
        ChiefEngineerBlueprintSummaryV1,
        RoleTaskContractV1,
    )
    from polaris.cells.runtime.projection.public.service import (
        CodeChangeState,
        CodeChangeStatus,
        DiffHunk,
        EventSeverity,
        PMTaskNode,
        PMTaskState,
        QATaskNode,
        QATaskState,
        ReviewComment,
        ReviewState,
        ReviewVerdict,
        RoleState,
        RoleType,
        RuntimeEventV2,
        RuntimeProjection,
        RuntimeProjectionService,
        RuntimeRoleState,
        RuntimeSnapshotV2,
        RuntimeSummary,
        RuntimeTaskNode,
        RuntimeWorkerState,
        TaskSource,
        TaskState,
        WorkerState,
        WorkspaceRuntimeContext,
        build_anthro_state,
        build_cache_root,
        build_director_runtime_status,
        build_director_status,
        build_engine_status,
        build_llm_status,
        build_pm_status,
        build_pm_status_async,
        build_resident_state,
        build_runtime_projection,
        build_runtime_projection_sync,
        build_snapshot_payload_from_projection,
        build_status_payload_sync,
        build_workflow_status_payload,
        canonicalize_workflow_task_state,
        decode_bytes,
        format_mtime,
        get_runtime_event_v2_schema,
        get_runtime_snapshot_v2_schema,
        get_workflow_director_status_sync,
        get_workflow_runtime_status,
        get_workflow_stage,
        invalidate_projection_cache,
        list_memos,
        load_runtime_task_rows,
        merge_director_status,
        query_project_outcome,
        query_project_outcome_with_factory_owner,
        read_file_head,
        read_file_tail,
        read_incremental,
        read_json,
        read_readme_title,
        resolve_artifact_path,
        resolve_workspace_runtime_context,
        select_latest_artifact,
        summarize_workflow_tasks,
        write_text_atomic,
        write_workflow_state,
    )

__all__ = [
    "ChainAxisV1",
    "ChiefEngineerBlueprintDetailV1",
    "ChiefEngineerBlueprintListV1",
    "ChiefEngineerBlueprintSummaryV1",
    "CodeChangeState",
    "CodeChangeStatus",
    "DeliveryAxisV1",
    "DiffHunk",
    "DirectorStatusObservationPortV1",
    "DirectorStatusObservationV1",
    "DirectorStatusObservationV1Error",
    "EventSeverity",
    "FactoryChainOwnerObservationPortV1",
    "FactoryChainOwnerObservationV1",
    "PMTaskNode",
    "PMTaskState",
    "ProjectOutcomeEvidenceRefsV1",
    "ProjectOutcomeFactoryOwnerBindingV1",
    "ProjectOutcomeFactoryOwnerQueryV1",
    "ProjectOutcomeNonFactoryClaimsV1",
    "ProjectOutcomeNonFactoryEvidenceRefsV1",
    "ProjectOutcomeOwnerObservationV1Error",
    "ProjectOutcomeQueryV1",
    "ProjectOutcomeV1",
    "ProjectOutcomeValidationV1Error",
    "QATaskNode",
    "QATaskState",
    "QaAxisV1",
    "RecommendedDispositionV1",
    "RoleTaskContractV1",
    "RunLedgerAxisV1",
    "RuntimeObserverEventTypeV1",
    "RuntimeObserverEventV1",
    "RuntimeProjectedEventV1",
    "RuntimeProjectionError",
    "RuntimeProjectionQueryV1",
    "RuntimeProjectionResultV1",
    "TaskBoundaryAxisV1",
    "TaskRuntimeAxisV1",
    "build_cache_root",
    "build_director_status",
    "build_llm_status",
    "build_pm_status",
    "build_pm_status_async",
    "build_resident_state",
    "build_runtime_projection",
    "build_status_payload_sync",
    "build_workflow_status_payload",
    "canonicalize_workflow_task_state",
    "get_workflow_runtime_status",
    "get_workflow_stage",
    "list_memos",
    "load_runtime_task_rows",
    "merge_director_status",
    "query_project_outcome",
    "query_project_outcome_with_factory_owner",
    "resolve_artifact_path",
    "select_latest_artifact",
    "summarize_workflow_tasks",
    "write_workflow_state",
]


def __getattr__(name: str) -> Any:
    if name in _CONTRACT_EXPORTS:
        from polaris.cells.runtime.projection.public import contracts

        value = getattr(contracts, name)
    elif name in _ROLE_CONTRACT_EXPORTS:
        from polaris.cells.runtime.projection.public import role_contracts

        value = getattr(role_contracts, name)
    elif name in _SERVICE_EXPORTS:
        from polaris.cells.runtime.projection.public import service

        value = getattr(service, name)
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    globals()[name] = value
    return value
