"""KernelOne context runtime exports."""

from __future__ import annotations

from .artifact_compression import (
    ArtifactCompressionRequest,
    ArtifactCompressionResult,
    compress_if_changed,
)
from .budget_gate import (
    DEFAULT_FALLBACK_WINDOW,
    DEFAULT_SAFETY_MARGIN,
    MIN_BUDGET_TOKENS,
    ContextBudget,
    ContextBudgetGate,
)
from .cache import (
    CacheEntry,
    CacheStats,
    CacheTier,
    KernelOneCacheManager,
    clear_cache_manager,
    get_cache_manager,
)
from .cache_manager import (
    AssetCachePort,
    CacheEntry as TieredCacheEntry,
    CacheStats as TieredCacheStats,
    CacheTier as TieredCacheTier,
    TieredAssetCacheManager,
)
from .cache_policies import (
    HotSliceCachePolicy,
    ProjectionCachePolicy,
    RepoMapCachePolicy,
    SymbolIndexCachePolicy,
    warming_hint_for_phase,
)
from .chunks import (
    AssemblyContext,
    AssemblyResult,
    CacheControl,
    ChunkBudget,
    ChunkBudgetTracker,
    ChunkMetadata,
    ChunkTokenStats,
    ChunkType,
    CompressionDecision,
    ContinuityDecision,
    FinalRequestReceipt,
    PromptChunk,
    PromptChunkAssembler,
    StrategyMetadata,
)
from .compaction import (
    CompactSnapshot,
    RoleContextCompressor,
    RoleContextIdentity,
    build_continuity_summary_text,
)
from .compaction_strategy import (
    CompactionStrategy,
)
from .context_os import (
    CodeContextDomainAdapter,
    ContextDomainAdapter,
    ContextOSProjection,
    ContextOSQualityCase,
    ContextOSQualityResult,
    ContextOSQualitySummary,
    ContextOSSnapshot,
    ContextSlicePlan,
    ContextSliceSelection,
    DomainRoutingDecision,
    DomainStatePatchHints,
    GenericContextDomainAdapter,
    RunCard,
    StateFirstContextOS,
    StateFirstContextOSPolicy,
    evaluate_context_os_case,
    evaluate_context_os_suite,
    get_context_domain_adapter,
    summarize_context_os_payload,
)
from .engine import ContextCache
from .engine.models import ContextItem, ContextPack, ContextRequest
from .exploration_policy import (
    AssetCandidate,
    AssetKind,
    DefaultExplorationPolicy,
    ExpansionDecision,
    ExplorationContext,
    ExplorationPhase,
    ExplorationPolicyConfig,
    ExplorationPolicyPort,
)
from .history_materialization import (
    HistoryMaterializationStrategy,
    SessionContinuityStrategy,
)
from .session_continuity import (
    SessionContinuityEngine,
    SessionContinuityPack,
    SessionContinuityPolicy,
    SessionContinuityProjection,
    SessionContinuityRequest,
    build_session_continuity_pack,
    history_pairs_to_messages,
    messages_to_history_pairs,
)
from .strategy_code_domain import (
    CacheStrategy,
    ExplorationStrategy,
    ProfileDrivenBudgetGate,
    ReadEscalationStrategy,
    StrategyDrivenExplorationPolicy,
)
from .strategy_contracts import (
    BudgetDecision,
    BudgetDecisionKind,
    CacheStrategyPort,
    CompactionDecision,
    CompactionResult,
    CompactionStrategyPort,
    EvaluationStrategyPort,
    ExpansionDecision as StrategyExpansionDecision,
    ExplorationStrategyPort,
    HistoryMaterialization,
    HistoryMaterializationStrategyPort,
    ProfileMetadata,
    ReadEscalation,
    ReadEscalationDecision,
    ReadEscalationDecisionResult,
    ReadEscalationStrategyPort,
    ResolvedStrategy,
    Scorecard,
    ScoreDiff,
    SessionContinuityStrategyPort,
    StrategyBundle,
    StrategyProfile,
    StrategyReceipt,
)
from .strategy_overlay_contracts import (
    ResolvedOverlayStrategy,
    RoleOverlay,
)
from .strategy_overlay_definitions import (
    BUILTIN_OVERLAYS,
    architect_analysis,
    director_coder,
    director_execution,
    director_writer,
    qa_review,
)
from .strategy_overlay_registry import (
    RoleOverlayRegistry,
    get_overlay_registry,
)
from .strategy_profiles import (
    BUILTIN_PROFILES,
    canonical_balanced,
    claude_like_dynamic,
    cost_guarded,
    deep_research,
    speed_first,
)
from .strategy_receipts import StrategyReceiptEmitter
from .strategy_registry import (
    CANONICAL_BUNDLE,
    StrategyRegistry,
    get_registry,
    reset_instance,
    resolve_bundle_hash,
    resolve_profile_hash,
)
from .strategy_run_context import StrategyRunContext
from .strategy_scoring import (
    CANONICAL_WEIGHTING,
    COST_GUARDED_WEIGHTING,
    LOW_LATENCY_WEIGHTING,
    compute_overall,
    score_diff,
)
from .working_set import (
    CodeSlice,
    RepoMapSnapshot,
    SymbolCandidate,
    WorkingSet,
    WorkingSetAssembler,
)

__all__ = [
    "BUILTIN_OVERLAYS",
    # Strategy profiles
    "BUILTIN_PROFILES",
    # Strategy registry
    "CANONICAL_BUNDLE",
    # Strategy scoring
    "CANONICAL_WEIGHTING",
    "COST_GUARDED_WEIGHTING",
    "DEFAULT_FALLBACK_WINDOW",
    "DEFAULT_SAFETY_MARGIN",
    "LOW_LATENCY_WEIGHTING",
    "MIN_BUDGET_TOKENS",
    # Prompt chunks
    "AssemblyContext",
    "AssemblyResult",
    "AssetCachePort",
    # Exploration policy
    "AssetCandidate",
    "AssetKind",
    # Strategy contracts
    "BudgetDecision",
    "BudgetDecisionKind",
    "CacheControl",
    # Cache (legacy 3-tier)
    "CacheEntry",
    "CacheStats",
    # Strategy code domain
    "CacheStrategy",
    "CacheStrategyPort",
    "CacheTier",
    "ChunkBudget",
    "ChunkBudgetTracker",
    "ChunkMetadata",
    "ChunkTokenStats",
    "ChunkType",
    # Context OS
    "CodeContextDomainAdapter",
    # Working set
    "CodeSlice",
    "CompactSnapshot",
    "CompactionDecision",
    "CompactionResult",
    "CompactionStrategy",
    "CompactionStrategyPort",
    "CompressionDecision",
    # Budget gate
    "ContextBudget",
    "ContextBudgetGate",
    # Engine
    "ContextCache",
    "ContextDomainAdapter",
    "ContextItem",
    "ContextOSProjection",
    "ContextOSQualityCase",
    "ContextOSQualityResult",
    "ContextOSQualitySummary",
    "ContextOSSnapshot",
    "ContextPack",
    "ContextRequest",
    "ContextSlicePlan",
    "ContextSliceSelection",
    "ContinuityDecision",
    "DefaultExplorationPolicy",
    "DomainRoutingDecision",
    "DomainStatePatchHints",
    "EvaluationStrategyPort",
    "ExpansionDecision",
    "ExplorationContext",
    "ExplorationPhase",
    "ExplorationPolicyConfig",
    "ExplorationPolicyPort",
    "ExplorationStrategy",
    "ExplorationStrategyPort",
    # Repo Intelligence
    "FileTag",
    "FinalRequestReceipt",
    "GenericContextDomainAdapter",
    "HistoryMaterialization",
    "HistoryMaterializationStrategy",
    "HistoryMaterializationStrategyPort",
    # Cache policies
    "HotSliceCachePolicy",
    "KernelOneCacheManager",
    "LoIRenderer",
    "ProfileDrivenBudgetGate",
    "ProfileMetadata",
    "ProjectionCachePolicy",
    "PromptChunk",
    "PromptChunkAssembler",
    "RankedCandidate",
    "ReadEscalation",
    "ReadEscalationDecision",
    "ReadEscalationDecisionResult",
    "ReadEscalationStrategy",
    "ReadEscalationStrategyPort",
    "RepoIntelligenceFacade",
    "RepoIntelligenceRanker",
    "RepoMapCachePolicy",
    "RepoMapSnapshot",
    # Role overlays
    "ResolvedOverlayStrategy",
    "ResolvedStrategy",
    "RoleContextCompressor",
    "RoleContextIdentity",
    "RoleOverlay",
    "RoleOverlayRegistry",
    "RunCard",
    "ScoreDiff",
    "Scorecard",
    "SessionContinuityEngine",
    "SessionContinuityPack",
    "SessionContinuityPolicy",
    "SessionContinuityProjection",
    "SessionContinuityRequest",
    "SessionContinuityStrategyPort",
    "StateFirstContextOS",
    "StateFirstContextOSPolicy",
    "StrategyBundle",
    "StrategyDrivenExplorationPolicy",
    "StrategyExpansionDecision",
    "StrategyMetadata",
    "StrategyProfile",
    "StrategyReceipt",
    # Strategy receipts
    "StrategyReceiptEmitter",
    "StrategyRegistry",
    # Strategy run context
    "StrategyRunContext",
    "SymbolCandidate",
    "SymbolIndexCachePolicy",
    "TagKind",
    "TagsCache",
    "TagsCacheStats",
    "TagsExtractor",
    "TieredAssetCacheManager",
    # Cache (5-tier blueprint §5.7)
    "TieredCacheEntry",
    "TieredCacheStats",
    "TieredCacheTier",
    "WorkingSet",
    "WorkingSetAssembler",
    "architect_analysis",
    # Compaction / continuity
    "build_continuity_summary_text",
    "build_session_continuity_pack",
    "canonical_balanced",
    "claude_like_dynamic",
    "clear_cache_manager",
    "compress_if_changed",
    "compute_overall",
    "cost_guarded",
    "deep_research",
    "director_coder",
    "director_execution",
    "director_writer",
    "evaluate_context_os_case",
    "evaluate_context_os_suite",
    "get_cache_manager",
    "get_context_domain_adapter",
    "get_overlay_registry",
    "get_registry",
    "get_repo_intelligence",
    "get_tags_cache",
    "get_tags_for_file",
    "history_pairs_to_messages",
    "messages_to_history_pairs",
    "qa_review",
    "reset_instance",
    "resolve_bundle_hash",
    "resolve_profile_hash",
    "score_diff",
    "speed_first",
    "summarize_context_os_payload",
    "warming_hint_for_phase",
]
