import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * DirectorDebugPanel - 调试面板展示组件
 */
import { Bug, CheckCircle2 } from 'lucide-react';
import { Button } from '@/app/components/ui/button';
export function DirectorDebugPanel({ tasks, cancellingTaskId, onInspectTask, onCancelTask, }) {
    return (_jsxs("div", { className: "h-full flex flex-col", children: [_jsx("div", { className: "h-12 flex items-center px-4 border-b border-white/5", children: _jsx("h2", { className: "text-sm font-medium text-slate-200", children: "\u8C03\u8BD5\u4E2D\u5FC3" }) }), _jsx("div", { className: "flex-1 overflow-auto p-4", children: tasks.length === 0 ? (_jsxs("div", { className: "h-full flex flex-col items-center justify-center text-slate-500", children: [_jsx(CheckCircle2, { className: "w-12 h-12 mb-4 text-blue-500/30" }), _jsx("p", { children: "\u6CA1\u6709\u9700\u8981\u8C03\u8BD5\u7684\u95EE\u9898" })] })) : (_jsx("div", { className: "space-y-2", children: tasks.map((task) => (_jsxs("div", { className: "p-4 rounded-xl border border-red-500/20 bg-red-500/5", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Bug, { className: "w-4 h-4 text-red-400" }), _jsx("span", { className: "text-sm text-slate-200 font-medium", children: task.name })] }), task.error && (_jsx("pre", { className: "text-xs text-red-400 font-mono bg-red-950/30 p-2 rounded", children: task.error })), _jsxs("div", { className: "mt-3 flex gap-2", children: [_jsx(Button, { size: "sm", variant: "outline", onClick: () => onInspectTask?.(task.id), disabled: !onInspectTask, "data-testid": `director-debug-inspect-${task.id}`, className: "border-red-500/30 text-red-400", children: "\u5B9A\u4F4D" }), _jsx(Button, { size: "sm", variant: "ghost", onClick: () => onCancelTask?.(task.id), disabled: !onCancelTask || cancellingTaskId === task.id, "data-testid": `director-debug-cancel-${task.id}`, className: "text-slate-400", children: cancellingTaskId === task.id ? '取消中' : '取消' })] })] }, task.id))) })) })] }));
}
