"""Public read services for the `director.runtime` cell.

This package is the lossless successor of the former ``service`` module.
It re-exports every previously-public symbol from the same import path so
that ``import ...public.service`` and ``from ...public.service import X``
keep resolving identically for all external importers.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable, Sequence
from typing import Any, Mapping, cast

from polaris.cells.director.runtime.internal.repair_kernel.advisory_policy import (
    ALLOWED_REPAIR_ADVISORY_SUGGESTED_RULE_FIELDS,
    FORBIDDEN_REPAIR_ADVISORY_METADATA_FIELDS,
    FORBIDDEN_REPAIR_ADVISORY_SUGGESTED_RULE_FIELDS,
)
from polaris.cells.director.runtime.internal.repair_kernel.contracts import (
    FILE_ABSENT_HASH,
    CompositionResult,
    RepairAdvisorNote,
    RepairDiagnostic,
    RepairPlan,
    RepairReceipt,
    RepairRevalidationEvidence,
    sha256_text,
)
from polaris.cells.director.runtime.internal.repair_kernel.diagnostics import normalize_artifact_quality_errors
from polaris.cells.director.runtime.internal.repair_kernel.environment import (
    environment_prep_catalog_summary,
    environment_prep_plans_from_requirements,
    environment_refresh_requirements_from_receipts,
)
from polaris.cells.director.runtime.internal.repair_kernel.executor import (
    _can_apply_with_editor,
    _text_replace_operations_for_patch,
)
from polaris.cells.director.runtime.internal.repair_kernel.receipt_projection import (
    build_repair_kernel_result_summary as _build_repair_kernel_result_summary,
    summarize_repair_revalidation_coverage,
)
from polaris.cells.director.runtime.internal.repair_kernel.receipts import attach_revalidation_evidence
from polaris.cells.director.runtime.internal.repair_kernel.registry import (
    build_repair_coverage_report,
    default_repair_rule_registry,
    repair_language_slots,
)
from polaris.cells.director.runtime.internal.repair_kernel.runtime_dispatch import (
    RuntimeRepairPlanning,
    plan_runtime_repair,
    run_runtime_repair,
    run_runtime_repair_convergence,
    runtime_repair_binding_has_typed_planner,
    runtime_repair_bindings,
    runtime_repair_source_tools,
)
from polaris.cells.director.runtime.internal.repair_kernel.schedule_catalog import (
    DEFAULT_REPAIR_SCHEDULE_MAX_ROUNDS,
    MaterializationQualityRepairScheduleStep,
    PostExecutionRepairScheduleStep,
    materialization_quality_repair_schedule,
    post_execution_repair_schedule,
    run_materialization_quality_repair_schedule_callbacks,
    run_post_execution_repair_schedule_callbacks,
)
from polaris.cells.director.runtime.internal.repair_kernel.scheduler import RepairVerifierSnapshot
from polaris.cells.director.runtime.internal.repair_kernel.shadow import compare_baseline_and_kernel_repairs
from polaris.cells.director.runtime.internal.repair_kernel.strategy_catalog import (
    deterministic_repair_strategy_catalog as _deterministic_repair_strategy_catalog,
)
from polaris.cells.director.runtime.public.contracts import (
    AttachDirectorRepairRevalidationEvidenceV1,
    CompareDirectorRepairShadowRunV1,
    DirectorInterfaceDiscrepancyReceiptV1,
    DirectorRepairAdvisoryPolicyResultV1,
    DirectorRepairAdvisoryValidationResultV1,
    DirectorRepairCallbackReceiptProjectionV1,
    DirectorRepairCompositionIssueV1,
    DirectorRepairCompositionSummaryV1,
    DirectorRepairConvergenceResultV1,
    DirectorRepairConvergenceRoundResultV1,
    DirectorRepairConvergenceVerifierRequestV1,
    DirectorRepairCoverageReportV1,
    DirectorRepairCutoverReadinessResultV1,
    DirectorRepairDiagnosticCoverageV1,
    DirectorRepairEffectPlanV1,
    DirectorRepairEffectToolNameV1,
    DirectorRepairEffectV1,
    DirectorRepairEnvironmentPrepCatalogResultV1,
    DirectorRepairEnvironmentPrepPlanV1,
    DirectorRepairEnvironmentRefreshRequirementsResultV1,
    DirectorRepairEnvironmentRefreshRequirementV1,
    DirectorRepairKernelSummaryProjectionResultV1,
    DirectorRepairLanguageSlotsResultV1,
    DirectorRepairLanguageSlotV1,
    DirectorRepairMaterializationAllowedPathsResultV1,
    DirectorRepairMaterializationBridgeMetadataResultV1,
    DirectorRepairMaterializationPlanProbeResultV1,
    DirectorRepairMaterializationQualityFacadeResultV1,
    DirectorRepairMaterializationQualityScheduleResultV1,
    DirectorRepairMaterializationQualityScheduleRunResultV1,
    DirectorRepairMaterializationQualityStepV1,
    DirectorRepairMetricsResultV1,
    DirectorRepairPatchSummaryV1,
    DirectorRepairPlanningResultV1,
    DirectorRepairPlanProbeItemV1,
    DirectorRepairPlanProbeResultV1,
    DirectorRepairPlanSummaryV1,
    DirectorRepairPostExecutionScheduleResultV1,
    DirectorRepairPostExecutionScheduleRunResultV1,
    DirectorRepairPostExecutionStepV1,
    DirectorRepairResultV1,
    DirectorRepairRevalidationInputV1,
    DirectorRepairRevalidationProjectionResultV1,
    DirectorRepairRevalidationRequestV1,
    DirectorRepairShadowComparisonResultV1,
    DirectorRepairStrategyCatalogResultV1,
    DirectorRepairVerifierSnapshotInputV1,
    DirectorTaskBoundaryQualityResultV1,
    EvaluateDirectorRepairCutoverReadinessV1,
    PlanDirectorRepairCommandV1,
    ProjectDirectorRepairKernelSummaryV1,
    ProjectDirectorRepairMaterializationBridgeMetadataV1,
    ProjectDirectorRepairMetricsV1,
    QueryDirectorRepairAdvisoryPolicyV1,
    QueryDirectorRepairAdvisoryValidationV1,
    QueryDirectorRepairCoverageV1,
    QueryDirectorRepairEnvironmentPrepCatalogV1,
    QueryDirectorRepairEnvironmentRefreshRequirementsV1,
    QueryDirectorRepairLanguageSlotsV1,
    QueryDirectorRepairMaterializationAllowedPathsV1,
    QueryDirectorRepairMaterializationPlanProbeV1,
    QueryDirectorRepairMaterializationQualityScheduleV1,
    QueryDirectorRepairPlanProbeV1,
    QueryDirectorRepairPostExecutionScheduleV1,
    QueryDirectorRepairStrategyCatalogV1,
    RepairAdvisoryV1,
    RepairDiagnosticV1,
    RepairReceiptV1,
    RunDirectorRepairCommandV1,
    RunDirectorRepairConvergenceCommandV1,
    RunDirectorTaskBoundaryQualityLoopCommandV1,
)
from polaris.cells.director.runtime.public.directed_effect_contracts import DirectedEffectImmutableItemsV1
from polaris.kernelone.tools.tool_kinds import WRITE_TOOLS

from ._core import (
    _ALLOWED_CONVERGENCE_VERIFIER_EVIDENCE_SOURCES,
    _DELETE_FILE_REQUIRES_POLICY_GATED_DELETER,
    DeleteFileFn,
    DirectorRepairConvergenceVerifierFn,
    DirectorRepairRevalidatorFn,
    EditFileFn,
    MaterializationQualityStepRunnerV1,
    PostExecutionStepRunnerV1,
    WriteFileFn,
    _count_by_key,
    _ordered_unique,
    _PublicConvergenceVerifierError,
    _receipt_authority_payload,
    _receipt_context_with_revalidation,
    _refresh_receipt_hashes,
    _repair_advisory_validation_summary,
    _repair_execution_error_code,
    _stable_json,
    project_director_repair_metrics,
    query_director_repair_advisory_policy,
    query_director_repair_environment_prep_catalog,
    query_director_repair_strategy_catalog,
    validate_director_repair_advisory,
)
from ._execution import (
    _apply_materialization_runtime_step_metadata,
    _coverage_item_is_covered_unplannable,
    _coverage_items_for_source_tool,
    _first_mapping_value,
    _materialization_aggregate_evidence_status,
    _materialization_candidate_source_tools_from_coverage,
    _materialization_claimed_evidence_status,
    _materialization_evidence_mapping_status,
    _materialization_evidence_residual_count,
    _materialization_facade_has_successful_write_tool,
    _materialization_optional_int,
    _materialization_payload_evidence_status,
    _materialization_payload_revalidation_evidence,
    _materialization_payload_step_id,
    _materialization_plan_probe_source_tools,
    _materialization_quality_schedule_reconciliation,
    _materialization_result_payload,
    _materialization_tool_result_evidence_status,
    _plan_probe_candidate_source_tools,
    _plan_probe_item_status,
    _plan_probe_result_status,
    _project_director_repair_diagnostic_coverage,
    _project_materialization_facade_tool_results_with_runtime_metadata,
    _public_materialization_quality_step,
    _public_post_execution_step,
    _repair_diagnostic_from_coverage_item,
    _repair_receipt_authority_policy,
    build_director_repair_kernel_summary,
    plan_director_repair,
    project_director_repair_kernel_summary,
    project_director_repair_materialization_bridge_metadata,
    query_director_repair_coverage,
    query_director_repair_language_slots,
    query_director_repair_materialization_allowed_paths,
    query_director_repair_materialization_plan_probe,
    query_director_repair_materialization_quality_schedule,
    query_director_repair_plan_probe,
    query_director_repair_post_execution_schedule,
    run_director_materialization_quality_repair_facade,
    run_director_materialization_quality_repair_schedule,
    run_director_materialization_quality_repair_schedule_result,
    run_director_post_execution_repair_schedule,
    run_director_post_execution_repair_schedule_result,
    run_director_repair,
    run_director_repair_convergence,
    run_director_task_boundary_quality_loop,
)
from ._projections import (
    _DIAGNOSTIC_SYMBOL_PATTERNS,
    _artifact_quality_errors_from_command,
    _attach_failed_native_revalidation,
    _attach_native_revalidation_evidence,
    _baseline_shadow_hashes,
    _diagnostic_codes,
    _diagnostic_ids_for_signatures,
    _diagnostic_paths,
    _diagnostic_symbols,
    _environment_prep_receipts_from_public_repair_receipts,
    _failed_public_convergence_result,
    _interface_contract_symbol_maps,
    _interface_delta_from_task_boundary,
    _interface_discrepancy_receipts_from_plan_probe,
    _interface_discrepancy_triage_summary,
    _interface_string_list,
    _kernel_receipt_hashes,
    _mapping_list,
    _merge_repair_diagnostic_evidence,
    _optional_int,
    _public_convergence_metadata,
    _public_receipt_to_internal,
    _public_repair_diagnostics_from_command,
    _public_revalidation_diagnostics_to_internal,
    _public_revalidation_evidence_to_internal,
    _repair_diagnostic_raw_key,
    _repair_diagnostic_signature,
    _repair_diagnostic_signature_index,
    _repair_diagnostic_structural_key,
    _repair_diagnostics_from_artifact_quality_issues,
    _repair_diagnostics_from_quality_inputs,
    _repair_effect_call_id,
    _repair_effect_operation_id,
    _repair_revalidation_evidence_status,
    _repair_revalidation_payload_failed,
    _runtime_artifact_quality_errors_from_command,
    _shadow_comparison_is_successful,
    _shadow_comparison_scope_signature,
    _shadow_cutover_readiness,
    _string_list,
    _task_boundary_quality_metadata,
    _to_internal_advisor_notes,
    _to_internal_repair_diagnostic,
    _to_public_convergence_result,
    _to_public_convergence_round,
    _to_public_environment_prep_plan,
    _to_public_environment_refresh_requirement,
    _to_public_repair_composition_summary,
    _to_public_repair_diagnostic,
    _to_public_repair_effect_plan,
    _to_public_repair_plan_summary,
    _to_public_repair_planning_result,
    _to_public_repair_receipt,
    _validate_public_convergence_verifier_evidence,
    attach_director_repair_revalidation_evidence,
    compare_director_repair_shadow_run,
    evaluate_director_repair_cutover_readiness,
    normalize_director_repair_diagnostics,
    normalize_director_repair_issue_diagnostics,
    project_director_repair_revalidation_evidence,
    query_director_repair_environment_refresh_requirements,
)

__all__ = [
    "AttachDirectorRepairRevalidationEvidenceV1",
    "DirectorRepairConvergenceResultV1",
    "DirectorRepairConvergenceRoundResultV1",
    "DirectorRepairConvergenceVerifierFn",
    "DirectorRepairConvergenceVerifierRequestV1",
    "DirectorRepairCutoverReadinessResultV1",
    "DirectorRepairEnvironmentPrepCatalogResultV1",
    "DirectorRepairEnvironmentPrepPlanV1",
    "DirectorRepairEnvironmentRefreshRequirementV1",
    "DirectorRepairEnvironmentRefreshRequirementsResultV1",
    "DirectorRepairKernelSummaryProjectionResultV1",
    "DirectorRepairMaterializationQualityScheduleResultV1",
    "DirectorRepairMaterializationQualityStepV1",
    "DirectorRepairMetricsResultV1",
    "DirectorRepairPlanProbeItemV1",
    "DirectorRepairPlanProbeResultV1",
    "DirectorRepairPostExecutionScheduleResultV1",
    "DirectorRepairPostExecutionStepV1",
    "DirectorRepairRevalidationInputV1",
    "DirectorRepairRevalidationProjectionResultV1",
    "DirectorRepairRevalidationRequestV1",
    "DirectorRepairRevalidatorFn",
    "DirectorRepairVerifierSnapshotInputV1",
    "DirectorTaskBoundaryQualityResultV1",
    "EvaluateDirectorRepairCutoverReadinessV1",
    "ProjectDirectorRepairKernelSummaryV1",
    "ProjectDirectorRepairMetricsV1",
    "QueryDirectorRepairEnvironmentPrepCatalogV1",
    "QueryDirectorRepairEnvironmentRefreshRequirementsV1",
    "QueryDirectorRepairPlanProbeV1",
    "RunDirectorRepairConvergenceCommandV1",
    "RunDirectorTaskBoundaryQualityLoopCommandV1",
    "attach_director_repair_revalidation_evidence",
    "build_director_repair_kernel_summary",
    "compare_director_repair_shadow_run",
    "evaluate_director_repair_cutover_readiness",
    "plan_director_repair",
    "project_director_repair_kernel_summary",
    "project_director_repair_metrics",
    "project_director_repair_revalidation_evidence",
    "query_director_repair_advisory_policy",
    "query_director_repair_coverage",
    "query_director_repair_environment_prep_catalog",
    "query_director_repair_environment_refresh_requirements",
    "query_director_repair_language_slots",
    "query_director_repair_materialization_quality_schedule",
    "query_director_repair_plan_probe",
    "query_director_repair_post_execution_schedule",
    "query_director_repair_strategy_catalog",
    "run_director_materialization_quality_repair_schedule",
    "run_director_post_execution_repair_schedule",
    "run_director_repair",
    "run_director_repair_convergence",
    "run_director_task_boundary_quality_loop",
    "validate_director_repair_advisory",
]
