"""Public contracts for `chief_engineer.blueprint` cell.

The contracts in this package define the stable boundary for Chief Engineer
blueprint commands, results, portfolio authority, project-completion
obligations, and governance DTOs.

This package is the lossless successor of the former ``contracts`` module.
It re-exports every previously-public symbol from the same import path so
that ``import ...public.contracts`` and ``from ...public.contracts import X``
keep resolving identically for all external importers.
"""

from __future__ import annotations

# Backward-compatible re-export of standard-library / typing names that were
# module-level attributes of the former ``contracts`` module.
import hashlib
import hmac
import json
import secrets
import shlex
import unicodedata
from collections.abc import Mapping
from copy import deepcopy
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any, Literal

from polaris.cells.chief_engineer.blueprint.public.contracts._blueprint_dtos import (
    ArchitectureDecisionV1,
    BuildChiefEngineerBlueprintPortfolioCommandV1,
    ChiefEngineerBlueprintError,
    ChiefEngineerBlueprintErrorV1,
    ChiefEngineerBlueprintPortfolioV1,
    ChiefEngineerPortfolioTaskV1,
    ChiefEngineerProjectInterfaceContractV1,
    GenerateTaskBlueprintCommandV1,
    GetBlueprintStatusQueryV1,
    QueryBlueprintProvenanceV1,
    QueryProjectCompletionContractV1,
    TaskBlueprintGeneratedEventV1,
    TaskBlueprintProvenanceSnapshotV1,
    TaskBlueprintResultV1,
    _ChiefEngineerPortfolioAuthorityCarrierV1,
    _issue_chief_engineer_portfolio_authority_carrier,
    _portfolio_authority_carrier_signature,
    _portfolio_authority_receipt_hash,
    _verify_chief_engineer_portfolio_authority_carrier,
)
from polaris.cells.chief_engineer.blueprint.public.contracts._completion import (
    ArtifactObligationV1,
    ArtifactSemanticRoleV1,
    EntrypointKindV1,
    EntrypointObligationV1,
    ObligationApplicabilityV1,
    ProjectCompletionContractV1,
    ProjectCompletionObligationsV1,
    ProjectKindAuthorityV1,
    ProjectKindV1,
    VerificationCommandAuthorityV1,
    VerificationModalityV1,
    VerificationObligationV1,
    _canonical_project_completion_contract_seed,
    _canonicalize_completion_id_tuple,
    _project_completion_contract_hash,
    _project_completion_contract_id,
)
from polaris.cells.chief_engineer.blueprint.public.contracts._enums import (
    ADRStatus,
    IncidentSeverity,
    PostMortemStatus,
    ReleaseDecision,
    RiskSeverity,
    RiskStatus,
    RollbackStrategy,
    TechDebtSeverity,
    TechDebtStatus,
    TechRadarRing,
)
from polaris.cells.chief_engineer.blueprint.public.contracts._governance import (
    ADREventV1,
    ADRRecordV1,
    CeHandoffDecisionBindingsV1,
    CeHandoffDecisionV1,
    GovernanceSummaryV1,
    HandoffDecisionV1,
    ListADRsQueryV1,
    ListPostMortemsQueryV1,
    ListRisksQueryV1,
    ListTechDebtQueryV1,
    ListTechRadarQueryV1,
    PostMortemEventV1,
    PostMortemRecordV1,
    QualityGateResultV1,
    RegisterADRCommandV1,
    RegisterPostMortemCommandV1,
    RegisterRiskCommandV1,
    RegisterTechDebtCommandV1,
    RegisterTechRadarCommandV1,
    ReleaseReadinessV1,
    RiskEventV1,
    RiskRecordV1,
    RollbackLinkV1,
    StackPolicyViolationV1,
    TechDebtEventV1,
    TechDebtRecordV1,
    TechRadarEntryV1,
    TechRadarEventV1,
    UpdateADRStatusCommandV1,
    UpdatePostMortemStatusCommandV1,
    UpdateRiskStatusCommandV1,
    UpdateTechDebtStatusCommandV1,
    UpdateTechRadarRingCommandV1,
)
from polaris.cells.chief_engineer.blueprint.public.contracts._helpers import (
    _PROJECT_COMPLETION_CONTRACT_ID_PREFIX,
    _PROJECT_COMPLETION_CONTRACT_SCHEMA_V1,
    _PROJECT_COMPLETION_MAX_ARTIFACTS,
    _PROJECT_COMPLETION_MAX_COMMAND_BYTES,
    _PROJECT_COMPLETION_MAX_ENTRYPOINTS,
    _PROJECT_COMPLETION_MAX_TASK_IDS,
    _PROJECT_COMPLETION_MAX_TOKEN_BYTES,
    _PROJECT_COMPLETION_MAX_VERIFICATIONS,
    _PROJECT_COMPLETION_MAX_VERIFIER_REFS,
    _PROVENANCE_BLUEPRINT_SCHEMA,
    _PROVENANCE_HASH_SCHEME,
    _PROVENANCE_MAX_IDENTITY_BYTES,
    _PROVENANCE_MAX_PATH_BYTES,
    _PROVENANCE_MAX_TARGET_FILES,
    _PROVENANCE_SNAPSHOT_SCHEMA,
    _json_safe_mapping,
    _normalize_relative_portfolio_path,
    _optional_completion_command,
    _project_kind_authority_hash,
    _relative_path_tuple,
    _require_completion_token,
    _require_exact_non_empty,
    _require_non_empty,
    _require_provenance_blueprint_id,
    _require_provenance_identity,
    _require_provenance_path,
    _require_provenance_sha256,
    _require_provenance_text,
    _require_safe_filename_token,
    _require_verification_command_proof,
    _require_verifier_argv,
    _require_verifier_cwd,
    _strict_provenance_target_paths,
    _strict_unique_string_tuple,
    _string_tuple,
    _to_dict_copy,
    _verification_command_authority_hash,
    project_completion_catalog_snapshot_hash,
    project_completion_verifier_policy_snapshot_hash,
)

__all__ = [
    "ADREventV1",
    "ADRRecordV1",
    "ADRStatus",
    "ArchitectureDecisionV1",
    "ArtifactObligationV1",
    "ArtifactSemanticRoleV1",
    "BuildChiefEngineerBlueprintPortfolioCommandV1",
    "CeHandoffDecisionBindingsV1",
    "CeHandoffDecisionV1",
    "ChiefEngineerBlueprintError",
    "ChiefEngineerBlueprintErrorV1",
    "ChiefEngineerBlueprintPortfolioV1",
    "ChiefEngineerPortfolioTaskV1",
    "ChiefEngineerProjectInterfaceContractV1",
    "EntrypointKindV1",
    "EntrypointObligationV1",
    "GenerateTaskBlueprintCommandV1",
    "GetBlueprintStatusQueryV1",
    "GovernanceSummaryV1",
    "HandoffDecisionV1",
    "IncidentSeverity",
    "ListADRsQueryV1",
    "ListPostMortemsQueryV1",
    "ListRisksQueryV1",
    "ListTechDebtQueryV1",
    "ListTechRadarQueryV1",
    "ObligationApplicabilityV1",
    "PostMortemEventV1",
    "PostMortemRecordV1",
    "PostMortemStatus",
    "ProjectCompletionContractV1",
    "ProjectCompletionObligationsV1",
    "ProjectKindAuthorityV1",
    "ProjectKindV1",
    "QualityGateResultV1",
    "QueryBlueprintProvenanceV1",
    "QueryProjectCompletionContractV1",
    "RegisterADRCommandV1",
    "RegisterPostMortemCommandV1",
    "RegisterRiskCommandV1",
    "RegisterTechDebtCommandV1",
    "RegisterTechRadarCommandV1",
    "ReleaseDecision",
    "ReleaseReadinessV1",
    "RiskEventV1",
    "RiskRecordV1",
    "RiskSeverity",
    "RiskStatus",
    "RollbackLinkV1",
    "RollbackStrategy",
    "StackPolicyViolationV1",
    "TaskBlueprintGeneratedEventV1",
    "TaskBlueprintProvenanceSnapshotV1",
    "TaskBlueprintResultV1",
    "TechDebtEventV1",
    "TechDebtRecordV1",
    "TechDebtSeverity",
    "TechDebtStatus",
    "TechRadarEntryV1",
    "TechRadarEventV1",
    "TechRadarRing",
    "UpdateADRStatusCommandV1",
    "UpdatePostMortemStatusCommandV1",
    "UpdateRiskStatusCommandV1",
    "UpdateTechDebtStatusCommandV1",
    "UpdateTechRadarRingCommandV1",
    "VerificationCommandAuthorityV1",
    "VerificationModalityV1",
    "VerificationObligationV1",
    "project_completion_verifier_policy_snapshot_hash",
]
