export const UI_TERMS = {
  roles: {
    pm: 'PM',
    director: 'Director',
    chief_engineer: 'Chief Engineer',
    qa: 'QA',
    architect: 'Architect',
    cfo: 'CFO',
    hr: 'HR',
  },
  nouns: {
    workspace: 'Workspace',
    logs: 'Logs',
    history: 'History',
    docsWizard: 'Docs Wizard',
    runtimeArtifacts: 'Runtime Artifacts',
  },
  states: {
    running: 'Running',
    idle: 'Idle',
    active: 'Active',
    ready: 'Ready',
    offline: 'Offline',
    pinging: 'Pinging',
    success: 'Success',
    failed: 'Failed',
    blocked: 'Blocked',
    unknown: 'Unknown',
  },
  actions: {
    startLoop: 'Start',
    stopLoop: 'Stop',
    runOnce: 'Run Once',
    resumeLast: 'Resume Last',
    openLogs: 'Open Logs',
    openSettings: 'Settings',
  },
} as const;
