"""Public boundary for `policy.workspace_guard` cell."""

from polaris.cells.policy.workspace_guard.public.service import (
    SELF_UPGRADE_MODE_ENV,
    WorkspaceArchiveWriteGuardQueryV1,
    WorkspaceGuardBatchDecisionV1,
    WorkspaceGuardDecisionV1,
    WorkspaceGuardError,
    WorkspaceGuardPathDecisionV1,
    WorkspaceGuardViolationEventV1,
    WorkspaceWriteGuardBatchQueryV1,
    WorkspaceWriteGuardQueryV1,
    build_workspace_guard_message,
    check_workspace_write_guard,
    check_workspace_write_guard_batch,
    ensure_workspace_target_allowed,
    get_meta_project_root,
    is_meta_project_target,
    resolve_workspace_target,
    self_upgrade_mode_enabled,
)

__all__ = [
    "SELF_UPGRADE_MODE_ENV",
    "WorkspaceArchiveWriteGuardQueryV1",
    "WorkspaceGuardBatchDecisionV1",
    "WorkspaceGuardDecisionV1",
    "WorkspaceGuardError",
    "WorkspaceGuardPathDecisionV1",
    "WorkspaceGuardViolationEventV1",
    "WorkspaceWriteGuardBatchQueryV1",
    "WorkspaceWriteGuardQueryV1",
    "build_workspace_guard_message",
    "check_workspace_write_guard",
    "check_workspace_write_guard_batch",
    "ensure_workspace_target_allowed",
    "get_meta_project_root",
    "is_meta_project_target",
    "resolve_workspace_target",
    "self_upgrade_mode_enabled",
]
