"""Public boundary for `roles.runtime` cell.

Keep package import lightweight by lazily loading contract/service exports.
"""

from __future__ import annotations

from importlib import import_module

__all__ = [
    "AgentMessage",
    "AgentState",
    "AgentStatus",
    "AggregateChatChoiceV1",
    "AggregateChatCompletionsCommandV1",
    "AggregateChatCompletionsResultV1",
    "AggregateChatMessageV1",
    "AggregateCognitiveLedgerEntryV1",
    "AggregateRoleLobeV1",
    "AggregateRolePlanResultV1",
    "AggregateRuntimeAuditResultV1",
    "AggregateRuntimeEntrypointCheckV1",
    "AggregateRuntimeIntegrationV1",
    "AggregateTakeoverDirectiveV1",
    "AuditAggregateRuntimeIntegrationsQueryV1",
    "BaseEngine",
    "BuildAggregateRolePlanQueryV1",
    "ContextRequest",
    "ContextResult",
    "ContinuationPolicy",
    "EngineBudget",
    "EngineContext",
    "EngineRegistry",
    "EngineResult",
    "EngineStatus",
    "EngineStrategy",
    "ExecuteRoleCapabilityInvocationCommandV1",
    "ExecuteRoleSessionCommandV1",
    "ExecuteRoleTaskCommandV1",
    "FailureClass",
    "GetRoleRuntimeStatusQueryV1",
    "HybridEngine",
    "IRoleRuntime",
    "KernelOneMessageBusPort",
    "MessageType",
    "OrchestratorSessionState",
    "PathSecurityError",
    "PlanSolveEngine",
    "PromptFingerprint",
    "ProtocolBus",
    "ProtocolFSM",
    "ReActEngine",
    "RetryHint",
    "RoleAgent",
    "RoleAssetMount",
    "RoleAssetMountTable",
    "RoleAssetRef",
    "RoleCapabilityDecision",
    "RoleCapabilityDescriptor",
    "RoleCapabilityFingerprint",
    "RoleCapabilityInvocation",
    "RoleCapabilityInvocationResultV1",
    "RoleCapabilityPorts",
    "RoleContextGateway",
    "RoleContextPolicy",
    "RoleDataPolicy",
    "RoleDataStore",
    "RoleDataStoreError",
    "RoleExecutionKernel",
    "RoleExecutionMode",
    "RoleExecutionResultV1",
    "RoleIdentity",
    "RoleLedgerBinding",
    "RoleLibraryPolicy",
    "RoleProfile",
    "RoleProfileBinding",
    "RoleProfileRegistry",
    "RolePromptPolicy",
    "RoleRuntimeError",
    "RoleRuntimeObject",
    "RoleRuntimeObjectSpec",
    "RoleRuntimeService",
    "RoleSessionOrchestrator",
    "RoleSkillManager",
    "RoleStateCommitReceipt",
    "RoleStateCommitRequest",
    "RoleTaskCompletedEventV1",
    "RoleTaskMarketBinding",
    "RoleTaskStartedEventV1",
    "RoleToolGateway",
    "RoleToolPolicy",
    "RoleTurnContext",
    "RoleTurnEnvelope",
    "RoleTurnRequest",
    "RoleTurnResult",
    "SeqEventType",
    "SeqProgressDetector",
    "SeqState",
    "SequentialBudget",
    "SequentialConfig",
    "SequentialEngine",
    "SequentialMode",
    "SequentialStateProxy",
    "SequentialStats",
    "SequentialStatsResult",
    "SequentialTraceLevel",
    "SkillLoader",
    "StepDecision",
    "StepResult",
    "StepStatus",
    "TaskClassifier",
    "TerminationReason",
    "ToTEngine",
    "ToolAuthorizationError",
    "Worker",
    "WorkerConfig",
    "WorkerPool",
    "WorkerResult",
    "WorkerState",
    "WorkerTask",
    "aggregate_chat_completions",
    "audit_aggregate_runtime_integrations",
    "classify_task",
    "commit_role_state",
    "create_engine_budget",
    "create_protocol_bus",
    "create_protocol_fsm",
    "create_role_skill_manager",
    "create_sequential_budget",
    "create_skill_loader",
    "create_worker_pool",
    "emit_seq_event",
    "execute_role_capability_invocation",
    "execute_role_session_command",
    "execute_role_task_command",
    "get_builtin_role_runtime_spec",
    "get_engine",
    "get_engine_registry",
    "get_hybrid_engine",
    "get_seq_emitter",
    "get_task_classifier",
    "load_core_roles",
    "profile_from_dict",
    "profile_to_dict",
    "query_aggregate_role_plan",
    "query_role_runtime_status",
    "register_engine",
    "registry",
    "should_enable_sequential",
    "stream_role_session_command",
]

_CONTRACTS_MODULE = "polaris.cells.roles.runtime.public.contracts"
_SERVICE_MODULE = "polaris.cells.roles.runtime.public.service"
_INTERNAL_CONTINUATION_MODULE = "polaris.cells.roles.runtime.internal.continuation_policy"
_CONTRACT_EXPORTS = frozenset(
    {
        "ExecuteRoleSessionCommandV1",
        "ExecuteRoleTaskCommandV1",
        "GetRoleRuntimeStatusQueryV1",
        "AggregateChatChoiceV1",
        "AggregateChatCompletionsCommandV1",
        "AggregateChatCompletionsResultV1",
        "AggregateChatMessageV1",
        "AggregateCognitiveLedgerEntryV1",
        "AggregateRuntimeEntrypointCheckV1",
        "AggregateRuntimeAuditResultV1",
        "AggregateRuntimeIntegrationV1",
        "AggregateRoleLobeV1",
        "AggregateRolePlanResultV1",
        "AggregateTakeoverDirectiveV1",
        "AuditAggregateRuntimeIntegrationsQueryV1",
        "BuildAggregateRolePlanQueryV1",
        "ExecuteRoleCapabilityInvocationCommandV1",
        "IRoleRuntime",
        "RoleAssetMount",
        "RoleAssetMountTable",
        "RoleAssetRef",
        "RoleCapabilityDecision",
        "RoleCapabilityDescriptor",
        "RoleCapabilityFingerprint",
        "RoleCapabilityInvocation",
        "RoleCapabilityInvocationResultV1",
        "RoleCapabilityPorts",
        "RoleExecutionResultV1",
        "RoleIdentity",
        "RoleLedgerBinding",
        "RoleProfileBinding",
        "RoleRuntimeError",
        "RoleRuntimeObject",
        "RoleRuntimeObjectSpec",
        "RoleStateCommitReceipt",
        "RoleStateCommitRequest",
        "RoleTaskMarketBinding",
        "RoleTaskCompletedEventV1",
        "RoleTaskStartedEventV1",
        "RoleTurnContext",
        "RoleTurnEnvelope",
        "get_builtin_role_runtime_spec",
    }
)
_CONTINUATION_EXPORTS = frozenset({"ContinuationPolicy", "OrchestratorSessionState"})


def __getattr__(name: str) -> object:
    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    if name in _CONTINUATION_EXPORTS:
        module_name = _INTERNAL_CONTINUATION_MODULE
    elif name in _CONTRACT_EXPORTS:
        module_name = _CONTRACTS_MODULE
    else:
        module_name = _SERVICE_MODULE
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
