import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, } from '@/app/components/ui/alert-dialog';
import { workspaceFileLabel } from '@/app/utils/workspaceDisplay';
export function AgentsReviewDialog({ open, onOpenChange, agentsDraftFailed, agentsReview, onOpenLogs, onOpenDraft, workspace, agentsDraftMtime, agentsFeedbackSavedAt, agentsLoading, agentsDraftContent, agentsFeedback, onAgentsFeedbackChange, onRetryGenerate, onSubmitFeedback, onApplyDraft, agentsApplying, }) {
    const targetPath = workspace ? `${workspace}\\AGENTS.md` : 'workspace\\AGENTS.md';
    const targetLabel = workspaceFileLabel(workspace);
    return (_jsx(AlertDialog, { open: open, onOpenChange: onOpenChange, children: _jsxs(AlertDialogContent, { "data-testid": "agents-review-dialog", className: "grid max-h-[92vh] min-w-0 max-w-3xl grid-rows-[auto_auto_minmax(0,1fr)_auto] overflow-hidden border border-emerald-500/30 bg-[#1f2125]", children: [_jsxs(AlertDialogHeader, { className: "shrink-0", children: [_jsx(AlertDialogTitle, { className: "text-emerald-200", children: agentsDraftFailed ? 'AGENTS.md 草案生成失败' : 'AGENTS.md 草案待审' }), _jsx(AlertDialogDescription, { className: "whitespace-pre-wrap text-gray-300", children: agentsDraftFailed
                                ? '未能生成可用草案。请先查看日志，补充修订意见后再重试。'
                                : '请审阅生成的 AGENTS.md 草案；确认后可回写到工作区，供 PM/Director 后续轮次遵循。' })] }), _jsxs("div", { className: "min-w-0 shrink-0 rounded-md border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-xs text-emerald-100", children: [_jsxs("div", { className: "flex min-w-0 flex-col gap-2 sm:flex-row sm:items-center sm:justify-between", children: [_jsxs("span", { className: "min-w-0 break-all", children: ["\u8349\u6848\u8DEF\u5F84: ", agentsReview?.draft_path || 'runtime/contracts/agents.generated.md'] }), _jsxs("div", { className: "flex shrink-0 flex-wrap items-center gap-2", children: [_jsx("button", { type: "button", onClick: onOpenLogs, className: "rounded bg-emerald-500/20 px-2 py-1 text-[11px] text-emerald-100 hover:bg-emerald-500/30", children: "\u67E5\u770B\u65E5\u5FD7" }), _jsx("button", { type: "button", onClick: onOpenDraft, className: "rounded bg-emerald-500/20 px-2 py-1 text-[11px] text-emerald-100 hover:bg-emerald-500/30", children: "\u6253\u5F00\u8349\u6848" })] })] }), _jsxs("div", { className: "truncate", title: targetPath, children: ["\u76EE\u6807\u4F4D\u7F6E: ", _jsx("span", { "data-testid": "agents-review-target-label", children: targetLabel })] }), agentsDraftMtime ? _jsxs("div", { children: ["\u751F\u6210\u65F6\u95F4: ", agentsDraftMtime] }) : null, agentsFeedbackSavedAt ? _jsxs("div", { children: ["\u53CD\u9988\u4FDD\u5B58\u65F6\u95F4: ", agentsFeedbackSavedAt] }) : null] }), _jsxs("div", { "data-testid": "agents-review-scroll-region", className: "grid min-h-0 gap-3 overflow-y-auto pr-1", children: [_jsxs("div", { className: "min-h-0 rounded-md border border-gray-700 bg-[#181a1f]", children: [_jsxs("div", { className: "flex min-w-0 items-center justify-between gap-2 border-b border-gray-800 px-3 py-2 text-xs text-gray-400", children: [_jsx("span", { className: "min-w-0 truncate", children: "AGENTS.generated.md" }), agentsLoading ? _jsx("span", { children: "\u52A0\u8F7D\u4E2D..." }) : null] }), _jsx("pre", { className: "max-h-[38vh] min-h-48 overflow-auto whitespace-pre-wrap break-words p-3 text-xs text-gray-200", children: agentsDraftContent || '(空)' })] }), _jsxs("div", { className: "rounded-md border border-gray-700 bg-[#181a1f] p-3", children: [_jsx("div", { className: "text-xs text-gray-400", children: "\u4FEE\u8BA2\u610F\u89C1\uFF08\u5C06\u53CD\u9988\u7ED9 PM\uFF09" }), _jsx("textarea", { className: "mt-2 h-28 w-full resize-none rounded border border-gray-700 bg-[#0f1115] p-2 text-xs text-gray-200 outline-none focus:border-emerald-400", placeholder: "\u8BF7\u8BF4\u660E\u9700\u8981\u4FEE\u6539\u7684\u89C4\u5219\u3001\u672F\u8BED\u6216\u683C\u5F0F\u8981\u6C42\uFF08UTF-8\uFF09...", value: agentsFeedback, onChange: (event) => {
                                        onAgentsFeedbackChange(event.target.value);
                                    } }), _jsx("div", { className: "mt-2 text-[11px] text-gray-500", children: "\u63D0\u4EA4\u53CD\u9988\u4E0D\u4F1A\u81EA\u52A8\u56DE\u5199\uFF1B\u9700\u786E\u8BA4\u8349\u6848\u540E\u518D\u6267\u884C\u5E94\u7528\u3002" })] })] }), _jsxs(AlertDialogFooter, { "data-testid": "agents-review-footer", className: "shrink-0 flex-wrap", children: [_jsx(AlertDialogCancel, { className: "whitespace-nowrap", onClick: () => onOpenChange(false), children: "\u53D6\u6D88" }), agentsDraftFailed ? (_jsx(AlertDialogAction, { onClick: (event) => {
                                event.preventDefault();
                                onRetryGenerate();
                            }, className: "whitespace-nowrap bg-blue-500 text-white hover:bg-blue-400", children: "\u91CD\u65B0\u751F\u6210" })) : null, _jsx(AlertDialogAction, { onClick: (event) => {
                                event.preventDefault();
                                onSubmitFeedback();
                            }, className: "whitespace-nowrap bg-blue-500 text-white hover:bg-blue-400", children: "\u63D0\u4EA4\u53CD\u9988\uFF08\u6682\u4E0D\u56DE\u5199\uFF09" }), _jsx(AlertDialogAction, { onClick: onApplyDraft, disabled: agentsApplying || agentsDraftFailed, className: "whitespace-nowrap bg-emerald-500 text-white hover:bg-emerald-400", children: agentsApplying ? '回写中...' : '回写到 AGENTS.md' })] })] }) }));
}
