import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FileText, Clock } from 'lucide-react';
export function SnapshotPanel({ timestamp, fileStatus, filePaths, directorState }) {
    const fileLines = Array.isArray(fileStatus) ? fileStatus.slice(0, 4) : [];
    const filePathsCount = Array.isArray(filePaths) ? filePaths.length : 0;
    const directorPhase = directorState && typeof directorState['phase'] === 'string' ? String(directorState['phase']) : '';
    const directorIter = directorState && typeof directorState['iteration'] === 'number' ? Number(directorState['iteration']) : null;
    const directorStatus = directorState && typeof directorState['status'] === 'string' ? String(directorState['status']) : '';
    return (_jsxs("div", { "data-testid": "snapshot-panel", className: "z-10 min-w-0 overflow-hidden border-b border-border bg-bg-panel/90 px-4 py-2 text-xs text-text-dim backdrop-blur-sm", children: [_jsx("div", { className: "flex min-w-0 items-center justify-between gap-4", children: _jsxs("div", { className: "flex min-w-0 flex-wrap items-center gap-2 font-mono text-[10px] text-text-dim", children: [_jsxs("div", { className: "flex shrink-0 items-center gap-1.5 rounded border border-border bg-bg-tertiary px-2 py-1", children: [_jsx(FileText, { className: "size-3 shrink-0 text-text-muted" }), _jsxs("span", { children: ["\u5377\u5B97: ", _jsx("span", { className: "text-text-main", children: filePathsCount })] })] }), _jsxs("div", { className: "flex min-w-0 items-center gap-1.5 rounded border border-border bg-bg-tertiary px-2 py-1", children: [_jsx(Clock, { className: "size-3 shrink-0 text-text-muted" }), _jsxs("span", { className: "min-w-0 break-all", children: ["\u65F6\u523B: ", _jsx("span", { className: "text-text-main", children: timestamp || '—' })] })] }), directorPhase || directorStatus || directorIter !== null ? (_jsxs("div", { className: "flex min-w-0 items-center gap-1.5 rounded border border-border bg-bg-tertiary px-2 py-1 animate-pulse-slow", children: [_jsx("span", { className: "shrink-0 font-bold text-status-secondary", children: "Chief Engineer" }), _jsx("span", { className: "mx-1 h-3 w-px shrink-0 bg-border" }), _jsx("span", { className: "min-w-0 break-all text-text-main", children: directorPhase || directorStatus || '' }), directorIter !== null ? _jsxs("span", { className: "text-accent", children: [" #", directorIter] }) : ''] })) : null] }) }), fileLines.length > 0 ? (_jsx("div", { className: "-mx-4 mt-2 flex min-w-0 flex-wrap gap-x-4 gap-y-1 border-t border-border bg-bg-tertiary/20 px-4 pb-1 pt-2 font-mono text-[10px] text-text-dim", children: fileLines.map((line) => (_jsxs("span", { "data-testid": "snapshot-panel-file-line", className: "flex max-w-full min-w-0 items-center gap-1 break-all md:max-w-[28rem]", children: [_jsx("span", { className: "h-1 w-1 shrink-0 rounded-full bg-text-muted" }), line] }, line))) })) : null] }));
}
