import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { getValidationSeverity } from '../utils/validation';
import { AlertTriangle, XCircle, Info } from 'lucide-react';
export function ValidationPanel({ issues, onIssueClick, onClose }) {
    if (issues.length === 0)
        return null;
    const errors = issues.filter(i => getValidationSeverity(i) === 'error');
    const warnings = issues.filter(i => getValidationSeverity(i) === 'warning');
    return (_jsxs("div", { className: "absolute top-4 right-4 z-50 w-80 soft-panel rounded-lg", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-white/10 px-3 py-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(AlertTriangle, { className: "size-4 text-rose-400" }), _jsxs("span", { className: "text-sm font-medium text-rose-200", children: ["\u914D\u7F6E\u95EE\u9898 (", issues.length, ")"] })] }), onClose && (_jsx("button", { onClick: onClose, className: "rounded p-1 text-text-dim hover:bg-white/10 hover:text-text-main", children: _jsx(XCircle, { className: "size-4" }) }))] }), _jsxs("div", { className: "max-h-60 overflow-y-auto p-2", children: [errors.length > 0 && (_jsxs("div", { className: "mb-2", children: [_jsxs("div", { className: "mb-1 text-[10px] font-medium uppercase tracking-wide text-rose-400", children: ["\u9519\u8BEF (", errors.length, ")"] }), _jsx("ul", { className: "space-y-1", children: errors.map((issue, idx) => (_jsx("li", { className: "cursor-pointer rounded border border-rose-500/20 bg-rose-500/10 p-2 text-[11px] hover:bg-rose-500/20", onClick: () => onIssueClick?.(issue), children: _jsxs("div", { className: "flex items-start gap-1.5", children: [_jsx(XCircle, { className: "mt-0.5 size-3 shrink-0 text-rose-400" }), _jsxs("div", { children: [_jsx("div", { className: "text-rose-200", children: issue.message }), issue.suggestion && (_jsxs("div", { className: "mt-1 flex items-center gap-1 text-[10px] text-rose-300/70", children: [_jsx(Info, { className: "size-3" }), issue.suggestion] }))] })] }) }, `error-${idx}`))) })] })), warnings.length > 0 && (_jsxs("div", { children: [_jsxs("div", { className: "mb-1 text-[10px] font-medium uppercase tracking-wide text-amber-400", children: ["\u8B66\u544A (", warnings.length, ")"] }), _jsx("ul", { className: "space-y-1", children: warnings.map((issue, idx) => (_jsx("li", { className: "cursor-pointer rounded border border-amber-500/20 bg-amber-500/10 p-2 text-[11px] hover:bg-amber-500/20", onClick: () => onIssueClick?.(issue), children: _jsxs("div", { className: "flex items-start gap-1.5", children: [_jsx(AlertTriangle, { className: "mt-0.5 size-3 shrink-0 text-amber-400" }), _jsxs("div", { children: [_jsx("div", { className: "text-amber-200", children: issue.message }), issue.suggestion && (_jsxs("div", { className: "mt-1 flex items-center gap-1 text-[10px] text-amber-300/70", children: [_jsx(Info, { className: "size-3" }), issue.suggestion] }))] })] }) }, `warning-${idx}`))) })] }))] }), _jsx("div", { className: "border-t border-white/10 px-3 py-2 text-[10px] text-text-dim", children: "\u70B9\u51FB\u95EE\u9898\u9879\u5B9A\u4F4D\u5230\u5BF9\u5E94\u8282\u70B9" })] }));
}
export function ValidationBadge({ count }) {
    if (count === 0)
        return null;
    return (_jsxs("span", { className: "inline-flex items-center gap-1 rounded-full bg-rose-500/20 px-2 py-0.5 text-[10px] text-rose-300", children: [_jsx(AlertTriangle, { className: "size-3" }), count, " \u4E2A\u95EE\u9898"] }));
}
