"""Aggregate-chat lobe/integration/entrypoint constants and spec tables."""

from __future__ import annotations

from pathlib import Path
from typing import Any

_AGGREGATE_MODEL_ID = "polaris.aggregate_llm.v1"
_DEFAULT_AGGREGATE_ROLE_IDS: tuple[str, ...] = (
    "pm",
    "architect",
    "chief_engineer",
    "director",
    "qa",
)
_AGGREGATE_FAILURE_SIGNAL_ALIASES: dict[str, str] = {
    "compile": "compile_failure",
    "compiler_failure": "compile_failure",
    "compile_error": "compile_failure",
    "tsc_failure": "typecheck_failure",
    "type_error": "typecheck_failure",
    "typecheck": "typecheck_failure",
    "apply_failure": "failed_apply",
    "patch_apply_failure": "failed_apply",
    "repo_map_empty": "empty_repo_map",
    "localization": "localization_uncertain",
}
_AGGREGATE_FAILURE_EVIDENCE_KEYS: dict[str, tuple[str, ...]] = {
    "compile_failure": ("compiler_output", "changed_files", "test_command"),
    "typecheck_failure": ("typecheck_output", "tsconfig_path", "changed_files"),
    "failed_apply": ("patch_payload", "apply_error", "target_paths"),
    "localization_uncertain": ("repo_map", "mentioned_symbols", "candidate_files"),
    "degraded_signal": ("degraded_reason", "cognitive_runtime_preflight", "session_id"),
    "empty_repo_map": ("repo_intelligence_result", "workspace", "language_filter"),
    "graph_boundary_violation": ("cell_id", "target_paths", "graph_edge"),
}


_AGGREGATE_LOBE_SPECS: tuple[dict[str, Any], ...] = (
    {
        "lobe_id": "constraint_boundary_generator",
        "title": "Architect + QA constraint boundary generator",
        "phase": "preflight",
        "role_ids": ("architect", "qa"),
        "virtual_role_ids": (),
        "capability_refs": (
            "docs.graph.catalog.cells",
            "docs.graph.subgraphs.context_plane",
            "polaris.kernelone.context.context_os.StateFirstContextOS",
            "polaris.cells.factory.cognitive_runtime",
        ),
        "attention_masks": (
            "graph_boundary",
            "forbid_prompt_leakage",
            "verification_before_write",
        ),
        "memory_triggers": (),
        "compute_tier": "cloud_control",
        "handoff_keys": (
            "constraint_topology",
            "negative_prompt_masks",
            "graph_boundary_verdict",
        ),
        "takeover_triggers": (
            "graph_boundary_violation",
            "prompt_leakage_risk",
            "unverified_write_plan",
        ),
        "output_contract": "constraint_topology_v1",
    },
    {
        "lobe_id": "dialectic_self_heal_loop",
        "title": "Chief Engineer + adversarial critic reasoning loop",
        "phase": "blueprint_refinement",
        "role_ids": ("chief_engineer", "qa"),
        "virtual_role_ids": ("adversarial_critic",),
        "capability_refs": (
            "polaris.cells.chief_engineer.blueprint",
            "polaris.kernelone.cognitive.governance.verification",
            "polaris.kernelone.tool_execution.code_validator",
            "polaris.kernelone.cognitive.execution.rollback_manager",
        ),
        "attention_masks": (
            "edge_case_attack",
            "rollback_required",
            "test_gate_required",
        ),
        "memory_triggers": ("verification_failure", "compiler_failure"),
        "compute_tier": "cloud_critic_local_retry",
        "handoff_keys": (
            "self_healed_blueprint",
            "edge_case_matrix",
            "rollback_plan",
        ),
        "takeover_triggers": (
            "blueprint_incomplete",
            "compile_failure",
            "typecheck_failure",
        ),
        "output_contract": "self_healed_blueprint_v1",
    },
    {
        "lobe_id": "hippocampus_controller",
        "title": "Director + ContextOS/Akashic memory router",
        "phase": "execution_context_projection",
        "role_ids": ("director",),
        "virtual_role_ids": (),
        "capability_refs": (
            "polaris.kernelone.context.context_os.StateFirstContextOS",
            "polaris.kernelone.akashic.semantic_memory.AkashicSemanticMemory",
            "polaris.kernelone.context.repo_intelligence.RepoIntelligenceFacade",
            "polaris.cells.roles.session.public.contracts",
        ),
        "attention_masks": (
            "active_window",
            "stable_facts",
            "open_loops",
        ),
        "memory_triggers": ("degraded_signal", "localization_uncertain", "long_session"),
        "compute_tier": "local_memory_router",
        "handoff_keys": (
            "context_projection",
            "akashic_recall_pack",
            "repo_localization_candidates",
        ),
        "takeover_triggers": (
            "degraded_signal",
            "empty_repo_map",
            "localization_uncertain",
        ),
        "output_contract": "context_projection_v1",
    },
    {
        "lobe_id": "tool_commit_guard",
        "title": "Director + QA governed commit guard",
        "phase": "apply_and_verify",
        "role_ids": ("director", "qa"),
        "virtual_role_ids": (),
        "capability_refs": (
            "polaris.cells.roles.kernel.transaction.turn_ledger",
            "polaris.kernelone.llm.toolkit.tool_normalization",
            "polaris.kernelone.tool_execution.code_validator",
            "polaris.cells.factory.cognitive_runtime.handoff",
        ),
        "attention_masks": (
            "single_commit",
            "tool_policy",
            "change_set_validation",
        ),
        "memory_triggers": ("rollback", "failed_apply", "integration_qa_failure"),
        "compute_tier": "local_execution_guard",
        "handoff_keys": (
            "validated_change_set",
            "tool_receipt",
            "qa_gate_result",
        ),
        "takeover_triggers": (
            "unsafe_tool_call",
            "change_set_out_of_scope",
            "integration_qa_failure",
        ),
        "output_contract": "verified_patch_v1",
    },
    {
        "lobe_id": "task_market_allocator",
        "title": "PM + Director + QA runtime task allocator",
        "phase": "stage_handoff",
        "role_ids": ("pm", "director", "qa"),
        "virtual_role_ids": (),
        "capability_refs": (
            "polaris.cells.runtime.task_market",
            "polaris.cells.runtime.projection",
            "polaris.cells.orchestration.pm_dispatch",
            "polaris.cells.factory.cognitive_runtime.receipt",
        ),
        "attention_masks": (
            "task_contract_quality",
            "stage_owner",
            "receipt_required",
        ),
        "memory_triggers": ("task_requeue", "dead_letter", "handoff_gap"),
        "compute_tier": "control_plane",
        "handoff_keys": (
            "task_contract",
            "stage_owner_matrix",
            "runtime_receipt_ids",
        ),
        "takeover_triggers": (
            "task_quality_below_gate",
            "handoff_gap",
            "dead_letter",
        ),
        "output_contract": "runtime_handoff_matrix_v1",
    },
)
_AGGREGATE_RUNTIME_INTEGRATION_SPECS: tuple[dict[str, Any], ...] = (
    {
        "tech_id": "acga_graph_cell_governance",
        "title": "ACGA 2.0 Graph/Cell governance",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "docs/graph/catalog/cells.yaml",
            "roles.runtime.build_aggregate_role_plan",
            "delivery.http./v1/chat/completions",
        ),
        "trigger_keys": ("workspace", "domain", "role_ids"),
        "evidence_keys": ("graph_catalog_cell", "required_capability_refs", "graph_boundary_verdict"),
        "runtime_effects": ("constrain role/capability selection before aggregate execution",),
        "benefit": "Keeps aggregate-model planning inside graph-owned architecture boundaries.",
        "capability_refs": ("docs.graph.catalog.cells",),
    },
    {
        "tech_id": "kernelone_agent_os",
        "title": "KernelOne Agent OS foundation",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "roles.runtime.stream_chat_turn",
            "roles.kernel.RoleExecutionKernel",
            "kernelone.context",
        ),
        "trigger_keys": ("execution_mode=single_turn",),
        "evidence_keys": ("strategy_fingerprint", "context_override", "runtime_receipts"),
        "runtime_effects": ("execute selected concrete role through KernelOne-backed role runtime",),
        "benefit": "Turns role lobes into a shared runtime substrate instead of prompt-only agents.",
        "capability_refs": ("polaris.kernelone", "polaris.cells.roles.kernel"),
    },
    {
        "tech_id": "turn_transaction_kernel_ledger",
        "title": "Turn Transaction Kernel / Turn Ledger",
        "status": "wired",
        "priority": "p0",
        "production_entrypoints": (
            "roles.runtime.stream_chat_turn",
            "roles.kernel.internal.transaction_kernel",
            "roles.kernel.internal.transaction.ledger",
        ),
        "trigger_keys": ("execution_mode=single_turn", "tool_call"),
        "evidence_keys": ("tool_calls", "turn_events_metadata", "receipt_ids"),
        "runtime_effects": ("commit or reject tool effects through the normal turn transaction flow",),
        "benefit": "Prevents aggregate execution from becoming an unaudited multi-agent chat transcript.",
        "capability_refs": ("polaris.cells.roles.kernel.transaction.turn_ledger",),
    },
    {
        "tech_id": "context_plane_isolation",
        "title": "Context Plane isolation",
        "status": "wired",
        "priority": "p0",
        "production_entrypoints": (
            "roles.runtime._prepare_session_request",
            "roles.runtime._enforce_required_context_os",
            "kernelone.context.context_os",
        ),
        "trigger_keys": ("context_os_expected", "state_first_context_os_enabled"),
        "evidence_keys": ("context_os_preflight", "context_os_audit", "context_os_snapshot"),
        "runtime_effects": ("separate control metadata from model-visible context projection",),
        "benefit": "Reduces prompt pollution while preserving auditable control-plane decisions.",
        "capability_refs": ("polaris.kernelone.context.context_os.StateFirstContextOS",),
    },
    {
        "tech_id": "descriptor_context_verify_packs",
        "title": "Descriptor / Context Pack / Verify Pack split",
        "status": "wired",
        "priority": "p2",
        "production_entrypoints": (
            "roles.runtime._build_aggregate_context_governance_pack",
            "cells.context.catalog",
            "cells.context.engine",
            "generated/context.pack.json",
        ),
        "trigger_keys": ("context_request", "verification_scope"),
        "evidence_keys": ("descriptor_pack", "context_pack", "verify_pack"),
        "runtime_effects": ("inject descriptor, working context, and verification summaries into aggregate turns",),
        "benefit": "Keeps retrieval, work, and verification attention layers distinct.",
        "capability_refs": ("polaris.cells.context.catalog", "polaris.cells.context.engine"),
    },
    {
        "tech_id": "strategy_profile_overlay_fingerprint",
        "title": "Strategy Profile + Role Overlay + Fingerprint",
        "status": "wired",
        "priority": "p0",
        "production_entrypoints": (
            "roles.runtime.stream_chat_turn",
            "roles.runtime.create_strategy_run",
            "runtime/strategy_runs",
        ),
        "trigger_keys": ("execution_mode=single_turn", "domain", "role"),
        "evidence_keys": ("profile_id", "profile_hash", "bundle_id", "strategy_receipt_path"),
        "runtime_effects": ("emit per-turn strategy identity before role execution",),
        "benefit": "Makes each brain-lobe activation traceable to a concrete context/tool policy.",
        "capability_refs": ("polaris.kernelone.context.strategy_profiles",),
    },
    {
        "tech_id": "cognitive_runtime_receipt_handoff",
        "title": "Cognitive Runtime Receipt / Handoff Pack",
        "status": "wired",
        "priority": "p0",
        "production_entrypoints": (
            "roles.runtime._emit_cognitive_runtime_shadow_artifacts",
            "factory.cognitive_runtime.record_runtime_receipt",
            "factory.cognitive_runtime.export_handoff_pack",
        ),
        "trigger_keys": ("cognitive_runtime_required", "session_id"),
        "evidence_keys": ("cognitive_runtime_evidence", "receipt_id", "handoff_id"),
        "runtime_effects": ("record completed role turns and export cross-lobe handoff packs",),
        "benefit": "Provides hard evidence for memory transfer instead of relying on chat history.",
        "capability_refs": ("polaris.cells.factory.cognitive_runtime",),
    },
    {
        "tech_id": "session_continuity_engine",
        "title": "Session Continuity Engine",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "roles.runtime._project_host_history",
            "roles.runtime._persist_session_turn_state",
            "context.session_continuity",
        ),
        "trigger_keys": ("session_id", "history", "include_session_snapshot"),
        "evidence_keys": ("stable_facts", "open_loops", "recent_window", "session_turn_events"),
        "runtime_effects": ("persist and reload structured session state across aggregate calls",),
        "benefit": "Turns long-running aggregate chats into stateful memory projection, not raw history piles.",
        "capability_refs": ("polaris.kernelone.context.session_continuity",),
    },
    {
        "tech_id": "context_catalog_graph_semantic_retrieval",
        "title": "Context Catalog / Graph-constrained semantic retrieval",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "roles.runtime._build_aggregate_context_governance_pack",
            "cells.context.catalog",
            "cells.context.engine.internal.search_gateway",
        ),
        "trigger_keys": ("context_query", "cell_scope", "graph_boundary"),
        "evidence_keys": ("catalog_descriptor", "graph_scope", "retrieval_candidates"),
        "runtime_effects": ("run catalog search gateway before aggregate role execution",),
        "benefit": "Prevents semantic memory recall from crossing Cell ownership boundaries.",
        "capability_refs": ("polaris.cells.context.catalog",),
    },
    {
        "tech_id": "repo_intelligence_localizer",
        "title": "Repo Intelligence / Repo Map Localizer",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "roles.runtime._build_session_request",
            "roles.runtime.public.context_adapter.augment_context_with_repo_intelligence",
            "kernelone.context.repo_intelligence",
        ),
        "trigger_keys": ("domain=code", "localization_uncertain", "empty_repo_map"),
        "evidence_keys": ("repo_intelligence", "candidate_files", "symbol_tags"),
        "runtime_effects": ("project code-localization candidates into role turn context",),
        "benefit": "Improves local-model coding accuracy by aiming attention at likely files first.",
        "capability_refs": ("polaris.kernelone.context.repo_intelligence.RepoIntelligenceFacade",),
    },
    {
        "tech_id": "akashic_knowledge_pipeline",
        "title": "Akashic Knowledge Pipeline",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "roles.runtime._build_aggregate_memory_recall_pack",
            "kernelone.memory",
            "kernelone.context.context_os.memory",
            "kernelone.context.context_os.memory_search",
        ),
        "trigger_keys": ("long_session", "memory_search", "akashic_recall_pack"),
        "evidence_keys": ("memory_candidates", "semantic_chunks", "vector_store_refs"),
        "runtime_effects": ("call ContextOS MemoryManager during aggregate memory fallback turns",),
        "benefit": "Allows repeated execution experience and documents to become reusable recall material.",
        "capability_refs": ("polaris.kernelone.akashic.semantic_memory.AkashicSemanticMemory",),
    },
    {
        "tech_id": "tool_normalization_edit_blocks",
        "title": "Tool Normalization / Edit Blocks Normalizer",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "roles.kernel.internal.tool_call_protocol",
            "roles.kernel.internal.output.action_parser",
            "roles.kernel.internal.transaction.modification_contract",
        ),
        "trigger_keys": ("tool_call", "edit_block", "failed_apply"),
        "evidence_keys": ("normalized_tool_call", "modification_contract", "apply_error"),
        "runtime_effects": ("normalize unstable model tool output before execution or repair",),
        "benefit": "Reduces format drift when aggregate execution delegates coding to weaker local models.",
        "capability_refs": ("polaris.kernelone.llm.toolkit.tool_normalization",),
    },
    {
        "tech_id": "change_set_validation_rollback",
        "title": "Change-set Validation + Rollback Manager",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "factory.cognitive_runtime.validate_change_set",
            "roles.kernel.internal.transaction.write_authority",
            "kernelone.cognitive.execution.rollback_manager",
        ),
        "trigger_keys": ("write_tool", "change_set", "rollback"),
        "evidence_keys": ("validated_change_set", "rollback_snapshot", "scope_lease"),
        "runtime_effects": ("guard physical writes with validation and rollback receipts",),
        "benefit": "Adds a write fuse between aggregate reasoning and repository mutation.",
        "capability_refs": ("polaris.kernelone.cognitive.execution.rollback_manager",),
    },
    {
        "tech_id": "task_market_runtime_projection",
        "title": "Task Market / Runtime Projection",
        "status": "wired",
        "priority": "p2",
        "production_entrypoints": (
            "roles.runtime._build_aggregate_task_market_projection_pack",
            "cells.runtime.task_market",
            "cells.runtime.projection",
            "cells.orchestration.pm_dispatch",
        ),
        "trigger_keys": ("pm_task_id", "stage_owner", "runtime_projection"),
        "evidence_keys": ("task_contract", "stage_owner_matrix", "projection_snapshot"),
        "runtime_effects": ("snapshot task-market projection during aggregate role execution",),
        "benefit": "Makes multi-role delivery a governed workflow rather than ad hoc cross-calls.",
        "capability_refs": ("polaris.cells.runtime.task_market", "polaris.cells.runtime.projection"),
    },
    {
        "tech_id": "cognitive_knowledge_distiller",
        "title": "Cognitive Knowledge Distiller",
        "status": "wired",
        "priority": "p2",
        "production_entrypoints": (
            "roles.runtime._build_aggregate_distilled_knowledge_pack",
            "roles.runtime._distill_aggregate_lobe_result",
            "docs.graph.catalog.cells:cognitive.knowledge_distiller",
            "polaris.cells.cognitive.knowledge_distiller.public.service",
        ),
        "trigger_keys": ("receipt_id", "post_run_distillation"),
        "evidence_keys": ("distilled_lesson", "source_receipts", "replay_case"),
        "runtime_effects": ("retrieve distilled knowledge before execution and distill lobe results after execution",),
        "benefit": "Converts one-off aggregate runs into reusable operational knowledge.",
        "capability_refs": ("cognitive.knowledge_distiller",),
    },
    {
        "tech_id": "contextos_attention_phase_budgeting",
        "title": "ContextOS Attention / Phase-aware Budgeting / Predictive Compression",
        "status": "wired",
        "priority": "p1",
        "production_entrypoints": (
            "roles.runtime._build_aggregate_contextos_attention_budget_pack",
            "kernelone.context.context_os.attention",
            "kernelone.context.context_os.phase_budget_planner",
            "kernelone.context.context_os.predictive",
        ),
        "trigger_keys": ("phase", "budget_plan", "attention_masks"),
        "evidence_keys": ("attention_scores", "phase_budget", "compression_decisions"),
        "runtime_effects": ("inject phase budget, attention scores, and predictive compression signals per lobe",),
        "benefit": "Supports different context budgets for planning, localization, execution, and QA lobes.",
        "capability_refs": ("polaris.kernelone.context.context_os.phase_budget_planner",),
    },
)

_SESSION_PUBLIC_EXPORTS = frozenset(
    {
        "PathSecurityError",
        "RoleDataStore",
        "RoleDataStoreError",
    }
)
_BACKEND_ROOT = Path(__file__).resolve().parents[6]
_ENTRYPOINT_MODULE_ALIASES: dict[str, str] = {
    "cells.context.catalog": "polaris.cells.context.catalog",
    "cells.context.engine": "polaris.cells.context.engine",
    "cells.context.engine.internal.search_gateway": "polaris.cells.context.engine.internal.search_gateway",
    "cells.orchestration.pm_dispatch": "polaris.cells.orchestration.pm_dispatch",
    "cells.runtime.projection": "polaris.cells.runtime.projection",
    "cells.runtime.task_market": "polaris.cells.runtime.task_market",
    "factory.cognitive_runtime.receipts": "polaris.cells.factory.cognitive_runtime.public.service",
    "kernelone.context": "polaris.kernelone.context",
    "kernelone.context.context_os": "polaris.kernelone.context.context_os",
    "kernelone.context.context_os.attention": "polaris.kernelone.context.context_os.attention",
    "kernelone.context.context_os.memory": "polaris.kernelone.context.context_os.memory",
    "kernelone.context.context_os.memory_search": "polaris.kernelone.context.context_os.memory_search",
    "kernelone.context.context_os.phase_budget_planner": "polaris.kernelone.context.context_os.phase_budget_planner",
    "kernelone.context.context_os.predictive": "polaris.kernelone.context.context_os.predictive",
    "kernelone.context.repo_intelligence": "polaris.kernelone.context.repo_intelligence",
    "kernelone.cognitive.execution.rollback_manager": "polaris.kernelone.cognitive.execution.rollback_manager",
    "kernelone.memory": "polaris.kernelone.memory",
    "context.session_continuity": "polaris.kernelone.context.session_continuity",
    "roles.kernel.internal.output.action_parser": "polaris.cells.roles.kernel.internal.output.action_parser",
    "roles.kernel.internal.tool_call_protocol": "polaris.cells.roles.kernel.internal.tool_call_protocol",
    "roles.kernel.internal.transaction.ledger": "polaris.cells.roles.kernel.internal.transaction.ledger",
    "roles.kernel.internal.transaction.modification_contract": (
        "polaris.cells.roles.kernel.internal.transaction.modification_contract"
    ),
    "roles.kernel.internal.transaction.write_authority": (
        "polaris.cells.roles.kernel.internal.transaction.write_authority"
    ),
    "roles.kernel.internal.transaction_kernel": "polaris.cells.roles.kernel.internal.transaction_kernel",
}
