"""Bootstrap template catalog for WorkerExecutor (Cell Implementation).

Migrated from ``polaris.cells.director.execution.internal.bootstrap_template_catalog``.

This module contains all bootstrap template generation functions,
decoupled from the execution logic for maintainability.

All text operations MUST explicitly use UTF-8 encoding.
"""

from __future__ import annotations


def get_intelligent_bootstrap_files(
    language: str,
    framework: str | None,
    task_subject: str,
    task_description: str,
) -> list[dict[str, str]]:
    """Get intelligent bootstrap files based on language and framework.

    Args:
        language: Programming language (python, typescript, javascript, go, rust)
        framework: Optional framework (fastapi, flask, react, express, etc.)
        task_subject: Task subject line
        task_description: Task description

    Returns:
        List of file dictionaries with 'path' and 'content' keys
    """
    if language == "python":
        return _get_intelligent_python_bootstrap(framework, task_subject, task_description)
    elif language in ("typescript", "javascript"):
        return _get_intelligent_ts_bootstrap(language, task_subject, task_description)
    elif language == "go":
        return _get_intelligent_go_bootstrap(task_subject, task_description)
    elif language == "rust":
        return _get_intelligent_rust_bootstrap(task_subject, task_description)
    else:
        return _get_generic_bootstrap_files(task_subject, task_description)


def _get_intelligent_python_bootstrap(
    framework: str | None,
    task_subject: str,
    task_description: str,
) -> list[dict[str, str]]:
    """Get Python bootstrap with actual implementation."""
    if framework == "fastapi":
        main_content = '''"""FastAPI application.

Generated by Polaris Worker.
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="Generated API", version="0.1.0")


class HealthResponse(BaseModel):
    status: str
    version: str


@app.get("/health", response_model=HealthResponse)
async def health_check():
    """Health check endpoint."""
    return HealthResponse(status="healthy", version="0.1.0")


@app.get("/")
async def root():
    """Root endpoint."""
    return {"message": "Welcome to the API", "version": "0.1.0"}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
        req_content = "fastapi>=0.100.0\nuvicorn[standard]>=0.23.0\npydantic>=2.0.0\n"
    elif framework == "flask":
        main_content = '''"""Flask application.

Generated by Polaris Worker.
"""

from flask import Flask, jsonify

app = Flask(__name__)


@app.route("/health")
def health_check():
    """Health check endpoint."""
    return jsonify({"status": "healthy", "version": "0.1.0"})


@app.route("/")
def root():
    """Root endpoint."""
    return jsonify({"message": "Welcome to the API", "version": "0.1.0"})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000, debug=True)
'''
        req_content = "flask>=2.3.0\nwerkzeug>=2.3.0\n"
    else:
        main_content = '''"""Main application.

Generated by Polaris Worker.
"""

import argparse
import logging
import sys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Generated Application")
    parser.add_argument("--version", action="version", version="0.1.0")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    logger.info("Application started")
    print("Hello from Polaris generated application!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
        req_content = "# Add dependencies here\n"

    subject = task_subject or "Generated Project"
    description = task_description or "A Python project."

    return [
        {"path": "fastapi_entrypoint.py", "content": main_content},
        {"path": "requirements.txt", "content": req_content},
        {"path": "tui_runtime.md", "content": f"# {subject}\n\n{description}\n"},
        {"path": "src/__init__.py", "content": '"""Source package."""\n'},
    ]


def _get_intelligent_ts_bootstrap(
    language: str,
    task_subject: str,
    task_description: str,
) -> list[dict[str, str]]:
    """Get TypeScript/JavaScript bootstrap with actual implementation."""
    ext = "ts" if language == "typescript" else "js"

    package_content = """{
  "name": "generated-project",
  "version": "0.1.0",
  "description": "Generated by Polaris",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/index.js",
    "dev": "ts-node src/index.ts"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0",
    "ts-node": "^10.9.0"
  }
}
"""

    if language == "typescript":
        main_content = """/**
 * Main application entry point.
 * Generated by Polaris Worker.
 */

interface AppConfig {
  name: string;
  version: string;
}

const config: AppConfig = {
  name: "generated-project",
  version: "0.1.0",
};

function main(): void {
  console.log(`Starting ${config.name} v${config.version}`);
  console.log("Hello from Polaris generated TypeScript application!");
}

main();
"""
        tsconfig = """{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true
  }
}
"""
    else:
        main_content = """/**
 * Main application entry point.
 * Generated by Polaris Worker.
 */

const config = {
  name: "generated-project",
  version: "0.1.0",
};

function main() {
  console.log(`Starting ${config.name} v${config.version}`);
  console.log("Hello from Polaris generated JavaScript application!");
}

main();
"""
        tsconfig = ""

    subject = task_subject or "Generated Project"
    description = task_description or "A JavaScript/TypeScript project."

    files = [
        {"path": "package.json", "content": package_content},
        {"path": f"src/index.{ext}", "content": main_content},
        {"path": "tui_runtime.md", "content": f"# {subject}\n\n{description}\n"},
    ]

    if tsconfig:
        files.append({"path": "tsconfig.json", "content": tsconfig})

    return files


def _get_intelligent_go_bootstrap(
    task_subject: str,
    task_description: str,
) -> list[dict[str, str]]:
    """Get Go bootstrap with actual implementation."""
    main_content = """package main

// Generated by Polaris Worker

import (
	"flag"
	"fmt"
	"log"
)

const (
	Version = "0.1.0"
	AppName = "generated-project"
)

type Config struct {
	Verbose bool
	Port    int
}

func main() {
	cfg := Config{}
	flag.BoolVar(&cfg.Verbose, "verbose", false, "Enable verbose logging")
	flag.IntVar(&cfg.Port, "port", 8080, "Server port")
	flag.Parse()

	if cfg.Verbose {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
	}

	log.Printf("Starting %s v%s on port %d", AppName, Version, cfg.Port)
	fmt.Println("Hello from Polaris generated Go application!")
}
"""
    subject = task_subject or "Generated Project"
    description = task_description or "A Go project."

    return [
        {"path": "main.go", "content": main_content},
        {"path": "go.mod", "content": "module generated-project\n\ngo 1.21\n"},
        {"path": "tui_runtime.md", "content": f"# {subject}\n\n{description}\n"},
    ]


def _get_intelligent_rust_bootstrap(
    task_subject: str,
    task_description: str,
) -> list[dict[str, str]]:
    """Get Rust bootstrap with actual implementation."""
    cargo_content = """[package]
name = "generated-project"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
"""

    main_content = """//! Main application entry point.
//! Generated by Polaris Worker.

use generated_project::service::{load_sample_feed, summarize_titles};

#[tokio::main]
async fn main() {
    println!("Starting generated-project v0.1.0");
    let feed = load_sample_feed().await;
    let summary = summarize_titles(&feed);
    println!("Loaded {} items", feed.len());
    println!("Summary: {summary}");
}
"""

    lib_content = """//! Library entry for generated project.

pub mod service;
"""

    service_content = """use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedItem {
    pub title: String,
    pub url: String,
}

pub async fn load_sample_feed() -> Vec<FeedItem> {
    vec![
        FeedItem {
            title: "Polaris architecture notes".to_string(),
            url: "https://example.com/polaris-architecture".to_string(),
        },
        FeedItem {
            title: "Director retry and queue fixes".to_string(),
            url: "https://example.com/director-retry-fix".to_string(),
        },
    ]
}

pub fn summarize_titles(items: &[FeedItem]) -> String {
    items
        .iter()
        .map(|item| item.title.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}
"""

    test_content = """use generated_project::service::{load_sample_feed, summarize_titles};

#[tokio::test]
async fn load_sample_feed_returns_items() {
    let items = load_sample_feed().await;
    assert!(!items.is_empty());
    assert!(items.iter().all(|item| !item.title.is_empty()));
}

#[test]
fn summarize_titles_joins_titles() {
    let items = vec![];
    let summary = summarize_titles(&items);
    assert_eq!(summary, "");
}
"""

    subject = task_subject or "Generated Project"

    return [
        {"path": "Cargo.toml", "content": cargo_content},
        {"path": "src/main.rs", "content": main_content},
        {"path": "src/lib.rs", "content": lib_content},
        {"path": "src/service.rs", "content": service_content},
        {"path": "tests/integration_test.rs", "content": test_content},
        {
            "path": "tui_runtime.md",
            "content": (
                f"# {subject}\n\n"
                "Generated Rust bootstrap with async runtime, feed service, and tests.\n"
                "## Project Layout\n\n"
                "- `src/main.rs`: application entry point\n"
                "- `src/lib.rs`: library module exports\n"
                "- `src/service.rs`: feed loading and summary utilities\n"
                "- `tests/integration_test.rs`: integration checks\n\n"
                "## Commands\n\n"
                "- `cargo test`\n"
                "- `cargo run`\n"
            ),
        },
    ]


def _get_generic_bootstrap_files(
    task_subject: str,
    task_description: str,
) -> list[dict[str, str]]:
    """Get generic bootstrap files for unknown languages."""
    subject = task_subject or "Generated Project"
    description = task_description or "A generic project."

    return [
        {
            "path": "tui_runtime.md",
            "content": f"# {subject}\n\n{description}\n\n"
            "## Getting Started\n\n"
            "1. Add your dependencies\n"
            "2. Implement your code\n"
            "3. Run and test\n",
        },
    ]


def get_python_bootstrap_files() -> list[dict[str, str]]:
    """Legacy function for Python bootstrap - returns basic template."""
    return [
        {
            "path": "fastapi_entrypoint.py",
            "content": '"""Main application.\nGenerated by Polaris.\n"""\n\ndef main():\n    print("Hello from Polaris!")\n\n\nif __name__ == "__main__":\n    main()\n',
        },
        {
            "path": "requirements.txt",
            "content": "# Add your dependencies here\n",
        },
        {
            "path": "tui_runtime.md",
            "content": "# Generated Project\n\nA Python project generated by Polaris.\n",
        },
    ]


def get_typescript_bootstrap_files() -> list[dict[str, str]]:
    """Legacy function for TypeScript bootstrap - returns basic template."""
    return [
        {
            "path": "package.json",
            "content": '{\n  "name": "generated-project",\n  "version": "0.1.0",\n  "main": "dist/index.js",\n  "scripts": {\n    "build": "tsc",\n    "start": "node dist/index.js"\n  },\n  "devDependencies": {\n    "@types/node": "^20.0.0",\n    "typescript": "^5.0.0"\n  }\n}\n',
        },
        {
            "path": "src/index.ts",
            "content": 'console.log("Hello from Polaris!");\n',
        },
        {
            "path": "tsconfig.json",
            "content": '{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "commonjs",\n    "outDir": "./dist",\n    "strict": true\n  }\n}\n',
        },
        {
            "path": "tui_runtime.md",
            "content": "# Generated Project\n\nA TypeScript project generated by Polaris.\n",
        },
    ]


def get_generic_bootstrap_files() -> list[dict[str, str]]:
    """Legacy function for generic bootstrap - returns basic template."""
    return [
        {
            "path": "tui_runtime.md",
            "content": "# Generated Project\n\nA project generated by Polaris.\n",
        },
    ]
