"""Public boundary for `roles.kernel` cell.

This module intentionally uses lazy re-exports so importing a narrow public
submodule such as ``turn_contracts`` does not eagerly import the heavier
``service`` boundary and its internal kernel runtime dependencies.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_TO_MODULE: dict[str, str] = {
    "FACTORY_ROLE_EVIDENCE_CUTOFF_ACK_SCHEMA": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FACTORY_ROLE_EVIDENCE_CUTOFF_PROOF_SCHEMA": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FACTORY_ROLE_EVIDENCE_CUTOFF_REQUEST_SCHEMA": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FACTORY_ROLE_FROZEN_SEMANTIC_REQUEST_SCHEMA": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FACTORY_ROLE_SEMANTIC_CANDIDATE_SCHEMA": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FACTORY_ROLE_EVIDENCE_AUTHORITY_BINDING_SCHEMA": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleEvidenceAuthorityBindingV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleEvidenceCutoffAckV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleEvidenceCutoffPort": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleEvidenceCutoffProofV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleEvidenceCutoffRequestV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleEvidenceCutoffSourceHeadV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleFrozenSemanticRequestV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleSemanticCandidateV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "FactoryRoleSemanticRequestIdentityV1": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "bind_factory_role_evidence_authority": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "contains_factory_role_evidence_runtime_authority": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "get_factory_role_evidence_authority_binding": "polaris.cells.roles.kernel.public.final_request_evidence_cutoff",
    "DirectedEffectAttemptHeartbeatStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectAttemptHeartbeatResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectAttemptValidationStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectAttemptValidationResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DeferredDirectorRepairEffectBindingV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DeferredDirectorCommandRequestV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DeferredDirectorRepairRequestV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DeferredDirectorRepairSynthesisResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectContextClaimStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectContextClaimResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectOperationClaimStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectExecutionContextV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceAdminPortV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceConsumeStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceConsumePortV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceConsumeResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFencePortsV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceRegistrationStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceRegistrationResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceReleaseStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectFenceReleaseResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectLifecycleStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectLifecycleResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectMutationStatusV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectMutationPortResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectMutationPortV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectPreparedMemberV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectRuntimeDependenciesV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectToolResultV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "DirectedEffectToolResultValueV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "PreparedDirectedEffectBatchV1": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "validate_directed_effect_execution_context": "polaris.cells.roles.kernel.public.directed_effect_contracts",
    "create_directed_effect_fence_ports": "polaris.cells.roles.kernel.public.directed_effect_service",
    "create_deferred_director_command_request": "polaris.cells.roles.kernel.public.deferred_repair_service",
    "create_deferred_director_repair_request": "polaris.cells.roles.kernel.public.deferred_repair_service",
    "ToolClassificationV1": "polaris.cells.roles.kernel.public.turn_contracts",
    "classify_tool_invocation": "polaris.cells.roles.kernel.public.turn_contracts",
    "KernelConfig": "polaris.cells.roles.kernel.public.config",
    "get_default_config": "polaris.cells.roles.kernel.public.config",
    "BuildRolePromptCommandV1": "polaris.cells.roles.kernel.public.contracts",
    "CheckRoleQualityCommandV1": "polaris.cells.roles.kernel.public.contracts",
    "ClassifyKernelErrorQueryV1": "polaris.cells.roles.kernel.public.contracts",
    "ExecuteRoleKernelTurnCommandV1": "polaris.cells.roles.kernel.public.contracts",
    "IRoleKernelService": "polaris.cells.roles.kernel.public.contracts",
    "ParseRoleOutputCommandV1": "polaris.cells.roles.kernel.public.contracts",
    "ResolveRetryPolicyQueryV1": "polaris.cells.roles.kernel.public.contracts",
    "RoleKernelError": "polaris.cells.roles.kernel.public.contracts",
    "RoleKernelParsedOutputEventV1": "polaris.cells.roles.kernel.public.contracts",
    "RoleKernelPromptBuiltEventV1": "polaris.cells.roles.kernel.public.contracts",
    "RoleKernelQualityCheckedEventV1": "polaris.cells.roles.kernel.public.contracts",
    "RoleKernelResultV1": "polaris.cells.roles.kernel.public.contracts",
    "ROLE_PROMPT_TEMPLATES": "polaris.cells.roles.kernel.public.prompt_templates",
    "SHARED_SECURITY_BOUNDARY": "polaris.cells.roles.kernel.public.prompt_templates",
    "CONSTITUTION": "polaris.cells.roles.kernel.public.service",
    "AllocationResult": "polaris.cells.roles.kernel.public.service",
    "AntiPattern": "polaris.cells.roles.kernel.public.service",
    "CacheEntry": "polaris.cells.roles.kernel.public.service",
    "CompressionStrategy": "polaris.cells.roles.kernel.public.service",
    "ConstitutionalRoleContext": "polaris.cells.roles.kernel.public.service",
    "ConstitutionEnforcer": "polaris.cells.roles.kernel.public.service",
    "ConstitutionGuard": "polaris.cells.roles.kernel.public.service",
    "ConstitutionViolationError": "polaris.cells.roles.kernel.public.service",
    "ContextOverride": "polaris.cells.roles.kernel.public.service",
    "ContextRequest": "polaris.cells.roles.kernel.public.service",
    "ContextResult": "polaris.cells.roles.kernel.public.service",
    "ContextStats": "polaris.cells.roles.kernel.public.service",
    "DeliveryMode": "polaris.cells.roles.kernel.internal.transaction.delivery_contract",
    "ConversationHistory": "polaris.cells.roles.kernel.public.service",
    "ErrorCategory": "polaris.cells.roles.kernel.public.service",
    "LLMCache": "polaris.cells.roles.kernel.public.service",
    "LLMCallEvent": "polaris.cells.roles.kernel.public.service",
    "LLMEventEmitter": "polaris.cells.roles.kernel.public.service",
    "LLMEventType": "polaris.cells.roles.kernel.public.service",
    "LLMResponse": "polaris.cells.roles.kernel.public.service",
    "MemorySnippet": "polaris.cells.roles.kernel.public.service",
    "OutputParser": "polaris.cells.roles.kernel.public.service",
    "PromptBuilder": "polaris.cells.roles.kernel.public.service",
    "PromptContext": "polaris.cells.roles.kernel.public.service",
    "QualityChecker": "polaris.cells.roles.kernel.public.service",
    "QualityResult": "polaris.cells.roles.kernel.public.service",
    "RetryDecision": "polaris.cells.roles.kernel.public.service",
    "RetryPolicyEngine": "polaris.cells.roles.kernel.public.service",
    "Role": "polaris.cells.roles.kernel.public.service",
    "RoleBoundary": "polaris.cells.roles.kernel.public.service",
    "RoleContextGateway": "polaris.cells.roles.kernel.public.service",
    "RoleExecutionKernel": "polaris.cells.roles.kernel.public.service",
    "RoleToolGateway": "polaris.cells.roles.kernel.public.service",
    "StructuredLLMResponse": "polaris.cells.roles.kernel.public.service",
    "SystemContext": "polaris.cells.roles.kernel.public.service",
    "TaskContext": "polaris.cells.roles.kernel.public.service",
    "ThinkingResult": "polaris.cells.roles.kernel.public.service",
    "TokenBudget": "polaris.cells.roles.kernel.public.service",
    "TokenEstimator": "polaris.cells.roles.kernel.public.service",
    "ToolAuthorizationError": "polaris.cells.roles.kernel.public.service",
    "ToolCallResult": "polaris.cells.roles.kernel.public.service",
    "ToolGatewayManager": "polaris.cells.roles.kernel.public.service",
    "ViolationLevel": "polaris.cells.roles.kernel.public.service",
    "classify_error": "polaris.cells.roles.kernel.public.service",
    "emit_llm_event": "polaris.cells.roles.kernel.public.service",
    "get_global_emitter": "polaris.cells.roles.kernel.public.service",
    "get_global_llm_cache": "polaris.cells.roles.kernel.public.service",
    "get_global_token_budget": "polaris.cells.roles.kernel.public.service",
    "get_max_retries": "polaris.cells.roles.kernel.public.service",
    "extract_target_path_from_payload": "polaris.cells.roles.kernel.public.service",
    "is_authoritative_write_invocation": "polaris.cells.roles.kernel.public.service",
    "is_authoritative_write_path": "polaris.cells.roles.kernel.public.service",
    "is_authoritative_write_result": "polaris.cells.roles.kernel.public.service",
    "is_control_plane_write_path": "polaris.cells.roles.kernel.public.service",
    "is_action_allowed": "polaris.cells.roles.kernel.public.service",
    "is_retryable": "polaris.cells.roles.kernel.public.service",
    "normalize_write_target_path": "polaris.cells.roles.kernel.public.service",
    "set_global_llm_cache": "polaris.cells.roles.kernel.public.service",
    "AssistantMessage": "polaris.cells.roles.kernel.public.transcript_ir",
    "CanonicalToolCallEntry": "polaris.cells.roles.kernel.public.transcript_ir",
    "ControlEvent": "polaris.cells.roles.kernel.public.transcript_ir",
    "ControlEventType": "polaris.cells.roles.kernel.public.transcript_ir",
    "ParsedToolPlan": "polaris.cells.roles.kernel.public.transcript_ir",
    "ReasoningSummary": "polaris.cells.roles.kernel.public.transcript_ir",
    "SanitizedOutput": "polaris.cells.roles.kernel.public.transcript_ir",
    "SystemInstruction": "polaris.cells.roles.kernel.public.transcript_ir",
    "ToolResultStatus": "polaris.cells.roles.kernel.public.transcript_ir",
    "TranscriptAppendRequest": "polaris.cells.roles.kernel.public.transcript_ir",
    "TranscriptDelta": "polaris.cells.roles.kernel.public.transcript_ir",
    "TranscriptItem": "polaris.cells.roles.kernel.public.transcript_ir",
    "UserMessage": "polaris.cells.roles.kernel.public.transcript_ir",
    "from_assistant_message": "polaris.cells.roles.kernel.public.transcript_ir",
    "from_control_event": "polaris.cells.roles.kernel.public.transcript_ir",
    "from_tool_result": "polaris.cells.roles.kernel.public.transcript_ir",
    "get_dead_loop_metrics": "polaris.cells.roles.kernel.public.metrics_contracts",
    "LLMInvoker": "polaris.cells.roles.kernel.internal.llm_caller.invoker",
    "create_role_transaction_kernel": "polaris.cells.roles.kernel.public.transaction_contracts",
    "extract_continuation_prompt_metadata": "polaris.cells.roles.kernel.public.transaction_contracts",
    "extract_target_files_from_message": "polaris.cells.roles.kernel.internal.transaction.contract_guards",
}

__all__ = list(_EXPORT_TO_MODULE)


def __getattr__(name: str) -> Any:
    """Resolve public exports lazily to avoid import-time cycles."""
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    return getattr(module, name)


def __dir__() -> list[str]:
    """Return the supported public re-export surface."""
    return sorted(__all__)
