"""Public boundary for `workspace.integrity` cell."""

from polaris.cells.workspace.integrity.public.contracts import (
    DocsTemplatesResultV1,
    EnsureDocsReadyCommandV1,
    GenerateDocsTemplatesCommandV1,
    IWorkspaceIntegrity,
    ValidateWorkspaceCommandV1,
    WorkspaceIntegrityError,
)
from polaris.cells.workspace.integrity.public.service import (
    WorkspaceIntegrityService,
    build_docs_templates,
    clear_workspace_status,
    default_qa_commands,
    detect_project_profile,
    ensure_docs_ready_command,
    ensure_docs_ready_or_raise,
    generate_docs_templates_command,
    get_code_parser,
    is_safe_docs_path,
    normalize_rel_path,
    read_workspace_status,
    select_docs_target_root,
    validate_workspace,
    validate_workspace_command,
    workspace_has_docs,
    workspace_status_path,
    write_workspace_status,
)

__all__ = [
    "DocsTemplatesResultV1",
    "EnsureDocsReadyCommandV1",
    "GenerateDocsTemplatesCommandV1",
    "IWorkspaceIntegrity",
    "ValidateWorkspaceCommandV1",
    "WorkspaceIntegrityError",
    "WorkspaceIntegrityService",
    "build_docs_templates",
    "clear_workspace_status",
    "default_qa_commands",
    "detect_project_profile",
    "ensure_docs_ready_command",
    "ensure_docs_ready_or_raise",
    "generate_docs_templates_command",
    "get_code_parser",
    "is_safe_docs_path",
    "normalize_rel_path",
    "read_workspace_status",
    "select_docs_target_root",
    "validate_workspace",
    "validate_workspace_command",
    "workspace_has_docs",
    "workspace_status_path",
    "write_workspace_status",
]
