"""Technical contracts submodule."""

from __future__ import annotations

from polaris.kernelone.contracts.technical.auth import (
    AuthCheckerPort,
    AuthResult,
    AuthStrength,
)
from polaris.kernelone.contracts.technical.master_types import (
    EFFECT_PAYLOAD_MAX_BYTES,
    EFFECT_TAG_MAX_LENGTH,
    GENESIS_HASH,
    KERNELONE_VERSION,
    LOCK_TIMEOUT_DEFAULT_SECONDS,
    LOCK_TTL_DEFAULT_SECONDS,
    Effect,
    EffectTracker,
    EffectType,
    Envelope,
    ErrorCategory,
    KernelError,
    KernelOneError,
    LockAcquireResult,
    LockOptions,
    LockPort,
    LockReleaseResult,
    Result,
    RuntimeHealthReport,
    ScheduledTask,
    ScheduleKind,
    ScheduleResult,
    SchedulerPort,
    ScheduleSpec,
    StreamChunk,
    StreamDone,
    StreamError,
    StreamEvent,
    SubsystemHealth,
    SubsystemStatus,
    TaggedError,
    TraceContext,
    _new_event_id,
    _new_run_id,
    _utc_now,
)

__all__ = [
    "EFFECT_PAYLOAD_MAX_BYTES",
    "EFFECT_TAG_MAX_LENGTH",
    "GENESIS_HASH",
    # Master types
    "KERNELONE_VERSION",
    "LOCK_TIMEOUT_DEFAULT_SECONDS",
    "LOCK_TTL_DEFAULT_SECONDS",
    # Auth contracts
    "AuthResult",
    "AuthStrength",
    "Effect",
    "EffectTracker",
    "EffectType",
    "Envelope",
    "ErrorCategory",
    "AuthCheckerPort",
    "KernelError",
    "KernelOneError",
    "LockAcquireResult",
    "LockOptions",
    "LockPort",
    "LockReleaseResult",
    "Result",
    "RuntimeHealthReport",
    "ScheduleKind",
    "ScheduleResult",
    "ScheduleSpec",
    "ScheduledTask",
    "SchedulerPort",
    "StreamChunk",
    "StreamDone",
    "StreamError",
    "StreamEvent",
    "SubsystemHealth",
    "SubsystemStatus",
    "TaggedError",
    "TraceContext",
    "_new_event_id",
    "_new_run_id",
    "_utc_now",
]
