#!/usr/bin/env python3
"""Generate an SVG coverage badge from pytest-cov output.

Reads coverage.xml (generated by pytest --cov-report=xml) and writes
an SVG badge to docs/assets/badges/coverage.svg.

Color scheme:
- red: < 50%
- yellow: 50% - 80%
- green: >= 80%

Usage:
    python scripts/generate_coverage_badge.py
    python scripts/generate_coverage_badge.py --coverage-xml coverage.xml --output docs/assets/badges/coverage.svg
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def parse_coverage_xml(path: Path) -> float:
    """Parse coverage.xml and return the line-rate as a percentage."""
    tree = ET.parse(path)
    root = tree.getroot()
    line_rate = root.get("line-rate")
    if line_rate is None:
        raise ValueError("No line-rate attribute found in coverage.xml root")
    return float(line_rate) * 100


def parse_coverage_text(text: str) -> float | None:
    """Attempt to parse coverage percentage from pytest-cov terminal output."""
    for line in text.splitlines():
        if "TOTAL" in line or "%" in line:
            parts = line.split()
            for part in parts:
                clean = part.replace("%", "").strip()
                try:
                    val = float(clean)
                    if 0 <= val <= 100:
                        return val
                except ValueError:
                    continue
    return None


def color_for_coverage(pct: float) -> str:
    """Return badge color based on coverage percentage."""
    if pct < 50:
        return "#e05d44"  # red
    if pct < 80:
        return "#dfb317"  # yellow
    return "#4c1"  # green


def generate_svg(percentage: float) -> str:
    """Generate a shields.io-style SVG badge."""
    color = color_for_coverage(percentage)
    label = "coverage"
    value_text = f"{percentage:.1f}%"

    label_width = 70
    value_width = 60
    total_width = label_width + value_width
    height = 20
    label_text_x = label_width / 2
    value_text_x = label_width + value_width / 2
    text_y = 14

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{total_width}" height="{height}" role="img" aria-label="{label}: {value_text}">
  <title>{label}: {value_text}</title>
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="r">
    <rect width="{total_width}" height="{height}" rx="3" fill="#fff"/>
  </clipPath>
  <g clip-path="url(#r)">
    <rect width="{label_width}" height="{height}" fill="#555"/>
    <rect x="{label_width}" width="{value_width}" height="{height}" fill="{color}"/>
    <rect width="{total_width}" height="{height}" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
    <text x="{label_text_x}" y="{text_y}" fill="#010101" fill-opacity=".3">{label}</text>
    <text x="{label_text_x}" y="{text_y - 1}">{label}</text>
    <text x="{value_text_x}" y="{text_y}" fill="#010101" fill-opacity=".3">{value_text}</text>
    <text x="{value_text_x}" y="{text_y - 1}">{value_text}</text>
  </g>
</svg>"""
    return svg


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a coverage SVG badge")
    parser.add_argument(
        "--coverage-xml",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to coverage.xml (default: coverage.xml)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/assets/badges/coverage.svg"),
        help="Output SVG path (default: docs/assets/badges/coverage.svg)",
    )
    parser.add_argument(
        "--percentage",
        type=float,
        default=None,
        help="Override coverage percentage (skip XML parsing)",
    )
    args = parser.parse_args(argv)

    if args.percentage is not None:
        percentage = args.percentage
    else:
        if not args.coverage_xml.exists():
            print(f"ERROR: Coverage XML not found at {args.coverage_xml}", file=sys.stderr)
            print("Run: pytest --cov=polaris --cov-report=xml", file=sys.stderr)
            return 1
        percentage = parse_coverage_xml(args.coverage_xml)

    svg = generate_svg(percentage)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(svg, encoding="utf-8")
    print(f"Badge written to {args.output} ({percentage:.1f}%)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
