"""OpenCode-style Typed Events for KernelOne.

This module provides a typed event system with:
- Zod-style discriminated union events using Pydantic
- Wildcard subscription support via EventRegistry
- Backward compatibility with existing MessageBus

Reference: OpenCode packages/opencode/src/bus/index.ts
"""

from polaris.kernelone.events.typed.bus_adapter import (
    MESSAGE_TYPE_TO_TYPED_EVENT,
    TYPED_EVENT_TO_MESSAGE_TYPE,
    TypedEventBusAdapter,
    get_default_adapter,
    init_default_adapter,
)
from polaris.kernelone.events.typed.registry import (
    EventPattern,
    EventRegistry,
    Subscription,
    emit_event,
    get_default_registry,
    subscribe,
    subscribe_once,
    unsubscribe,
)
from polaris.kernelone.events.typed.schemas import (
    # Audit events
    AuditCompleted,
    AuditCompletedPayload,
    BeliefChangeEvent,
    BeliefChangePayload,
    BudgetExceeded,
    BudgetExceededPayload,
    CautiousExecutionEvent,
    CautiousExecutionPayload,
    CompactRequested,
    CompactRequestedPayload,
    ConfidenceCalibrationEvent,
    ConfidenceCalibrationPayload,
    # Context events
    ContextWindowStatus,
    ContextWindowStatusPayload,
    CriticalThinkingEvent,
    CriticalThinkingPayload,
    DirectorPaused,
    DirectorPausedPayload,
    DirectorResumed,
    DirectorResumedPayload,
    # Director events
    DirectorStarted,
    DirectorStartedPayload,
    DirectorStopped,
    DirectorStoppedPayload,
    # Base types
    EventBase,
    # Event categories
    EventCategory,
    EventPayload,
    EvolutionEvent,
    EvolutionPayload,
    FileWritten,
    FileWrittenPayload,
    InstanceDisposed,
    InstanceDisposedPayload,
    # Lifecycle events
    InstanceStarted,
    InstanceStartedPayload,
    IntentDetectedEvent,
    IntentDetectedPayload,
    NagReminder,
    NagReminderPayload,
    PerceptionCompletedEvent,
    PerceptionCompletedPayload,
    PlanCreated,
    PlanCreatedPayload,
    ReasoningCompletedEvent,
    ReasoningCompletedPayload,
    ReflectionEvent,
    ReflectionPayload,
    SettingsChanged,
    SettingsChangedPayload,
    # System events
    SystemError,
    SystemErrorPayload,
    TaskCancelled,
    TaskCancelledPayload,
    TaskClaimed,
    TaskClaimedPayload,
    TaskCompleted,
    TaskCompletedPayload,
    TaskFailed,
    TaskFailedPayload,
    TaskProgress,
    TaskProgressPayload,
    TaskRetry,
    TaskRetryPayload,
    TaskStarted,
    TaskStartedPayload,
    TaskSubmitted,
    TaskSubmittedPayload,
    # Cognitive events
    ThinkingPhaseEvent,
    ThinkingPhasePayload,
    ToolBlocked,
    ToolBlockedPayload,
    ToolCompleted,
    ToolCompletedPayload,
    ToolError,
    ToolErrorKind,
    ToolErrorPayload,
    # Tool events
    ToolInvoked,
    ToolInvokedPayload,
    ToolTimeout,
    ToolTimeoutPayload,
    TurnCompleted,
    TurnCompletedPayload,
    TurnFailed,
    TurnFailedPayload,
    # Turn events
    TurnStarted,
    TurnStartedPayload,
    # TypedEvent union
    TypedEvent,
    ValueAlignmentEvent,
    ValueAlignmentPayload,
    WorkerBusy,
    WorkerBusyPayload,
    WorkerReady,
    WorkerReadyPayload,
    WorkerSpawned,
    WorkerSpawnedPayload,
    WorkerStopped,
    WorkerStoppedPayload,
    WorkerStopping,
    WorkerStoppingPayload,
)

__all__ = [
    # Adapter mappings
    "MESSAGE_TYPE_TO_TYPED_EVENT",
    "TYPED_EVENT_TO_MESSAGE_TYPE",
    # Audit
    "AuditCompleted",
    "AuditCompletedPayload",
    "BudgetExceeded",
    "BudgetExceededPayload",
    "CompactRequested",
    "CompactRequestedPayload",
    # Context
    "ContextWindowStatus",
    "ContextWindowStatusPayload",
    "DirectorPaused",
    "DirectorPausedPayload",
    "DirectorResumed",
    "DirectorResumedPayload",
    # Director
    "DirectorStarted",
    "DirectorStartedPayload",
    "DirectorStopped",
    "DirectorStoppedPayload",
    # Base
    "EventBase",
    # Categories
    "EventCategory",
    "EventPattern",
    "EventPayload",
    # Registry
    "EventRegistry",
    "FileWritten",
    "FileWrittenPayload",
    "InstanceDisposed",
    "InstanceDisposedPayload",
    # Lifecycle
    "InstanceStarted",
    "InstanceStartedPayload",
    "NagReminder",
    "NagReminderPayload",
    "PlanCreated",
    "PlanCreatedPayload",
    "SettingsChanged",
    "SettingsChangedPayload",
    "Subscription",
    # System
    "SystemError",
    "SystemErrorPayload",
    "TaskCancelled",
    "TaskCancelledPayload",
    "TaskClaimed",
    "TaskClaimedPayload",
    "TaskCompleted",
    "TaskCompletedPayload",
    "TaskFailed",
    "TaskFailedPayload",
    "TaskProgress",
    "TaskProgressPayload",
    "TaskRetry",
    "TaskRetryPayload",
    "TaskStarted",
    "TaskStartedPayload",
    "TaskSubmitted",
    "TaskSubmittedPayload",
    "ToolBlocked",
    "ToolBlockedPayload",
    "ToolCompleted",
    "ToolCompletedPayload",
    "ToolError",
    "ToolErrorKind",
    "ToolErrorPayload",
    # Tool
    "ToolInvoked",
    "ToolInvokedPayload",
    "ToolTimeout",
    "ToolTimeoutPayload",
    "TurnCompleted",
    "TurnCompletedPayload",
    "TurnFailed",
    "TurnFailedPayload",
    # Turn
    "TurnStarted",
    "TurnStartedPayload",
    # Union
    "TypedEvent",
    # Adapter
    "TypedEventBusAdapter",
    "WorkerBusy",
    "WorkerBusyPayload",
    "WorkerReady",
    "WorkerReadyPayload",
    "WorkerSpawned",
    "WorkerSpawnedPayload",
    "WorkerStopped",
    "WorkerStoppedPayload",
    "WorkerStopping",
    "WorkerStoppingPayload",
    # Cognitive events
    "ThinkingPhaseEvent",
    "ThinkingPhasePayload",
    "ReflectionEvent",
    "ReflectionPayload",
    "EvolutionEvent",
    "EvolutionPayload",
    "BeliefChangeEvent",
    "BeliefChangePayload",
    "ConfidenceCalibrationEvent",
    "ConfidenceCalibrationPayload",
    "PerceptionCompletedEvent",
    "PerceptionCompletedPayload",
    "ReasoningCompletedEvent",
    "ReasoningCompletedPayload",
    "IntentDetectedEvent",
    "IntentDetectedPayload",
    "CriticalThinkingEvent",
    "CriticalThinkingPayload",
    "CautiousExecutionEvent",
    "CautiousExecutionPayload",
    "ValueAlignmentEvent",
    "ValueAlignmentPayload",
    # Functions
    "emit_event",
    "get_default_adapter",
    "get_default_registry",
    "init_default_adapter",
    "subscribe",
    "subscribe_once",
    "unsubscribe",
]
