"""KernelOne storage layout exports."""

# StorageCategory is the single source of truth in contracts.py.
from .contracts import StorageCategory
from .layout import (
    UNSUPPORTED_PATH_PREFIX,
    StorageLayout,
    StorageRoots,
    WorkspaceRuntimeIdentity,
    clear_business_roots_resolver,
    clear_storage_roots_cache,
    default_kernelone_cache_base,
    default_ramdisk_root,
    kernelone_home,
    normalize_logical_rel_path,
    normalize_ramdisk_root,
    register_business_roots_resolver,
    resolve_global_path,
    resolve_logical_path,
    resolve_ramdisk_root,
    resolve_runtime_path,
    resolve_storage_roots,
    resolve_workspace_persistent_path,
    resolve_workspace_runtime_identity,
    state_to_ramdisk_enabled,
    workspace_key,
)
from .paths import (
    WORKSPACE_ARTIFACTS,
    WORKSPACE_SESSIONS,
    WORKSPACE_SIGNALS,
    WORKSPACE_TASKS,
    resolve_artifact_path,
    resolve_session_path,
    resolve_signal_path,
    resolve_taskboard_path,
)
from .policy import (
    STORAGE_POLICY_REGISTRY,
    Lifecycle,
    StoragePolicy,
    StoragePolicyService,
    get_category_for_path,
    get_lifecycle_for_path,
    get_policy_for_path,
    is_archive_eligible,
)

__all__ = [
    "STORAGE_POLICY_REGISTRY",
    "UNSUPPORTED_PATH_PREFIX",
    "WORKSPACE_ARTIFACTS",
    "WORKSPACE_SESSIONS",
    "WORKSPACE_SIGNALS",
    "WORKSPACE_TASKS",
    "Lifecycle",
    "StorageCategory",
    "StorageLayout",
    "StoragePolicy",
    "StoragePolicyService",
    "StorageRoots",
    "WorkspaceRuntimeIdentity",
    "clear_business_roots_resolver",
    "clear_storage_roots_cache",
    "default_kernelone_cache_base",
    "default_ramdisk_root",
    "get_category_for_path",
    "get_lifecycle_for_path",
    "get_policy_for_path",
    "is_archive_eligible",
    "kernelone_home",
    "normalize_logical_rel_path",
    "normalize_ramdisk_root",
    "register_business_roots_resolver",
    "resolve_artifact_path",
    "resolve_global_path",
    "resolve_logical_path",
    "resolve_ramdisk_root",
    "resolve_runtime_path",
    "resolve_session_path",
    "resolve_signal_path",
    "resolve_storage_roots",
    "resolve_taskboard_path",
    "resolve_workspace_persistent_path",
    "resolve_workspace_runtime_identity",
    "state_to_ramdisk_enabled",
    "workspace_key",
]
