"""KernelOne storage layout exports."""

# StorageCategory is the single source of truth in contracts.py.
from .contracts import StorageCategory
from .layout import (
    UNSUPPORTED_PATH_PREFIX,
    StorageLayout,
    StorageRoots,
    clear_business_roots_resolver,
    clear_storage_roots_cache,
    default_kernelone_cache_base,
    default_ramdisk_root,
    kernelone_home,
    normalize_logical_rel_path,
    normalize_ramdisk_root,
    register_business_roots_resolver,
    resolve_global_path,
    resolve_logical_path,
    resolve_ramdisk_root,
    resolve_runtime_path,
    resolve_storage_roots,
    resolve_workspace_persistent_path,
    state_to_ramdisk_enabled,
    workspace_key,
)
from .policy import (
    ARTIFACT_POLICY_METADATA,
    STORAGE_POLICY_REGISTRY,
    Lifecycle,
    StoragePolicy,
    StoragePolicyService,
    get_artifact_policy_metadata,
    get_category_for_path,
    get_lifecycle_for_path,
    get_policy_for_path,
    is_archive_eligible,
    should_archive_artifact,
    should_compress_artifact,
)

__all__ = [
    "ARTIFACT_POLICY_METADATA",
    "STORAGE_POLICY_REGISTRY",
    "UNSUPPORTED_PATH_PREFIX",
    "Lifecycle",
    "StorageCategory",
    "StorageLayout",
    "StoragePolicy",
    "StoragePolicyService",
    "StorageRoots",
    "clear_business_roots_resolver",
    "clear_storage_roots_cache",
    "default_kernelone_cache_base",
    "default_ramdisk_root",
    "get_artifact_policy_metadata",
    "get_category_for_path",
    "get_lifecycle_for_path",
    "get_policy_for_path",
    "is_archive_eligible",
    "kernelone_home",
    "normalize_logical_rel_path",
    "normalize_ramdisk_root",
    "register_business_roots_resolver",
    "resolve_global_path",
    "resolve_logical_path",
    "resolve_ramdisk_root",
    "resolve_runtime_path",
    "resolve_storage_roots",
    "resolve_workspace_persistent_path",
    "should_archive_artifact",
    "should_compress_artifact",
    "state_to_ramdisk_enabled",
    "workspace_key",
]
