# mypy: disable-error-code="attr-defined"
from __future__ import annotations

import logging
import time

from polaris.cells.runtime.task_market.public.contracts import (
    AcknowledgeTaskStageCommandV1,
    TaskMarketError,
    TaskWorkItemResultV1,
)

from ..lease_manager import LeaseManager
from ..models import (
    TERMINAL_STATUSES,
    now_iso,
)

logger = logging.getLogger(__name__.rsplit(".", 1)[0])


class AcknowledgeMixin:
    """Acknowledge stage transitions."""

    # ---- Acknowledge --------------------------------------------------------

    def acknowledge_task_stage(self, command: AcknowledgeTaskStageCommandV1) -> TaskWorkItemResultV1:
        t0 = time.monotonic()
        with self._workspace_lock(command.workspace):
            store = self._get_store(command.workspace)
            items = store.load_items()
            item = self._require_item(items, command.task_id)

            # Validate lease token.
            lm = LeaseManager(store)
            lm.validate_token(item, command.lease_token)

            previous_status = item.status
            previous_version = int(item.version)
            ack_metadata = dict(command.metadata)

            # Determine next status.
            if command.next_stage is not None:
                self._fsm.validate_transition(item, "ack", next_stage=command.next_stage)
                next_is_leaf = False if ack_metadata.get("is_leaf") is False else item.is_leaf
                if previous_status == "in_execution" and command.next_stage == "pending_exec" and next_is_leaf:
                    raise TaskMarketError(
                        "Leaf execution work items cannot acknowledge directly back to pending_exec; use fail/requeue",
                        code="leaf_execution_ack_requeue_forbidden",
                        details={
                            "task_id": item.task_id,
                            "from_status": previous_status,
                            "next_stage": command.next_stage,
                        },
                    )
                item.stage = command.next_stage
                item.status = command.next_stage
                # A stage advance opens a fresh attempt budget: attempts
                # burned at the previous stage must not be charged to the
                # next one (live I3-r9: a step that succeeded on exec
                # attempt 3/3 was retry-exhausted-killed by the QA queue
                # claim before QA ever judged it).
                item.attempts = 0
            else:
                terminal_status = str(command.terminal_status or "resolved").strip().lower()
                if terminal_status not in TERMINAL_STATUSES:
                    raise TaskMarketError(
                        f"Unsupported terminal status: {terminal_status}",
                        code="unsupported_terminal_status",
                        details={"task_id": item.task_id, "status": terminal_status},
                    )
                self._fsm.validate_transition(item, "ack", terminal_status=terminal_status)
                item.status = terminal_status

            item.metadata = dict(item.metadata)
            item.metadata["last_summary"] = command.summary
            item.metadata["last_ack_metadata"] = ack_metadata
            # Three-tier fission: when CE fissions a task into leaf steps it
            # demotes the parent to a supervision row; the market record must
            # reflect that so the exec claim gate can skip it.
            if ack_metadata.get("is_leaf") is False:
                item.is_leaf = False

            # Merge ack metadata into item.payload so downstream consumers (Director, QA)
            # can access fields generated by upstream workers (CE sets blueprint_id, guardrails, etc.).
            item.payload = {**dict(item.payload), **dict(command.metadata)}
            # A successful advance retires the failure teaching — stale
            # bounce reasons must not leak into the next stage's context.
            item.payload.pop("last_failure", None)

            # Clear lease.
            lm.clear_lease(item)
            item.version += 1
            item.updated_at = now_iso()

            items[item.task_id] = item

            transition = {
                "task_id": item.task_id,
                "from_status": previous_status,
                "to_status": item.status,
                "event_type": "acknowledged",
                "worker_id": item.claimed_by or "",
                "lease_token": command.lease_token,
                "version": item.version,
                "metadata": {
                    "trace_id": item.trace_id,
                    "from_status": previous_status,
                    "to_status": item.status,
                    "next_stage": command.next_stage or "",
                    "summary": command.summary,
                },
            }

            outbox = self._build_outbox_record(
                workspace=command.workspace,
                event_type="task_market.stage_acknowledged",
                run_id=item.run_id,
                task_id=item.task_id,
                payload={
                    "trace_id": item.trace_id,
                    "from_status": previous_status,
                    "to_status": item.status,
                    "next_stage": command.next_stage or "",
                },
            )
            lifecycle_evidence = self._record_cognitive_runtime_lifecycle_receipt(
                item=item,
                event_type="acknowledged",
                from_status=previous_status,
                to_status=item.status,
                worker_id=item.claimed_by or "",
                lease_token=command.lease_token,
                metadata={
                    "next_stage": command.next_stage or "",
                    "terminal_status": command.terminal_status or "",
                    "summary": command.summary,
                    "ack_metadata": dict(command.metadata),
                },
            )
            self._attach_lifecycle_evidence(
                item=item,
                transition=transition,
                outbox_record=outbox,
                evidence=lifecycle_evidence,
            )
            items[item.task_id] = item

            self._atomic_save_changed_items(
                store=store,
                items=items,
                transitions=[transition],
                outbox_records=[outbox],
                expected_versions={item.task_id: previous_version},
            )

            if command.next_stage == "waiting_human":
                escalation = self._escalate_to_human_review_no_lock(
                    workspace=command.workspace,
                    store=store,
                    task_id=item.task_id,
                    reason=str(command.summary or "qa_waiting_human").strip() or "qa_waiting_human",
                    requested_by="acknowledge_task_stage",
                )
                item = escalation["item"]

            self._observe(
                "acknowledge",
                (time.monotonic() - t0) * 1000.0,
                stage=item.stage,
                task_id=item.task_id,
                trace_id=item.trace_id,
            )
            return self._result_from_item(item, reason="acknowledged")
